trigger:
  branches:
    include:
    - '*sprint*'
pr:
  autoCancel: false
  drafts: false
  branches:
    include:
    - '*sprint*'
name: Function-Consumption-$(SourceBranchName)-$(Date:MM-dd-yyyy)$(Rev:.r)
resources:
  repositories:
  - repository: self
    type: git
  - repository: templates
    type: github
    name: Infogix/govern-pipeline-templates
    ref: refs/heads/main
    endpoint: 'govern-build - Service Endpoint'
stages:
- stage: BUILD_NAME
  displayName: 'Set build name'
  dependsOn: []
  jobs:
  - template: build/jobs/job-build-name.yml@templates
- stage: BUILD_SOLUTION
  displayName: 'Build .Net core solution'
  dependsOn: []
  jobs:
  - template: build/jobs/job-dotnet-core-build.yml@templates
    parameters:
      solutionPath: igx.functions/igx.functions.consumption.csproj
      workingDirectory: igx.functions
      artifactName: functionConsumption