<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="DatabaseTaskProcessor.cs" />
    <Compile Remove="DisplayValueChecker.cs" />
    <Compile Remove="DisplayValueUpdateProcessor.cs" />
    <Compile Remove="IndexMaintainance.cs" />
    <Compile Remove="PostExecutionJobProcessor.cs" />
    <Compile Remove="ResourceCache.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.21" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.13.4" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.21.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\d360.core\d360.core.csproj" />
    <ProjectReference Include="..\d360.extensions.events\d360.extensions.events.csproj" />
    <ProjectReference Include="..\d360.extensions.mail\d360.extensions.mail.csproj" />
    <ProjectReference Include="..\d360.extensions.search\d360.extensions.search.csproj" />
    <ProjectReference Include="..\d360.extensions\d360.extensions.csproj" />
    <ProjectReference Include="..\d360.model\d360.model.csproj" />
    <ProjectReference Include="..\d360.utils.company\d360.utils.company.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
