<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net48</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Dapper" Version="2.1.21" />
	  <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	  <PackageReference Include="morelinq" Version="4.0.0" />
	  <PackageReference Include="NEST" Version="6.8.9" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\d360.core\d360.core.csproj" />
	  <ProjectReference Include="..\d360.extensions\d360.extensions.csproj" />
	</ItemGroup>

</Project>
