import { Component, Input, Output, EventEmitter} from '@angular/core';
import { BaseComponent } from './base.component';

@Component({
    selector: 'd3s-icon-picker',
    template: `
                <select name="icon" [ngModel]="ngModel" (ngModelChange)="ngModel=$event;ngModelChange.emit(ngModel);" style="width:100%">
                    <optgroup label="Web Application Icons">
                        <option value="fa-adjust">adjust</option>
                        <option value="fa-asterisk">asterisk</option>
                        <option value="fa-ban-circle">ban-circle</option>
                        <option value="fa-bar-chart">bar-chart</option>
                        <option value="fa-barcode">barcode</option>                        
                        <option value="fa-beer">beer</option>
                        <option value="fa-bell">bell</option>
                        <option value="fa-bell-alt">bell-alt</option>
                        <option value="fa-bolt">bolt</option>
                        <option value="fa-book">book</option>
                        <option value="fa-bookmark">bookmark</option>
                        <option value="fa-bookmark-empty">bookmark-empty</option>
                        <option value="fa-briefcase">briefcase</option>
                        <option value="fa-bullhorn">bullhorn</option>
                        <option value="fa-calendar">calendar</option>
                        <option value="fa-camera">camera</option>
                        <option value="fa-camera-retro">camera-retro</option>
                        <option value="fa-certificate">certificate</option>
                        <option value="fa-check">check</option>
                        <option value="fa-check-empty">check-empty</option>
                        <option value="fa-circle">circle</option>
                        <option value="fa-circle-blank">circle-blank</option>
                        <option value="fa-cloud">cloud</option>
                        <option value="fa-cloud-download">cloud-download</option>
                        <option value="fa-cloud-upload">cloud-upload</option>
                        <option value="fa-coffee">coffee</option>
                        <option value="fa-cog">cog</option>
                        <option value="fa-cogs">cogs</option>
                        <option value="fa-comment">comment</option>
                        <option value="fa-comment-alt">comment-alt</option>
                        <option value="fa-comments">comments</option>
                        <option value="fa-comments-alt">comments-alt</option>
                        <option value="fa-credit-card">credit-card</option>
                        <option value="fa-dashboard">dashboard</option>
                        <option value="fa-desktop">desktop</option>
                        <option value="fa-download">download</option>
                        <option value="fa-download-alt">download-alt</option>
                        <option value="fa-edit">edit</option>
                        <option value="fa-envelope">envelope</option>
                        <option value="fa-envelope-alt">envelope-alt</option>
                        <option value="fa-exchange">exchange</option>
                        <option value="fa-exclamation-sign">exclamation-sign</option>
                        <option value="fa-external-link">external-link</option>
                        <option value="fa-eye-close">eye-close</option>
                        <option value="fa-eye-open">eye-open</option>
                        <option value="fa-facetime-video">facetime-video</option>
                        <option value="fa-fighter-jet">fighter-jet</option>
                        <option value="fa-film">film</option>
                        <option value="fa-filter">filter</option>
                        <option value="fa-fire">fire</option>
                        <option value="fa-flag">flag</option>
                        <option value="fa-folder-close">folder-close</option>
                        <option value="fa-folder-open">folder-open</option>
                        <option value="fa-folder-close-alt">folder-close-alt</option>
                        <option value="fa-folder-open-alt">folder-open-alt</option>
                        <option value="fa-food">food</option>
                        <option value="fa-gift">gift</option>
                        <option value="fa-glass">glass</option>
                        <option value="fa-globe">globe</option>
                        <option value="fa-group">group</option>
                        <option value="fa-hdd">hdd</option>
                        <option value="fa-headphones">headphones</option>
                        <option value="fa-heart">heart</option>
                        <option value="fa-heart-empty">heart-empty</option>
                        <option value="fa-home">home</option>
                        <option value="fa-inbox">inbox</option>
                        <option value="fa-info-sign">info-sign</option>
                        <option value="fa-key">key</option>
                        <option value="fa-leaf">leaf</option>
                        <option value="fa-laptop">laptop</option>
                        <option value="fa-legal">legal</option>
                        <option value="fa-lemon">lemon</option>
                        <option value="fa-lightbulb">lightbulb</option>
                        <option value="fa-lock">lock</option>
                        <option value="fa-unlock">unlock</option>
                        <option value="fa-magic">magic</option>
                        <option value="fa-magnet">magnet</option>
                        <option value="fa-map-marker">map-marker</option>
                        <option value="fa-minus">minus</option>
                        <option value="fa-minus-sign">minus-sign</option>
                        <option value="fa-mobile-phone">mobile-phone</option>
                        <option value="fa-money">money</option>
                        <option value="fa-move">move</option>
                        <option value="fa-music">music</option>
                        <option value="fa-off">off</option>
                        <option value="fa-ok">ok</option>
                        <option value="fa-ok-circle">ok-circle</option>
                        <option value="fa-ok-sign">ok-sign</option>
                        <option value="fa-pencil">pencil</option>
                        <option value="fa-picture">picture</option>
                        <option value="fa-plane">plane</option>
                        <option value="fa-plus">plus</option>
                        <option value="fa-plus-sign">plus-sign</option>
                        <option value="fa-print">print</option>
                        <option value="fa-pushpin">pushpin</option>
                        <option value="fa-qrcode">qrcode</option>
                        <option value="fa-question-sign">question-sign</option>
                        <option value="fa-quote-left">quote-left</option>
                        <option value="fa-quote-right">quote-right</option>
                        <option value="fa-random">random</option>
                        <option value="fa-refresh">refresh</option>
                        <option value="fa-remove">remove</option>
                        <option value="fa-remove-circle">remove-circle</option>
                        <option value="fa-remove-sign">remove-sign</option>
                        <option value="fa-reorder">reorder</option>
                        <option value="fa-reply">reply</option>
                        <option value="fa-resize-horizontal">resize-horizontal</option>
                        <option value="fa-resize-vertical">resize-vertical</option>
                        <option value="fa-retweet">retweet</option>
                        <option value="fa-road">road</option>
                        <option value="fa-rss">rss</option>
                        <option value="fa-screenshot">screenshot</option>
                        <option value="fa-search">search</option>
                        <option value="fa-share">share</option>
                        <option value="fa-share-alt">share-alt</option>
                        <option value="fa-shopping-cart">shopping-cart</option>
                        <option value="fa-signal">signal</option>
                        <option value="fa-signin">signin</option>
                        <option value="fa-signout">signout</option>
                        <option value="fa-sitemap">sitemap</option>
                        <option value="fa-sort">sort</option>
                        <option value="fa-sort-down">sort-down</option>
                        <option value="fa-sort-up">sort-up</option>
                        <option value="fa-spinner">spinner</option>
                        <option value="fa-star">star</option>
                        <option value="fa-star-empty">star-empty</option>
                        <option value="fa-star-half">star-half</option>
                        <option value="fa-tablet">tablet</option>
                        <option value="fa-tag">tag</option>
                        <option value="fa-tags">tags</option>
                        <option value="fa-tasks">tasks</option>
                        <option value="fa-thumbs-down">thumbs-down</option>
                        <option value="fa-thumbs-up">thumbs-up</option>
                        <option value="fa-time">time</option>
                        <option value="fa-tint">tint</option>
                        <option value="fa-trash">trash</option>
                        <option value="fa-trophy">trophy</option>
                        <option value="fa-truck">truck</option>
                        <option value="fa-umbrella">umbrella</option>
                        <option value="fa-upload">upload</option>
                        <option value="fa-upload-alt">upload-alt</option>
                        <option value="fa-user">user</option>
                        <option value="fa-user-md">user-md</option>
                        <option value="fa-volume-off">volume-off</option>
                        <option value="fa-volume-down">volume-down</option>
                        <option value="fa-volume-up">volume-up</option>
                        <option value="fa-warning-sign">warning-sign</option>
                        <option value="fa-wrench">wrench</option>
                        <option value="fa-zoom-in">zoom-in</option>
                        <option value="fa-zoom-out">zoom-out</option>
                </optgroup>
                <optgroup label="Text Editor Icons">
                        <option value="fa-file">file</option>
                        <option value="fa-file-alt">file-alt</option>
                        <option value="fa-cut">cut</option>
                        <option value="fa-copy">copy</option>
                        <option value="fa-paste">paste</option>
                        <option value="fa-save">save</option>
                        <option value="fa-undo">undo</option>
                        <option value="fa-repeat">repeat</option>
                        <option value="fa-text-height">text-height</option>
                        <option value="fa-text-width">text-width</option>
                        <option value="fa-align-left">align-left</option>
                        <option value="fa-align-center">align-center</option>
                        <option value="fa-align-right">align-right</option>
                        <option value="fa-align-justify">align-justify</option>
                        <option value="fa-indent-left">indent-left</option>
                        <option value="fa-indent-right">indent-right</option>
                        <option value="fa-font">font</option>
                        <option value="fa-bold">bold</option>
                        <option value="fa-italic">italic</option>
                        <option value="fa-strikethrough">strikethrough</option>
                        <option value="fa-underline">underline</option>
                        <option value="fa-link">link</option>
                        <option value="fa-paper-clip">paper-clip</option>
                        <option value="fa-columns">columns</option>
                        <option value="fa-table">table</option>
                        <option value="fa-th-large">th-large</option>
                        <option value="fa-th">th</option>
                        <option value="fa-th-list">th-list</option>
                        <option value="fa-list">list</option>
                        <option value="fa-list-ol">list-ol</option>
                        <option value="fa-list-ul">list-ul</option>
                        <option value="fa-list-alt">list-alt</option>
                </optgroup>
                <optgroup label="Directional Icons">
                        <option value="fa-angle-left">angle-left</option>
                        <option value="fa-angle-right">angle-right</option>
                        <option value="fa-angle-up">angle-up</option>
                        <option value="fa-angle-down">angle-down</option>
                        <option value="fa-arrow-down">arrow-down</option>
                        <option value="fa-arrow-left">arrow-left</option>
                        <option value="fa-arrow-right">arrow-right</option>
                        <option value="fa-arrow-up">arrow-up</option>
                        <option value="fa-caret-down">caret-down</option>
                        <option value="fa-caret-left">caret-left</option>
                        <option value="fa-caret-right">caret-right</option>
                        <option value="fa-caret-up">caret-up</option>
                        <option value="fa-chevron-down">chevron-down</option>
                        <option value="fa-chevron-left">chevron-left</option>
                        <option value="fa-chevron-right">chevron-right</option>
                        <option value="fa-chevron-up">chevron-up</option>
                        <option value="fa-arrow-circle-down">arrow-circle-down</option>
                        <option value="fa-arrow-circle-left">arrow-circle-left</option>
                        <option value="fa-arrow-circle-right">arrow-circle-right</option>
                        <option value="fa-arrow-circle-up">arrow-circle-up</option>
                        <option value="fa-angle-double-left">angle-double-left</option>
                        <option value="fa-angle-double-right">angle-double-right</option>
                        <option value="fa-angle-double-up">angle-double-up</option>
                        <option value="fa-angle-double-down">angle-double-down</option>
                        <option value="fa-hand-down">hand-down</option>
                        <option value="fa-hand-left">hand-left</option>
                        <option value="fa-hand-right">hand-right</option>
                        <option value="fa-hand-up">hand-up</option>
                        <option value="fa-circle">circle</option>
                        <option value="fa-circle-blank">circle-blank</option>
              </optgroup>
              <optgroup label="Video Player Icons">
                        <option value="fa-play-circle">play-circle</option>
                        <option value="fa-play">play</option>
                        <option value="fa-pause">pause</option>
                        <option value="fa-stop">stop</option>
                        <option value="fa-step-backward">step-backward</option>
                        <option value="fa-fast-backward">fast-backward</option>
                        <option value="fa-backward">backward</option>
                        <option value="fa-forward">forward</option>
                        <option value="fa-fast-forward">fast-forward</option>
                        <option value="fa-step-forward">step-forward</option>
                        <option value="fa-eject">eject</option>
                        <option value="fa-fullscreen">fullscreen</option>
                        <option value="fa-resize-full">resize-full</option>
                        <option value="fa-resize-small">resize-small</option>
              </optgroup>            
            <optgroup label="Medical Icons">
                        <option value="fa-ambulance">ambulance</option>                                                                   
                        <option value="fa-heart-o">heart</option>
                        <option value="fa-heart">heart filled</option>
                        <option value="fa-heartbeat">heartbeat</option>
                        <option value="fa-hospital-o">hospital</option>
                        <option value="fa-h-square">hospital sign</option>
                        <option value="fa-medkit">medkit</option>
                        <option value="fa-plus-square">plus-square</option>
                        <option value="fa-stethoscope">stethoscope</option>
                        <option value="fa-user-md">user-md</option>
                        <option value="fa-wheelchair">wheelchair</option>
                        <option value="fa-wheelchair-alt">wheelchair alt</option>
            </optgroup>
        </select>
    `
})

export class IconPickerComponent extends BaseComponent {
    @Input() ngModel: string;
    @Output() ngModelChange = new EventEmitter();
}
