<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net48</TargetFrameworks>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Dapper" Version="2.1.21" />
	  <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
	  <PackageReference Include="Dapper.ParameterExtensions" Version="2022.7.7.1" />
	  <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\repositories\repositories.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Compile Update=".\Catalog.*.cs">
			<DependentUpon>.\Catalog.cs</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Update=".\Community.*.cs">
			<DependentUpon>.\Community.cs</DependentUpon>
		</Compile>
	</ItemGroup>
	
	
</Project>
