<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="igx.function.Fusion.csproj.vspscc" />
  </ItemGroup>
  <ItemGroup>    
    <PackageReference Include="Dapper" Version="1.50.2" />    
    <PackageReference Include="EnterpriseLibrary.TransientFaultHandling" Version="6.0.1304" />    
    <PackageReference Include="EnterpriseLibrary.TransientFaultHandling.Data" Version="6.0.1304.1" />    
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.6" />    
    <PackageReference Include="WindowsAzure.Storage" Version="8.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\d360.core\d360.core.csproj" />
    <ProjectReference Include="..\d360.extensions\d360.extensions.csproj" />
    <ProjectReference Include="..\igx.function\igx.function.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
