//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.web.App_GlobalResources.Actions", typeof(Actions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plus.
        /// </summary>
        public static string Add_Icon {
            get {
                return ResourceManager.GetString("Add_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string AddClaim_Text {
            get {
                return ResourceManager.GetString("AddClaim_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string AddField_Text {
            get {
                return ResourceManager.GetString("AddField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibility.
        /// </summary>
        public static string AddGovernance_Text {
            get {
                return ResourceManager.GetString("AddGovernance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string AddLevel_Text {
            get {
                return ResourceManager.GetString("AddLevel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcing.
        /// </summary>
        public static string AddSourceResponsibility_Text {
            get {
                return ResourceManager.GetString("AddSourceResponsibility_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Responsibilities.
        /// </summary>
        public static string AddVerticalSecurity_Text {
            get {
                return ResourceManager.GetString("AddVerticalSecurity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.
        /// </summary>
        public static string Allocation_Icon {
            get {
                return ResourceManager.GetString("Allocation_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string Allocation_Text {
            get {
                return ResourceManager.GetString("Allocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Type.
        /// </summary>
        public static string ArtifactType_Text {
            get {
                return ResourceManager.GetString("ArtifactType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string Attributes_Icon {
            get {
                return ResourceManager.GetString("Attributes_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Group.
        /// </summary>
        public static string AttributeType_Text {
            get {
                return ResourceManager.GetString("AttributeType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.
        /// </summary>
        public static string Audit_Icon {
            get {
                return ResourceManager.GetString("Audit_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string Board_Icon {
            get {
                return ResourceManager.GetString("Board_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string Challenge {
            get {
                return ResourceManager.GetString("Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        public static string Challenge_Icon {
            get {
                return ResourceManager.GetString("Challenge_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Artifact Type.
        /// </summary>
        public static string ChildArtifactType_Text {
            get {
                return ResourceManager.GetString("ChildArtifactType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Attribute Type.
        /// </summary>
        public static string ChildAttributeType_Text {
            get {
                return ResourceManager.GetString("ChildAttributeType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trash-o.
        /// </summary>
        public static string Delete_Icon {
            get {
                return ResourceManager.GetString("Delete_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sitemap.
        /// </summary>
        public static string Diagram_Icon {
            get {
                return ResourceManager.GetString("Diagram_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pencil.
        /// </summary>
        public static string Edit_Icon {
            get {
                return ResourceManager.GetString("Edit_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloud-download.
        /// </summary>
        public static string ExportToExcel_Icon {
            get {
                return ResourceManager.GetString("ExportToExcel_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportToExcel_Text {
            get {
                return ResourceManager.GetString("ExportToExcel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to columns.
        /// </summary>
        public static string Fields_Icon {
            get {
                return ResourceManager.GetString("Fields_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmark.
        /// </summary>
        public static string Follow_Icon {
            get {
                return ResourceManager.GetString("Follow_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bolt.
        /// </summary>
        public static string Fusion_Icon {
            get {
                return ResourceManager.GetString("Fusion_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governance.
        /// </summary>
        public static string Governance {
            get {
                return ResourceManager.GetString("Governance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legal.
        /// </summary>
        public static string Governance_Icon {
            get {
                return ResourceManager.GetString("Governance_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string Group_Icon {
            get {
                return ResourceManager.GetString("Group_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        public static string IntersectRoles {
            get {
                return ResourceManager.GetString("IntersectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string IntersectRoles_Icon {
            get {
                return ResourceManager.GetString("IntersectRoles_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Issue.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag.
        /// </summary>
        public static string Issue_Icon {
            get {
                return ResourceManager.GetString("Issue_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sitemap.
        /// </summary>
        public static string Levels_Icon {
            get {
                return ResourceManager.GetString("Levels_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code-fork.
        /// </summary>
        public static string Lineage_Icon {
            get {
                return ResourceManager.GetString("Lineage_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Predicates.
        /// </summary>
        public static string Predicates {
            get {
                return ResourceManager.GetString("Predicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map-signs.
        /// </summary>
        public static string Predicates_Icon {
            get {
                return ResourceManager.GetString("Predicates_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar-chart-o.
        /// </summary>
        public static string Report_Icon {
            get {
                return ResourceManager.GetString("Report_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Response Types.
        /// </summary>
        public static string ResponseTypes {
            get {
                return ResourceManager.GetString("ResponseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bullhorn.
        /// </summary>
        public static string ResponseTypes_Icon {
            get {
                return ResourceManager.GetString("ResponseTypes_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tachometer.
        /// </summary>
        public static string StatisticType_Icon {
            get {
                return ResourceManager.GetString("StatisticType_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytic Type.
        /// </summary>
        public static string StatisticType_Text {
            get {
                return ResourceManager.GetString("StatisticType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magnet.
        /// </summary>
        public static string SynonymType_Icon {
            get {
                return ResourceManager.GetString("SynonymType_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym Type.
        /// </summary>
        public static string SynonymType_Text {
            get {
                return ResourceManager.GetString("SynonymType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloud-download.
        /// </summary>
        public static string TemplateDownload_Icon {
            get {
                return ResourceManager.GetString("TemplateDownload_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Following.
        /// </summary>
        public static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmark-o.
        /// </summary>
        public static string Unfollow_Icon {
            get {
                return ResourceManager.GetString("Unfollow_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloud-upload.
        /// </summary>
        public static string Upload_Icon {
            get {
                return ResourceManager.GetString("Upload_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string Usage_Icon {
            get {
                return ResourceManager.GetString("Usage_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string User_Icon {
            get {
                return ResourceManager.GetString("User_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Relationships.
        /// </summary>
        public static string ViewRelationships {
            get {
                return ResourceManager.GetString("ViewRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retweet.
        /// </summary>
        public static string ViewRelationships_Icon {
            get {
                return ResourceManager.GetString("ViewRelationships_Icon", resourceCulture);
            }
        }
    }
}
