//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommentsAPIMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommentsAPIMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommentsAPIMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to create this comment..
        /// </summary>
        internal static string CommentCreatePermission {
            get {
                return ResourceManager.GetString("CommentCreatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment with Uid {0} does not exist..
        /// </summary>
        internal static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to successfully remove comment. Please try again later..
        /// </summary>
        internal static string CommentRetryRemove {
            get {
                return ResourceManager.GetString("CommentRetryRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to view comments..
        /// </summary>
        internal static string CommentViewPermission {
            get {
                return ResourceManager.GetString("CommentViewPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting this comment.
        /// </summary>
        internal static string ErrorDeletingComment {
            get {
                return ResourceManager.GetString("ErrorDeletingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving comments.
        /// </summary>
        internal static string ErrorGetComment {
            get {
                return ResourceManager.GetString("ErrorGetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving rolled up counts by comment type.
        /// </summary>
        internal static string ErrorGetRollupCount {
            get {
                return ResourceManager.GetString("ErrorGetRollupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving voters based on the comment.
        /// </summary>
        internal static string ErrorGetVoterBasedOnComment {
            get {
                return ResourceManager.GetString("ErrorGetVoterBasedOnComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving voters based on the comment and emoji.
        /// </summary>
        internal static string ErrorGetVoterBasedOnCommentEmoji {
            get {
                return ResourceManager.GetString("ErrorGetVoterBasedOnCommentEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating comment.
        /// </summary>
        internal static string ErrorUpdateComment {
            get {
                return ResourceManager.GetString("ErrorUpdateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing your vote on the comment using this emoji.
        /// </summary>
        internal static string RestrictVoteRemove {
            get {
                return ResourceManager.GetString("RestrictVoteRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to see rolled up counts by comment type..
        /// </summary>
        internal static string RollupCountPermission {
            get {
                return ResourceManager.GetString("RollupCountPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to see voters for this comment..
        /// </summary>
        internal static string VotePermission {
            get {
                return ResourceManager.GetString("VotePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while voting on the comment using this emoji.
        /// </summary>
        internal static string VotingOnCommentUsingEmoji {
            get {
                return ResourceManager.GetString("VotingOnCommentUsingEmoji", resourceCulture);
            }
        }
    }
}
