//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataProfileAPIMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataProfileAPIMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.web.App_GlobalResources.DataProfileAPIMessages", typeof(DataProfileAPIMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Info.
        /// </summary>
        public static string ApiSheetName {
            get {
                return ResourceManager.GetString("ApiSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset ID.
        /// </summary>
        public static string AssetIdColumn {
            get {
                return ResourceManager.GetString("AssetIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Path.
        /// </summary>
        public static string AssetPathColumn {
            get {
                return ResourceManager.GetString("AssetPathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string AssetSheetName {
            get {
                return ResourceManager.GetString("AssetSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type Path.
        /// </summary>
        public static string AssetTypePathColumn {
            get {
                return ResourceManager.GetString("AssetTypePathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type Uid.
        /// </summary>
        public static string AssetTypeUidColumn {
            get {
                return ResourceManager.GetString("AssetTypeUidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset UID.
        /// </summary>
        public static string AssetUidColumn {
            get {
                return ResourceManager.GetString("AssetUidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exist for AssetUid {0} and ProfileSetDate {1}.
        /// </summary>
        public static string AssetUidProfileSetDateRecordNotfound {
            get {
                return ResourceManager.GetString("AssetUidProfileSetDateRecordNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset URL.
        /// </summary>
        public static string AssetUrlColumn {
            get {
                return ResourceManager.GetString("AssetUrlColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Type.
        /// </summary>
        public static string BaseTypeColumn {
            get {
                return ResourceManager.GetString("BaseTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorColumn {
            get {
                return ResourceManager.GetString("ColorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only delete a maximum of {0} dataprofile records in this request. Please use the BATCH API endpoint..
        /// </summary>
        public static string DataProfileDeleteMaxLimit {
            get {
                return ResourceManager.GetString("DataProfileDeleteMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only provide a maximum of {0} Data Profile records in this request. Please call the BATCH API to submit more than {1} items..
        /// </summary>
        public static string DataProfileRecordsLimit {
            get {
                return ResourceManager.GetString("DataProfileRecordsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionColumn {
            get {
                return ResourceManager.GetString("DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string DisabledColumn {
            get {
                return ResourceManager.GetString("DisabledColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Records: {0}. AssetUid and ProfileSetDate pairs are used as record identifiers and must be unique within a batch..
        /// </summary>
        public static string DuplicateRecordBatchProfile {
            get {
                return ResourceManager.GetString("DuplicateRecordBatchProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From.
        /// </summary>
        public static string EffectiveFromColumn {
            get {
                return ResourceManager.GetString("EffectiveFromColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Through.
        /// </summary>
        public static string EffectiveThroughColumn {
            get {
                return ResourceManager.GetString("EffectiveThroughColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements in bottomK cannot be Empty strings.
        /// </summary>
        public static string ElementBottomKNotEmpty {
            get {
                return ResourceManager.GetString("ElementBottomKNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements in topK cannot be Empty string.
        /// </summary>
        public static string ElementTopKNotEmpty {
            get {
                return ResourceManager.GetString("ElementTopKNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This endpoint is not accessible..
        /// </summary>
        public static string EndpointNotAccessible {
            get {
                return ResourceManager.GetString("EndpointNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on request..
        /// </summary>
        public static string ErrorOnRequest {
            get {
                return ResourceManager.GetString("ErrorOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Filter.
        /// </summary>
        public static string HeaderFilterColumn {
            get {
                return ResourceManager.GetString("HeaderFilterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Filter Confidence.
        /// </summary>
        public static string HeaderFilterConfidenceColumn {
            get {
                return ResourceManager.GetString("HeaderFilterConfidenceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter &apos;_order&apos;. Allowed values are &apos;path&apos; and &apos;tags&apos;..
        /// </summary>
        public static string InvalidOrder {
            get {
                return ResourceManager.GetString("InvalidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid similar type..
        /// </summary>
        public static string InvalidSimilarType {
            get {
                return ResourceManager.GetString("InvalidSimilarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Values.
        /// </summary>
        public static string InvalidValuesColumn {
            get {
                return ResourceManager.GetString("InvalidValuesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string JsonColumn {
            get {
                return ResourceManager.GetString("JsonColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered {0} {1} Fields List _{2}_.xlsx.
        /// </summary>
        public static string MatchedAssetExportFileName {
            get {
                return ResourceManager.GetString("MatchedAssetExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field Asset ID.
        /// </summary>
        public static string MatchedAssetIdColumn {
            get {
                return ResourceManager.GetString("MatchedAssetIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field Name.
        /// </summary>
        public static string MatchedAssetNameColumn {
            get {
                return ResourceManager.GetString("MatchedAssetNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field Asset Path.
        /// </summary>
        public static string MatchedAssetPathColumn {
            get {
                return ResourceManager.GetString("MatchedAssetPathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field Tags.
        /// </summary>
        public static string MatchedAssetTagsColumn {
            get {
                return ResourceManager.GetString("MatchedAssetTagsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field Asset Type Path.
        /// </summary>
        public static string MatchedAssetTypePathColumn {
            get {
                return ResourceManager.GetString("MatchedAssetTypePathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field Asset UID.
        /// </summary>
        public static string MatchedAssetUidColumn {
            get {
                return ResourceManager.GetString("MatchedAssetUidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field Url.
        /// </summary>
        public static string MatchedAssetUrlColumn {
            get {
                return ResourceManager.GetString("MatchedAssetUrlColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Type.
        /// </summary>
        public static string MatchTypeColumn {
            get {
                return ResourceManager.GetString("MatchTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string MaximumColumn {
            get {
                return ResourceManager.GetString("MaximumColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Confidence Parameter is invalid.
        /// </summary>
        public static string MinConfidenceInvalid {
            get {
                return ResourceManager.GetString("MinConfidenceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string MinimumColumn {
            get {
                return ResourceManager.GetString("MinimumColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Maximum Present.
        /// </summary>
        public static string MinimumMaximumPresentColumn {
            get {
                return ResourceManager.GetString("MinimumMaximumPresentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Samples.
        /// </summary>
        public static string MinimumSamplesColumn {
            get {
                return ResourceManager.GetString("MinimumSamplesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} signature not found for AssetUid {1}.
        /// </summary>
        public static string NoSimilarTypeForAssetUid {
            get {
                return ResourceManager.GetString("NoSimilarTypeForAssetUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter &apos;_order&apos;. Allowed values are &apos;confidence&apos;, &apos;path&apos; or &apos;assettypepath&apos;..
        /// </summary>
        public static string OrderInvalid {
            get {
                return ResourceManager.GetString("OrderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PriorityColumn {
            get {
                return ResourceManager.GetString("PriorityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists for AssetUid {0} and ProfileSetDate {1}.
        /// </summary>
        public static string ProfileRecordAlreadyExists {
            get {
                return ResourceManager.GetString("ProfileRecordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset class {0} does not support data profiling. Profiling data can only be associated with Business or Technical Asset types..
        /// </summary>
        public static string ProfilingNotSupportAssetClass {
            get {
                return ResourceManager.GetString("ProfilingNotSupportAssetClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifier.
        /// </summary>
        public static string QualifierColumn {
            get {
                return ResourceManager.GetString("QualifierColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string RegularExpressionColumn {
            get {
                return ResourceManager.GetString("RegularExpressionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to similarType is a required field..
        /// </summary>
        public static string RequiredSimilarType {
            get {
                return ResourceManager.GetString("RequiredSimilarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True/False (Boolean).
        /// </summary>
        public static string SemanticBaseTypeBoolean {
            get {
                return ResourceManager.GetString("SemanticBaseTypeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number ({0}).
        /// </summary>
        public static string SemanticBaseTypeNumber {
            get {
                return ResourceManager.GetString("SemanticBaseTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced (JSON).
        /// </summary>
        public static string SemanticMatchTypeAdvanced {
            get {
                return ResourceManager.GetString("SemanticMatchTypeAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Values.
        /// </summary>
        public static string SemanticMatchTypeList {
            get {
                return ResourceManager.GetString("SemanticMatchTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern in Data.
        /// </summary>
        public static string SemanticMatchTypePattern {
            get {
                return ResourceManager.GetString("SemanticMatchTypePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-In.
        /// </summary>
        public static string SemanticSourceBuiltIn {
            get {
                return ResourceManager.GetString("SemanticSourceBuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined.
        /// </summary>
        public static string SemanticSourceUserDefined {
            get {
                return ResourceManager.GetString("SemanticSourceUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Review.
        /// </summary>
        public static string SemanticStatusUnderReview {
            get {
                return ResourceManager.GetString("SemanticStatusUnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Asset list for {0} {1}.xlsx.
        /// </summary>
        public static string SemanticTypeAssetExportFilename {
            get {
                return ResourceManager.GetString("SemanticTypeAssetExportFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Semantic Types List {0}.xlsx.
        /// </summary>
        public static string SemanticTypeExportFilename {
            get {
                return ResourceManager.GetString("SemanticTypeExportFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Type Status List {0}.xlsx.
        /// </summary>
        public static string SemanticTypeStatusExportFilename {
            get {
                return ResourceManager.GetString("SemanticTypeStatusExportFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Type Uid.
        /// </summary>
        public static string SemanticTypeUidColumn {
            get {
                return ResourceManager.GetString("SemanticTypeUidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Type URL.
        /// </summary>
        public static string SemanticTypeURLColumn {
            get {
                return ResourceManager.GetString("SemanticTypeURLColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar.
        /// </summary>
        public static string Similar {
            get {
                return ResourceManager.GetString("Similar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Source.
        /// </summary>
        public static string SourceColumn {
            get {
                return ResourceManager.GetString("SourceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusColumn {
            get {
                return ResourceManager.GetString("StatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag field not found.
        /// </summary>
        public static string TagFieldNotFound {
            get {
                return ResourceManager.GetString("TagFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsColumn {
            get {
                return ResourceManager.GetString("TagsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string ThresholdColumn {
            get {
                return ResourceManager.GetString("ThresholdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Qualifier Parameter is invalid.
        /// </summary>
        public static string TypeQualifierInvalid {
            get {
                return ResourceManager.GetString("TypeQualifierInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Qualifier &apos;{0}&apos; does not exist.
        /// </summary>
        public static string TypeQualifierNotFound {
            get {
                return ResourceManager.GetString("TypeQualifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string UrlColumn {
            get {
                return ResourceManager.GetString("UrlColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Locales.
        /// </summary>
        public static string ValidLocalesColumn {
            get {
                return ResourceManager.GetString("ValidLocalesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Values.
        /// </summary>
        public static string ValidValuesColumn {
            get {
                return ResourceManager.GetString("ValidValuesColumn", resourceCulture);
            }
        }
    }
}
