//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.web.App_GlobalResources.FormInfo", typeof(FormInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify this {0} type using the form below..
        /// </summary>
        public static string Add_Asset_Type_Directions {
            get {
                return ResourceManager.GetString("Add_Asset_Type_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} Type.
        /// </summary>
        public static string Add_Asset_Type_Title {
            get {
                return ResourceManager.GetString("Add_Asset_Type_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string ArtifactType {
            get {
                return ResourceManager.GetString("ArtifactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify {0} Type.
        /// </summary>
        public static string Edit_Asset_Type_Title {
            get {
                return ResourceManager.GetString("Edit_Asset_Type_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Attribute.
        /// </summary>
        public static string FusionAttributeType {
            get {
                return ResourceManager.GetString("FusionAttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relationship type you are trying to delete has established relationships.  Please delete these prior to deleting the relationship type..
        /// </summary>
        public static string InUse_Error_Delete {
            get {
                return ResourceManager.GetString("InUse_Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relationship type is referenced by one or more field type definitions. Please update or delete these prior to deleting this relationship type..
        /// </summary>
        public static string InUse_RelationShipType_Error_Delete {
            get {
                return ResourceManager.GetString("InUse_RelationShipType_Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field type.
        /// </summary>
        public static string NoFormData_FieldType {
            get {
                return ResourceManager.GetString("NoFormData_FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Type.
        /// </summary>
        public static string OrganizationType {
            get {
                return ResourceManager.GetString("OrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to add this..
        /// </summary>
        public static string Permisions_Error_Add {
            get {
                return ResourceManager.GetString("Permisions_Error_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to remove this..
        /// </summary>
        public static string Permisions_Error_Delete {
            get {
                return ResourceManager.GetString("Permisions_Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to update this..
        /// </summary>
        public static string Permisions_Error_Edit {
            get {
                return ResourceManager.GetString("Permisions_Error_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string PolicyType {
            get {
                return ResourceManager.GetString("PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Responsibility Then Filter value is required.
        /// </summary>
        public static string Responsibility_Then_Filter_Value_Required {
            get {
                return ResourceManager.GetString("Responsibility_Then_Filter_Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Field type in When filters for this asset type..
        /// </summary>
        public static string Responsibility_Then_InvalidFieldType {
            get {
                return ResourceManager.GetString("Responsibility_Then_InvalidFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;The responsibility at lease one when filter required when ApplyToType is false..
        /// </summary>
        public static string Responsibility_When_Filter_Required_Based_ApplyToType_Value {
            get {
                return ResourceManager.GetString("Responsibility_When_Filter_Required_Based_ApplyToType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Responsibility When Filter value is required..
        /// </summary>
        public static string Responsibility_When_Filter_Value_Required {
            get {
                return ResourceManager.GetString("Responsibility_When_Filter_Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altering a model&apos;s parent could potentially have a significant impact on ownership throughout the system..
        /// </summary>
        public static string Taxonomy_ChangeParent_Warning {
            get {
                return ResourceManager.GetString("Taxonomy_ChangeParent_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string TaxonomyType {
            get {
                return ResourceManager.GetString("TaxonomyType", resourceCulture);
            }
        }
    }
}
