//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OthersMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OthersMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.web.App_GlobalResources.OthersMessages", typeof(OthersMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _pageNum parameter must be greater than 0..
        /// </summary>
        public static string _PageNumGT0 {
            get {
                return ResourceManager.GetString("_PageNumGT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _pageSize parameter has a maximum supported value of 200..
        /// </summary>
        public static string _PageSizeMax200 {
            get {
                return ResourceManager.GetString("_PageSizeMax200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All nodes within diagram must be linked..
        /// </summary>
        public static string AllNodeMustLink {
            get {
                return ResourceManager.GetString("AllNodeMustLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation identifier with value {0} does not correspond to a valid allocation..
        /// </summary>
        public static string AllocationIdentifierDoesnotValidAllocation {
            get {
                return ResourceManager.GetString("AllocationIdentifierDoesnotValidAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allocationUid {0} is not a correctly formatted identifier..
        /// </summary>
        public static string AllocationUidNotCorrectlyFormatted {
            get {
                return ResourceManager.GetString("AllocationUidNotCorrectlyFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset identifier with value {0} does not correspond to a valid asset..
        /// </summary>
        public static string AssetIdentifierDoesnotValidAsset {
            get {
                return ResourceManager.GetString("AssetIdentifierDoesnotValidAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset with uid specified does not exist..
        /// </summary>
        public static string AssetuidDoesnotExists {
            get {
                return ResourceManager.GetString("AssetuidDoesnotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset uid must be specified..
        /// </summary>
        public static string AssetUidMustSpecified {
            get {
                return ResourceManager.GetString("AssetUidMustSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assetUid {0} is not a correctly formatted identifier..
        /// </summary>
        public static string AssetuidNotCorrectlyFormatted {
            get {
                return ResourceManager.GetString("AssetuidNotCorrectlyFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request submitted.
        /// </summary>
        public static string BadRequestSubmitted {
            get {
                return ResourceManager.GetString("BadRequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Exception.
        /// </summary>
        public static string CriticalException {
            get {
                return ResourceManager.GetString("CriticalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomConstant {
            get {
                return ResourceManager.GetString("CustomConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying data source is not reachable..
        /// </summary>
        public static string DatasourceNotReachable {
            get {
                return ResourceManager.GetString("DatasourceNotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint not found..
        /// </summary>
        public static string EndPointNotFound {
            get {
                return ResourceManager.GetString("EndPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertionConsumerService =&gt; Failed to Verify Signature where an IDP-supplied CER file was stored.
        /// </summary>
        public static string FailedToVerifySignature {
            get {
                return ResourceManager.GetString("FailedToVerifySignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertionConsumerService =&gt; Failed to Verify Signature where no IDP-supplied CER file was stored.
        /// </summary>
        public static string FailedToVerifySignatureNoIDP {
            get {
                return ResourceManager.GetString("FailedToVerifySignatureNoIDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter expressions contained the following errors: {0}..
        /// </summary>
        public static string FilterExpressionErrors {
            get {
                return ResourceManager.GetString("FilterExpressionErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Govern environment you requested is currently inactive. Please contact Precisely support for additional information..
        /// </summary>
        public static string GovernEnvironmentInactive {
            get {
                return ResourceManager.GetString("GovernEnvironmentInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email does not look valid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have invalid fields in your _order query parameter..
        /// </summary>
        public static string InvalidField_OrderParameter {
            get {
                return ResourceManager.GetString("InvalidField_OrderParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have invalid fields in your filter query parameters: {0}..
        /// </summary>
        public static string InvalidFieldFilterParameter {
            get {
                return ResourceManager.GetString("InvalidFieldFilterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have invalid fields in your select query parameters: {0}..
        /// </summary>
        public static string InvalidFieldSelectQueryParameter {
            get {
                return ResourceManager.GetString("InvalidFieldSelectQueryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Relationship field encountered invalid or deleted relationship type encountered..
        /// </summary>
        public static string InvalidOrDeletedRelationshipType {
            get {
                return ResourceManager.GetString("InvalidOrDeletedRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link without from and to node detected..
        /// </summary>
        public static string LinkWithoutFromToDetected {
            get {
                return ResourceManager.GetString("LinkWithoutFromToDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model cannot be empty..
        /// </summary>
        public static string ModelNotEmpty {
            get {
                return ResourceManager.GetString("ModelNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the terms of use..
        /// </summary>
        public static string MustAcceptTermsOfUse {
            get {
                return ResourceManager.GetString("MustAcceptTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please try again or contact the administrator.
        /// </summary>
        public static string NeedAdministratorHelp {
            get {
                return ResourceManager.GetString("NeedAdministratorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assertions in response.
        /// </summary>
        public static string NoAssertionsInResponse {
            get {
                return ResourceManager.GetString("NoAssertionsInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email domain could be resolved..
        /// </summary>
        public static string NoEmailDomainResolved {
            get {
                return ResourceManager.GetString("NoEmailDomainResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to view score history on this asset..
        /// </summary>
        public static string NoPremissiontoviewScoreHistory {
            get {
                return ResourceManager.GetString("NoPremissiontoviewScoreHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registration found..
        /// </summary>
        public static string NoRegistrationFound {
            get {
                return ResourceManager.GetString("NoRegistrationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Relationship field encountered no relationship type to lookup found in definition..
        /// </summary>
        public static string NoRelationshipTypeFoundToLookup {
            get {
                return ResourceManager.GetString("NoRelationshipTypeFoundToLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource account could be located for you..
        /// </summary>
        public static string NoResourceAccount {
            get {
                return ResourceManager.GetString("NoResourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to edit this process diagram.
        /// </summary>
        public static string NotAuthorizedToEditDiagram {
            get {
                return ResourceManager.GetString("NotAuthorizedToEditDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No terms of use agreement found..
        /// </summary>
        public static string NoTermOfAgreementFound {
            get {
                return ResourceManager.GetString("NoTermOfAgreementFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password does not meet the following complexity requirements: {0}..
        /// </summary>
        public static string NotMeetPasswordRule {
            get {
                return ResourceManager.GetString("NotMeetPasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your organisation is not yet registered with the Market Business Glossary or your details are invalid. Please contact &lt;a href=&apos;mailto:datasupport@londonmarketgroup.co.uk&apos;&gt;datasupport@londonmarketgroup.co.uk&lt;/a&gt; for assistance..
        /// </summary>
        public static string OrganisationNotYetRegistered {
            get {
                return ResourceManager.GetString("OrganisationNotYetRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email shortly to confirm ownership of this email address, and to continue registration..
        /// </summary>
        public static string OwnershipConfirmationMail {
            get {
                return ResourceManager.GetString("OwnershipConfirmationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URI must not exceed 16,000 characters..
        /// </summary>
        public static string RequestURINotExceed16Kchar {
            get {
                return ResourceManager.GetString("RequestURINotExceed16Kchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource account not yet allocated to this company..
        /// </summary>
        public static string ResoourceAccountNotAllocatedToCompany {
            get {
                return ResourceManager.GetString("ResoourceAccountNotAllocatedToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource account not yet set as an organizational resource..
        /// </summary>
        public static string ResourceNotSetOrgResource {
            get {
                return ResourceManager.GetString("ResourceNotSetOrgResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not available for this user..
        /// </summary>
        public static string ResourceNotThisUser {
            get {
                return ResourceManager.GetString("ResourceNotThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search filters are invalid in your filter query parameter: last_modified..
        /// </summary>
        public static string SearchFilterInvalid {
            get {
                return ResourceManager.GetString("SearchFilterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server error occurred. Please try your request again at a later time.
        /// </summary>
        public static string ServerErrorOccurred {
            get {
                return ResourceManager.GetString("ServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using copy/replace option with sourceAssetUid model must be empty..
        /// </summary>
        public static string SourceAssetUidModelNotEmpty {
            get {
                return ResourceManager.GetString("SourceAssetUidModelNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target asset cannot be same..
        /// </summary>
        public static string SourceTargetNotSame {
            get {
                return ResourceManager.GetString("SourceTargetNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target asset types must be same..
        /// </summary>
        public static string SourceTargetTypeMustSame {
            get {
                return ResourceManager.GetString("SourceTargetTypeMustSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sourceAssetUid is invalid or asset does not exist..
        /// </summary>
        public static string SourceUidNotExists {
            get {
                return ResourceManager.GetString("SourceUidNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
