//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.web.App_GlobalResources.PageInfo", typeof(PageInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create various types of measurements on items throughout the system, including analytics that factor into scores..
        /// </summary>
        public static string Administration_Analytics_Description {
            get {
                return ResourceManager.GetString("Administration_Analytics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytic Types.
        /// </summary>
        public static string Administration_Analytics_Title {
            get {
                return ResourceManager.GetString("Administration_Analytics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will find all artifact types and custom fields associated with them.
        /// </summary>
        public static string Administration_Artifact_Description {
            get {
                return ResourceManager.GetString("Administration_Artifact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Types.
        /// </summary>
        public static string Administration_Artifact_Title {
            get {
                return ResourceManager.GetString("Administration_Artifact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All type of reference data lists for the organization are defined here. To add a new type of list, go under Actions and select Add type..
        /// </summary>
        public static string Administration_DomainType_Description {
            get {
                return ResourceManager.GetString("Administration_DomainType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Types.
        /// </summary>
        public static string Administration_DomainType_Title {
            get {
                return ResourceManager.GetString("Administration_DomainType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will find all metadata that can be assigned to various objects and relationships.
        /// </summary>
        public static string Administration_Fact_Description {
            get {
                return ResourceManager.GetString("Administration_Fact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute  Groups.
        /// </summary>
        public static string Administration_Fact_Title {
            get {
                return ResourceManager.GetString("Administration_Fact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will find all global field types used by items like artifacts, information models, and resources..
        /// </summary>
        public static string Administration_Fields_Description {
            get {
                return ResourceManager.GetString("Administration_Fields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Types.
        /// </summary>
        public static string Administration_Fields_Title {
            get {
                return ResourceManager.GetString("Administration_Fields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will find all Fusion sources and synchronization settings.
        /// </summary>
        public static string Administration_Fusion_Description {
            get {
                return ResourceManager.GetString("Administration_Fusion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Types.
        /// </summary>
        public static string Administration_Fusion_Title {
            get {
                return ResourceManager.GetString("Administration_Fusion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign which objects can be owned, and whether groups, users or both may own them.  You may also define application and licensing source types..
        /// </summary>
        public static string Administration_Governance_Description {
            get {
                return ResourceManager.GetString("Administration_Governance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibility Types.
        /// </summary>
        public static string Administration_Governance_Title {
            get {
                return ResourceManager.GetString("Administration_Governance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will find groups and membership.
        /// </summary>
        public static string Administration_Group_Description {
            get {
                return ResourceManager.GetString("Administration_Group_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Administration_Group_Title {
            get {
                return ResourceManager.GetString("Administration_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the possibility of establishing relationships between different objects within the system..
        /// </summary>
        public static string Administration_Intersect_Description {
            get {
                return ResourceManager.GetString("Administration_Intersect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Types.
        /// </summary>
        public static string Administration_Intersect_Title {
            get {
                return ResourceManager.GetString("Administration_Intersect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will find all general lookups used.
        /// </summary>
        public static string Administration_Lookup_Description {
            get {
                return ResourceManager.GetString("Administration_Lookup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Types.
        /// </summary>
        public static string Administration_Lookup_Title {
            get {
                return ResourceManager.GetString("Administration_Lookup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize various sets of policies across your organization..
        /// </summary>
        public static string Administration_PolicyType_Description {
            get {
                return ResourceManager.GetString("Administration_PolicyType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Types.
        /// </summary>
        public static string Administration_PolicyType_Title {
            get {
                return ResourceManager.GetString("Administration_PolicyType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your dashboard overlays and tiles..
        /// </summary>
        public static string Administration_Reporting_Description {
            get {
                return ResourceManager.GetString("Administration_Reporting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string Administration_Reporting_Title {
            get {
                return ResourceManager.GetString("Administration_Reporting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will find all current resources.
        /// </summary>
        public static string Administration_Resource_Description {
            get {
                return ResourceManager.GetString("Administration_Resource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Administration_Resource_Title {
            get {
                return ResourceManager.GetString("Administration_Resource_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the available lists of responses that can be associated with different survey questions..
        /// </summary>
        public static string Administration_ResponseType_Description {
            get {
                return ResourceManager.GetString("Administration_ResponseType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Types.
        /// </summary>
        public static string Administration_ResponseType_Title {
            get {
                return ResourceManager.GetString("Administration_ResponseType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can configure the properties available to rules, including what dimensions are defined..
        /// </summary>
        public static string Administration_RuleType_Description {
            get {
                return ResourceManager.GetString("Administration_RuleType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Types.
        /// </summary>
        public static string Administration_RuleType_Title {
            get {
                return ResourceManager.GetString("Administration_RuleType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage system-wide settings for your environment..
        /// </summary>
        public static string Administration_Settings_Description {
            get {
                return ResourceManager.GetString("Administration_Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Administration_Settings_Title {
            get {
                return ResourceManager.GetString("Administration_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage surveys throughout the system, targeting them to different types of objects..
        /// </summary>
        public static string Administration_SurveyType_Description {
            get {
                return ResourceManager.GetString("Administration_SurveyType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Types.
        /// </summary>
        public static string Administration_SurveyType_Title {
            get {
                return ResourceManager.GetString("Administration_SurveyType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the variety of synonym types contained within your firm..
        /// </summary>
        public static string Administration_SynonymType_Description {
            get {
                return ResourceManager.GetString("Administration_SynonymType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym Types.
        /// </summary>
        public static string Administration_SynonymType_Title {
            get {
                return ResourceManager.GetString("Administration_SynonymType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All top-level information models for the organization are defined here. To add a new top-level model, go under Actions and select Add Type..
        /// </summary>
        public static string Administration_TaxonomyType_Description {
            get {
                return ResourceManager.GetString("Administration_TaxonomyType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Types.
        /// </summary>
        public static string Administration_TaxonomyType_Title {
            get {
                return ResourceManager.GetString("Administration_TaxonomyType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All email and tooltip templates for notifications..
        /// </summary>
        public static string Administration_Template_Description {
            get {
                return ResourceManager.GetString("Administration_Template_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Administration_Template_Title {
            get {
                return ResourceManager.GetString("Administration_Template_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all workflow settings for types within your environment..
        /// </summary>
        public static string Administration_Workflow_Description {
            get {
                return ResourceManager.GetString("Administration_Workflow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Administration_Workflow_Title {
            get {
                return ResourceManager.GetString("Administration_Workflow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find all your data and sourcing information.
        /// </summary>
        public static string Artifacts_Description {
            get {
                return ResourceManager.GetString("Artifacts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts.
        /// </summary>
        public static string Artifacts_Title {
            get {
                return ResourceManager.GetString("Artifacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A place to share and report issues to the greater Data360 audience..
        /// </summary>
        public static string Community_Home_Description {
            get {
                return ResourceManager.GetString("Community_Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Community_Home_Title {
            get {
                return ResourceManager.GetString("Community_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can administer all reference data groups, lists, and values from this screen..
        /// </summary>
        public static string Domains_Description {
            get {
                return ResourceManager.GetString("Domains_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Domains_Title {
            get {
                return ResourceManager.GetString("Domains_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to fulfill your request!.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a group below.  See the activity happening on publisc groups.  If interested, feel free to join..
        /// </summary>
        public static string Groups_Description {
            get {
                return ResourceManager.GetString("Groups_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups_Title {
            get {
                return ResourceManager.GetString("Groups_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find all your data and sourcing information.
        /// </summary>
        public static string Home_Description {
            get {
                return ResourceManager.GetString("Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can bulk load almost any piece of content contained within the Data360 platform..
        /// </summary>
        public static string Load_Description {
            get {
                return ResourceManager.GetString("Load_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Loading.
        /// </summary>
        public static string Load_Title {
            get {
                return ResourceManager.GetString("Load_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login.
        /// </summary>
        public static string Login_Description {
            get {
                return ResourceManager.GetString("Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all your policies and rules.  Each rule can maintain a list of fields.  These fields will define what an event looks like that the selected rule..
        /// </summary>
        public static string Monitor_Description {
            get {
                return ResourceManager.GetString("Monitor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Monitor_Title {
            get {
                return ResourceManager.GetString("Monitor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find people and groups and see the most active users..
        /// </summary>
        public static string People_Description {
            get {
                return ResourceManager.GetString("People_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People_Title {
            get {
                return ResourceManager.GetString("People_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Policies_Description {
            get {
                return ResourceManager.GetString("Policies_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies_Title {
            get {
                return ResourceManager.GetString("Policies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Rules_Description {
            get {
                return ResourceManager.GetString("Rules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules_Title {
            get {
                return ResourceManager.GetString("Rules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you looking for the info you need?  Find it here....
        /// </summary>
        public static string Search_Description {
            get {
                return ResourceManager.GetString("Search_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an available model below on the left-hand side.  If no models exist, create one using the menu to the left..
        /// </summary>
        public static string Taxonomies_Description {
            get {
                return ResourceManager.GetString("Taxonomies_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Taxonomies_Title {
            get {
                return ResourceManager.GetString("Taxonomies_Title", resourceCulture);
            }
        }
    }
}
