//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScoreApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScoreApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.web.App_GlobalResources.ScoreApiMessages", typeof(ScoreApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation successfully deleted!.
        /// </summary>
        public static string AllocationDeleteMessage {
            get {
                return ResourceManager.GetString("AllocationDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation with uid {0} does not exist..
        /// </summary>
        public static string AllocationNotExists {
            get {
                return ResourceManager.GetString("AllocationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate measureUid specified in the payload..
        /// </summary>
        public static string DuplicateMesaureUid {
            get {
                return ResourceManager.GetString("DuplicateMesaureUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to effectiveDate must not be greater than today&apos;s date (in UTC)..
        /// </summary>
        public static string EffectiveDateNotGTToday {
            get {
                return ResourceManager.GetString("EffectiveDateNotGTToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving data quality evidence for score result.
        /// </summary>
        public static string ErrorGetDataQualityScore {
            get {
                return ResourceManager.GetString("ErrorGetDataQualityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving unallocated asset types.
        /// </summary>
        public static string ErrorUnallocatedAssetType {
            get {
                return ResourceManager.GetString("ErrorUnallocatedAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower threshold must be set..
        /// </summary>
        public static string LowerThreshold {
            get {
                return ResourceManager.GetString("LowerThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold values must be between 0 and 100..
        /// </summary>
        public static string RangeLimitThreshold {
            get {
                return ResourceManager.GetString("RangeLimitThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately you are unable to delete a score with measures defined..
        /// </summary>
        public static string RestrictDeleteScore {
            get {
                return ResourceManager.GetString("RestrictDeleteScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to read the asset that is related to this score item..
        /// </summary>
        public static string RestrictReadAssetScoreITem {
            get {
                return ResourceManager.GetString("RestrictReadAssetScoreITem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to retrieve the measure version history for this measure..
        /// </summary>
        public static string RestrictReadVersionHistory {
            get {
                return ResourceManager.GetString("RestrictReadVersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to recalculate score items associated with this measure..
        /// </summary>
        public static string RestrictRecalculateScore {
            get {
                return ResourceManager.GetString("RestrictRecalculateScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately you are unable to update a scores Asset Type, Score Type or Externally calculated flag if score has active measures defined..
        /// </summary>
        public static string RestrictUpdateScoreField {
            get {
                return ResourceManager.GetString("RestrictUpdateScoreField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score definition with {0} could not be found..
        /// </summary>
        public static string ScoreDefinitionNotFound {
            get {
                return ResourceManager.GetString("ScoreDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Allocation already exists..
        /// </summary>
        public static string ScoreExists {
            get {
                return ResourceManager.GetString("ScoreExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score item with Uid {0} is not a data quality measure..
        /// </summary>
        public static string ScoreNotDataQualityMeasure {
            get {
                return ResourceManager.GetString("ScoreNotDataQualityMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score item with Uid {o} does not exist..
        /// </summary>
        public static string ScoreNotExists {
            get {
                return ResourceManager.GetString("ScoreNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score definition with {0} is not externally calculated..
        /// </summary>
        public static string ScoreNotExternalCalculation {
            get {
                return ResourceManager.GetString("ScoreNotExternalCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower threshold must be smaller than Upper threshold..
        /// </summary>
        public static string UpperGtLower {
            get {
                return ResourceManager.GetString("UpperGtLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper threshold must be set..
        /// </summary>
        public static string UpperThreshold {
            get {
                return ResourceManager.GetString("UpperThreshold", resourceCulture);
            }
        }
    }
}
