//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkflowApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkflowApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.web.App_GlobalResources.WorkflowApiMessages", typeof(WorkflowApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form settings is missing or invalid.
        /// </summary>
        public static string InvalidFormSetting {
            get {
                return ResourceManager.GetString("InvalidFormSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID MODEL NO FIELDS PASSED.
        /// </summary>
        public static string InvalidModelNoFieldPassed {
            get {
                return ResourceManager.GetString("InvalidModelNoFieldPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order passed in the request. Valid values are: StartedOn and CompletedOn.
        /// </summary>
        public static string InvalidOrderParameterPassed {
            get {
                return ResourceManager.GetString("InvalidOrderParameterPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order passed in the request. Valid values are: VersionNumber, State, CreatedOn, and UpdatedOn.
        /// </summary>
        public static string InvalidParameterWorkflowVersion {
            get {
                return ResourceManager.GetString("InvalidParameterWorkflowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource id.
        /// </summary>
        public static string InvalidResourceID {
            get {
                return ResourceManager.GetString("InvalidResourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID WORKFLOW ITEM ID,  CANNOT FIND WORKFLOWITEMSTEP WITH SPECIFIED ID..
        /// </summary>
        public static string InvalidSpecificID {
            get {
                return ResourceManager.GetString("InvalidSpecificID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to retrieve this workflow version is invalid, possibly due to an incorrectly formatted identifier ActionTypeUid/AssetTypeUid/RelationshipTypeUid.
        /// </summary>
        public static string InvalidTypeWorkflowVersionRequest {
            get {
                return ResourceManager.GetString("InvalidTypeWorkflowVersionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to retrieve this workflow version is invalid, possibly due to an incorrectly formatted identifier ActionTypeUid/AssetTypeUid/RelationshipTypeUid/WorkflowTypeUid.
        /// </summary>
        public static string InvalidTypeWorkflowVersionRequestIncWF {
            get {
                return ResourceManager.GetString("InvalidTypeWorkflowVersionRequestIncWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to retrieve this workflow version is invalid, possibly due to an incorrectly formatted identifier ActionUid / AssetUid / RelationshipUid / WorkflowTypeUid / WorkflowVerionUid.
        /// </summary>
        public static string InvalidUidWorkflowVersionRequest {
            get {
                return ResourceManager.GetString("InvalidUidWorkflowVersionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Workflow item id..
        /// </summary>
        public static string InvalidWorkflowID {
            get {
                return ResourceManager.GetString("InvalidWorkflowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow registration is missing or invalid.
        /// </summary>
        public static string InvalidWorkflowRegistration {
            get {
                return ResourceManager.GetString("InvalidWorkflowRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Workflow item step id..
        /// </summary>
        public static string InvalidWorkflowStepID {
            get {
                return ResourceManager.GetString("InvalidWorkflowStepID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANNOT FIND THE ITEM STEP FOR THE SPECIFIED PARAMETERS.
        /// </summary>
        public static string ItemStepNotFound {
            get {
                return ResourceManager.GetString("ItemStepNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find item step.
        /// </summary>
        public static string ItemStepUnableFound {
            get {
                return ResourceManager.GetString("ItemStepUnableFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one uid is passed in the request, either  ActionTypeUid OR AssetTypeUid OR RelationshipTypeUid.
        /// </summary>
        public static string MoreThanOneTypeUidPassed {
            get {
                return ResourceManager.GetString("MoreThanOneTypeUidPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one uid is passed in the request , either  ActionTypeUid OR AssetTypeUid OR RelationshipTypeUid or WorkflowTypeUid.
        /// </summary>
        public static string MoreThanOneTypeUidPassedInclWorkflow {
            get {
                return ResourceManager.GetString("MoreThanOneTypeUidPassedInclWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one uid is passed in the request, either ActionUid OR AssetUid OR RelationshipUid.
        /// </summary>
        public static string MoreThanOneUidPassed {
            get {
                return ResourceManager.GetString("MoreThanOneUidPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTIPLE VERION STEPS SPECIFIED.
        /// </summary>
        public static string MultiVersionFound {
            get {
                return ResourceManager.GetString("MultiVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to bulk reassign..
        /// </summary>
        public static string NoPermissionBulkReassign {
            get {
                return ResourceManager.GetString("NoPermissionBulkReassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO VALID ITEM STEPS FOUND.
        /// </summary>
        public static string NoValidItemStep {
            get {
                return ResourceManager.GetString("NoValidItemStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;RELATIONSHIP INPUT CANNOT FIND THE SPECIFIED INTERSECT TYPE.
        /// </summary>
        public static string RelationNotFoundIntersectType {
            get {
                return ResourceManager.GetString("RelationNotFoundIntersectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATIONSHIP INPUT CANNOT IDENTIFY ISSUE OBJECT.
        /// </summary>
        public static string RelationNotFoundIssueObject {
            get {
                return ResourceManager.GetString("RelationNotFoundIssueObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATIONSHIP INPUT CANNOT IDENTIFY WORKFLOW EVENT REGISTRATION.
        /// </summary>
        public static string RelationNotFoundRegistration {
            get {
                return ResourceManager.GetString("RelationNotFoundRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATIONSHIP INPUT HAS AN INVALID INTERSECTTYPE ID VALUE.
        /// </summary>
        public static string RelatioshipInvalid {
            get {
                return ResourceManager.GetString("RelatioshipInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step not found.
        /// </summary>
        public static string StepNotFound {
            get {
                return ResourceManager.GetString("StepNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow with specified version step id not found.
        /// </summary>
        public static string VersionStepIDNotFound {
            get {
                return ResourceManager.GetString("VersionStepIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID WORKFLOW FORM DEFINITION,  FORM XML IS NULL..
        /// </summary>
        public static string WofkFlowXMLNull {
            get {
                return ResourceManager.GetString("WofkFlowXMLNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow type ID {0} is already deleted.
        /// </summary>
        public static string WorkflowIDAlreadyDeleted {
            get {
                return ResourceManager.GetString("WorkflowIDAlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the specified workflow instance..
        /// </summary>
        public static string WorkflowInstanceNotFound {
            get {
                return ResourceManager.GetString("WorkflowInstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow item has been deleted..
        /// </summary>
        public static string WorkflowItemDeleted {
            get {
                return ResourceManager.GetString("WorkflowItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow forms reassigned successfully.
        /// </summary>
        public static string WorkflowReassignSuccess {
            get {
                return ResourceManager.GetString("WorkflowReassignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow type id {0} could not be found.
        /// </summary>
        public static string WorkflowtypeidNotFound {
            get {
                return ResourceManager.GetString("WorkflowtypeidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow type Uid {0} could not be found.
        /// </summary>
        public static string WorkflowtypeUIDNotFound {
            get {
                return ResourceManager.GetString("WorkflowtypeUIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Uid {0} could not be found..
        /// </summary>
        public static string WorkflowUIDNotFound {
            get {
                return ResourceManager.GetString("WorkflowUIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Version with Uid {0} could not be found..
        /// </summary>
        public static string WorkflowVersionUIDNotFound {
            get {
                return ResourceManager.GetString("WorkflowVersionUIDNotFound", resourceCulture);
            }
        }
    }
}
