export class FollowDetail {
    ResourceID: number;
    ObjectID: number;
    ObjectType: string;
    FollowID: number;
    ID: number;
    Name: string;
    TextPath: string;
    Description: string;
    ParentID: number;
    ParentType: string;
    Url: string;
    TypeID: number;
    Type: string;
    TypeName: string;
    IconBackColor: string;
    IconForeColor: string;
    IconText: string;
    OpenEventCount: number;
    CurrentScore: number;
    FollowerEmail: string;
    FollowerFirstName: string;
    FollowerLastName: string;
    FollowerName: string;
    FollowerObjectType: string;
    FollowerObjectID: number;
    FollowerUrl: string;
    HardFollow: boolean;
}