<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net48</TargetFrameworks>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="SpreadsheetLight" Version="3.5.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\d360.core\d360.core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="resources\Xref.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Xref.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="resources\Xref.nl-NL.resx">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="resources\Xref.es-ES.resx">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="resources\Xref.fr-FR.resx">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="resources\Xref.it-IT.resx">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="resources\Xref.de-DE.resx">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="resources\Xref.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Xref.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
