//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetTypeErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetTypeErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.AssetTypeErrors", typeof(AssetTypeErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _parentUid with value {0} does not correspond to a valid asset!.
        /// </summary>
        public static string _parentuidNotValidAsset {
            get {
                return ResourceManager.GetString("_parentuidNotValidAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _parentUid parameter must be a valid Guid, be set to null, or not be present!.
        /// </summary>
        public static string _parentUidNotValidUid {
            get {
                return ResourceManager.GetString("_parentUidNotValidUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets already exist with assigned parents. You may not change the parent of this asset type..
        /// </summary>
        public static string AssetsWithAssignedParents {
            get {
                return ResourceManager.GetString("AssetsWithAssignedParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type Already Exists.
        /// </summary>
        public static string AssetTypeExistsTitle {
            get {
                return ResourceManager.GetString("AssetTypeExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asset type with the specified Uid already exists..
        /// </summary>
        public static string AssetTypeWithUidExists {
            get {
                return ResourceManager.GetString("AssetTypeWithUidExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Display Parent can be set only asset types that are a Business or Technical class and are the child of another asset type..
        /// </summary>
        public static string AutoDisplayParentRestriction {
            get {
                return ResourceManager.GetString("AutoDisplayParentRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Format contains invalid field references..
        /// </summary>
        public static string BadDisplayFormat {
            get {
                return ResourceManager.GetString("BadDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Edit Parent can be set only asset types that are a Business or Technical class and are the child of another asset type..
        /// </summary>
        public static string CanEditParentClassRestriction {
            get {
                return ResourceManager.GetString("CanEditParentClassRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Edit Parent can be set only on children asset types..
        /// </summary>
        public static string CanEditParentRestriction {
            get {
                return ResourceManager.GetString("CanEditParentRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your request and try again..
        /// </summary>
        public static string CheckRequest {
            get {
                return ResourceManager.GetString("CheckRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Found.
        /// </summary>
        public static string DuplicateFound {
            get {
                return ResourceManager.GetString("DuplicateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate items found in request.
        /// </summary>
        public static string DuplicateItem {
            get {
                return ResourceManager.GetString("DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Name Found.
        /// </summary>
        public static string DuplicateNameFound {
            get {
                return ResourceManager.GetString("DuplicateNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is taken. Please try another name..
        /// </summary>
        public static string ErrorNameTaken {
            get {
                return ResourceManager.GetString("ErrorNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution unique identifier not found..
        /// </summary>
        public static string ExecutionUIDNotFound {
            get {
                return ResourceManager.GetString("ExecutionUIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an organization type with that name..
        /// </summary>
        public static string ExistingOrganizationType {
            get {
                return ResourceManager.GetString("ExistingOrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be empty..
        /// </summary>
        public static string FieldIsEmpty {
            get {
                return ResourceManager.GetString("FieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        public static string FieldIsInvalid {
            get {
                return ResourceManager.GetString("FieldIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid value..
        /// </summary>
        public static string FieldProvideCorrectValue {
            get {
                return ResourceManager.GetString("FieldProvideCorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add Asset Type of class Diagram. Governance Role Reference UID is not set..
        /// </summary>
        public static string GovernanceRoleNotSet {
            get {
                return ResourceManager.GetString("GovernanceRoleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v2/membership/groups.
        /// </summary>
        public static string GroupEndPoint {
            get {
                return ResourceManager.GetString("GroupEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not provided a proper predicate based on its asset type class..
        /// </summary>
        public static string ImproperPredicate {
            get {
                return ResourceManager.GetString("ImproperPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assetType specified.
        /// </summary>
        public static string InvalidAssetType {
            get {
                return ResourceManager.GetString("InvalidAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid asset Uid in parameters!.
        /// </summary>
        public static string InvalidAssetUid {
            get {
                return ResourceManager.GetString("InvalidAssetUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} provided..
        /// </summary>
        public static string InvalidClass {
            get {
                return ResourceManager.GetString("InvalidClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order direction passed in the request..
        /// </summary>
        public static string InvalidDirection {
            get {
                return ResourceManager.GetString("InvalidDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayFormat provided is invalid..
        /// </summary>
        public static string InvalidDisplayFormat {
            get {
                return ResourceManager.GetString("InvalidDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Field Entry.
        /// </summary>
        public static string InvalidFieldEntry {
            get {
                return ResourceManager.GetString("InvalidFieldEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be updated because it is {1}..
        /// </summary>
        public static string InvalidFieldMessage {
            get {
                return ResourceManager.GetString("InvalidFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Maximum Depth.
        /// </summary>
        public static string InvalidMaximumDepthTitle {
            get {
                return ResourceManager.GetString("InvalidMaximumDepthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum depth. Model level specified must be a value between 1 and 10..
        /// </summary>
        public static string InvalidModelDepth {
            get {
                return ResourceManager.GetString("InvalidModelDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order by passed in the request..
        /// </summary>
        public static string InvalidOrderPassed {
            get {
                return ResourceManager.GetString("InvalidOrderPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Organization provided..
        /// </summary>
        public static string InvalidOrganization {
            get {
                return ResourceManager.GetString("InvalidOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Owner Uid in parameters!.
        /// </summary>
        public static string InvalidOwnerUid {
            get {
                return ResourceManager.GetString("InvalidOwnerUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} provided.
        /// </summary>
        public static string InvalidParameterProvided {
            get {
                return ResourceManager.GetString("InvalidParameterProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid ParentUid for the Class..
        /// </summary>
        public static string InvalidParentForClass {
            get {
                return ResourceManager.GetString("InvalidParentForClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parent Selected.
        /// </summary>
        public static string InvalidParentSelected {
            get {
                return ResourceManager.GetString("InvalidParentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ParentUid provided..
        /// </summary>
        public static string InvalidParentUid {
            get {
                return ResourceManager.GetString("InvalidParentUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum depth. Policy level specified must be a value between 1 and 10..
        /// </summary>
        public static string InvalidPolicyDepth {
            get {
                return ResourceManager.GetString("InvalidPolicyDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or deleted relationship type encountered on Relationship field with friendly name &quot;{FriendlyName}&quot;..
        /// </summary>
        public static string InvalidRelationshipFieldType {
            get {
                return ResourceManager.GetString("InvalidRelationshipFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string InvalidRequestHttpErrorTitle {
            get {
                return ResourceManager.GetString("InvalidRequestHttpErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Icon Style provided..
        /// </summary>
        public static string InvalidStyle {
            get {
                return ResourceManager.GetString("InvalidStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [autoDisplayDescription].
        /// </summary>
        public static string InvalidValueautoDisplayDescription {
            get {
                return ResourceManager.GetString("InvalidValueautoDisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [autoDisplayParent].
        /// </summary>
        public static string InvalidValueAutoDisplayParent {
            get {
                return ResourceManager.GetString("InvalidValueAutoDisplayParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [useastransformation].
        /// </summary>
        public static string InvalidValueForuseastransformation {
            get {
                return ResourceManager.GetString("InvalidValueForuseastransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [hierarchical].
        /// </summary>
        public static string InvalidValueHierachical {
            get {
                return ResourceManager.GetString("InvalidValueHierachical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [includedashboardflag].
        /// </summary>
        public static string InvalidValueincludedashboardflag {
            get {
                return ResourceManager.GetString("InvalidValueincludedashboardflag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [includeLevels].
        /// </summary>
        public static string InvalidValueincludeLevels {
            get {
                return ResourceManager.GetString("InvalidValueincludeLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [obj].
        /// </summary>
        public static string InvalidValueObj {
            get {
                return ResourceManager.GetString("InvalidValueObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [objID].
        /// </summary>
        public static string InvalidValueObjID {
            get {
                return ResourceManager.GetString("InvalidValueObjID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [ReturnCount].
        /// </summary>
        public static string InvalidValueReturnCount {
            get {
                return ResourceManager.GetString("InvalidValueReturnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value {0} in _includeFields parameter, field with this name not found..
        /// </summary>
        public static string InvalueValue_includeFields {
            get {
                return ResourceManager.GetString("InvalueValue_includeFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be added or updated because an existing item already found..
        /// </summary>
        public static string ItemConflicit {
            get {
                return ResourceManager.GetString("ItemConflicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be found..
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Style ForeColor and BackColor cannot be the same value..
        /// </summary>
        public static string MatchingIconStyle {
            get {
                return ResourceManager.GetString("MatchingIconStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of asset types for this method is 1..
        /// </summary>
        public static string MaxNumberAllowedAssetType {
            get {
                return ResourceManager.GetString("MaxNumberAllowedAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowObjectType is required field for Asset Type with class Diagram..
        /// </summary>
        public static string MissingFlowObjectType {
            get {
                return ResourceManager.GetString("MissingFlowObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing required properties for the request to proceed..
        /// </summary>
        public static string MissingPropertyMessage {
            get {
                return ResourceManager.GetString("MissingPropertyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Missing Properties.
        /// </summary>
        public static string MissingPropertyTitle {
            get {
                return ResourceManager.GetString("MissingPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be added or updated because an item with the same name already exists..
        /// </summary>
        public static string NameConflicit {
            get {
                return ResourceManager.GetString("NameConflicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character(-s) provided in the asset type name. Please fix content of asset type name field..
        /// </summary>
        public static string NameContainInvalidCharacters {
            get {
                return ResourceManager.GetString("NameContainInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No form data present to created {0}..
        /// </summary>
        public static string NoFormDataMessage {
            get {
                return ResourceManager.GetString("NoFormDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Form Data.
        /// </summary>
        public static string NoFormDataTitle {
            get {
                return ResourceManager.GetString("NoFormDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type not found based on Class provided..
        /// </summary>
        public static string NotFoundBasedOnClass {
            get {
                return ResourceManager.GetString("NotFoundBasedOnClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type not found based on Uid provided..
        /// </summary>
        public static string NotFoundBasedOnUid {
            get {
                return ResourceManager.GetString("NotFoundBasedOnUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type not found..
        /// </summary>
        public static string NotFoundGeneric {
            get {
                return ResourceManager.GetString("NotFoundGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are existing parent/child relationships for assets of this type. You may not alter the parent type until these relationships are removed..
        /// </summary>
        public static string ParentChildRelationExists {
            get {
                return ResourceManager.GetString("ParentChildRelationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate.
        /// </summary>
        public static string PredicateHttpErrorTitle {
            get {
                return ResourceManager.GetString("PredicateHttpErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship OR Relationship type exists with this the asset type or any asset under this type participates in the relationship..
        /// </summary>
        public static string RelationshipExistsForAssetType {
            get {
                return ResourceManager.GetString("RelationshipExistsForAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores Message Already Being Processed.
        /// </summary>
        public static string ScoreAlreadyProcessed {
            get {
                return ResourceManager.GetString("ScoreAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Organization.
        /// </summary>
        public static string TitleWrongOrganization {
            get {
                return ResourceManager.GetString("TitleWrongOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use As Transformation can be set only asset types that are a Business or Technical class..
        /// </summary>
        public static string TransformationClassRestriction {
            get {
                return ResourceManager.GetString("TransformationClassRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of asset types exceeds the Transformation limit..
        /// </summary>
        public static string TransformationLimitExceeded {
            get {
                return ResourceManager.GetString("TransformationLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found..
        /// </summary>
        public static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse value of _includeFields.
        /// </summary>
        public static string UnableParse_IncludeFields {
            get {
                return ResourceManager.GetString("UnableParse_IncludeFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occured. Please try your request again..
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported asset class..
        /// </summary>
        public static string UnsupportedAssetClass {
            get {
                return ResourceManager.GetString("UnsupportedAssetClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowObjectType is not support for class {0}..
        /// </summary>
        public static string UnsupportedFlowObjectType {
            get {
                return ResourceManager.GetString("UnsupportedFlowObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseAsAdmin parameter can be used only with _assetUid specified!.
        /// </summary>
        public static string UseAsAdminUseWithAssetUid {
            get {
                return ResourceManager.GetString("UseAsAdminUseWithAssetUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v2/membership/users.
        /// </summary>
        public static string UserEndPoint {
            get {
                return ResourceManager.GetString("UserEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong {0}.
        /// </summary>
        public static string WrongClass {
            get {
                return ResourceManager.GetString("WrongClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Name.
        /// </summary>
        public static string WrongNameHttpErrorTitle {
            get {
                return ResourceManager.GetString("WrongNameHttpErrorTitle", resourceCulture);
            }
        }
    }
}
