//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetTypeErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetTypeErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.AssetTypeErrors", typeof(AssetTypeErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets already exist with assigned parents. You may not change the parent of this asset type..
        /// </summary>
        public static string AssetsWithAssignedParents {
            get {
                return ResourceManager.GetString("AssetsWithAssignedParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type Already Exists.
        /// </summary>
        public static string AssetTypeExistsTitle {
            get {
                return ResourceManager.GetString("AssetTypeExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asset type with the specified Uid already exists..
        /// </summary>
        public static string AssetTypeWithUidExists {
            get {
                return ResourceManager.GetString("AssetTypeWithUidExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Display Parent can be set only asset types that are a Business or Technical class and are the child of another asset type..
        /// </summary>
        public static string AutoDisplayParentRestriction {
            get {
                return ResourceManager.GetString("AutoDisplayParentRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Format contains invalid field references..
        /// </summary>
        public static string BadDisplayFormat {
            get {
                return ResourceManager.GetString("BadDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Edit Parent can be set only asset types that are a Business or Technical class and are the child of another asset type..
        /// </summary>
        public static string CanEditParentClassRestriction {
            get {
                return ResourceManager.GetString("CanEditParentClassRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Edit Parent can be set only on children asset types..
        /// </summary>
        public static string CanEditParentRestriction {
            get {
                return ResourceManager.GetString("CanEditParentRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your request and try again..
        /// </summary>
        public static string CheckRequest {
            get {
                return ResourceManager.GetString("CheckRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is taken. Please try another name..
        /// </summary>
        public static string ErrorNameTaken {
            get {
                return ResourceManager.GetString("ErrorNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an organization type with that name..
        /// </summary>
        public static string ExistingOrganizationType {
            get {
                return ResourceManager.GetString("ExistingOrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add Asset Type of class Diagram. Governance Role Reference UID is not set..
        /// </summary>
        public static string GovernanceRoleNotSet {
            get {
                return ResourceManager.GetString("GovernanceRoleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v2/membership/groups.
        /// </summary>
        public static string GroupEndPoint {
            get {
                return ResourceManager.GetString("GroupEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not provided a proper predicate based on its asset type class..
        /// </summary>
        public static string ImproperPredicate {
            get {
                return ResourceManager.GetString("ImproperPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayFormat provided is invalid..
        /// </summary>
        public static string InvalidDisplayFormat {
            get {
                return ResourceManager.GetString("InvalidDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum depth. Model level specified must be a value between 1 and 10..
        /// </summary>
        public static string InvalidModelDepth {
            get {
                return ResourceManager.GetString("InvalidModelDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid Name provided..
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} provided.
        /// </summary>
        public static string InvalidParameterProvided {
            get {
                return ResourceManager.GetString("InvalidParameterProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid ParentUid for the Class..
        /// </summary>
        public static string InvalidParentForClass {
            get {
                return ResourceManager.GetString("InvalidParentForClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ParentUid provided..
        /// </summary>
        public static string InvalidParentUid {
            get {
                return ResourceManager.GetString("InvalidParentUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum depth. Policy level specified must be a value between 1 and 10..
        /// </summary>
        public static string InvalidPolicyDepth {
            get {
                return ResourceManager.GetString("InvalidPolicyDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or deleted relationship type encountered on Relationship field with friendly name &quot;{FriendlyName}&quot;..
        /// </summary>
        public static string InvalidRelationshipFieldType {
            get {
                return ResourceManager.GetString("InvalidRelationshipFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string InvalidRequestHttpErrorTitle {
            get {
                return ResourceManager.GetString("InvalidRequestHttpErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Icon Style provided..
        /// </summary>
        public static string InvalidStyle {
            get {
                return ResourceManager.GetString("InvalidStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter [ReturnCount].
        /// </summary>
        public static string InvalidValueReturnCount {
            get {
                return ResourceManager.GetString("InvalidValueReturnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Style ForeColor and BackColor cannot be the same value..
        /// </summary>
        public static string MatchingIconStyle {
            get {
                return ResourceManager.GetString("MatchingIconStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowObjectType is required field for Asset Type with class Diagram..
        /// </summary>
        public static string MissingFlowObjectType {
            get {
                return ResourceManager.GetString("MissingFlowObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type not found based on Class provided..
        /// </summary>
        public static string NotFoundBasedOnClass {
            get {
                return ResourceManager.GetString("NotFoundBasedOnClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type not found based on Uid provided..
        /// </summary>
        public static string NotFoundBasedOnUid {
            get {
                return ResourceManager.GetString("NotFoundBasedOnUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type not found..
        /// </summary>
        public static string NotFoundGeneric {
            get {
                return ResourceManager.GetString("NotFoundGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship OR Relationship type exists with this the asset type or any asset under this type participates in the relationship..
        /// </summary>
        public static string RelationshipExistsForAssetType {
            get {
                return ResourceManager.GetString("RelationshipExistsForAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use As Transformation can be set only asset types that are a Business or Technical class..
        /// </summary>
        public static string TransformationClassRestriction {
            get {
                return ResourceManager.GetString("TransformationClassRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of asset types exceeds the Transformation limit..
        /// </summary>
        public static string TransformationLimitExceeded {
            get {
                return ResourceManager.GetString("TransformationLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported asset class..
        /// </summary>
        public static string UnsupportedAssetClass {
            get {
                return ResourceManager.GetString("UnsupportedAssetClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowObjectType is not support for class {0}..
        /// </summary>
        public static string UnsupportedFlowObjectType {
            get {
                return ResourceManager.GetString("UnsupportedFlowObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v2/membership/users.
        /// </summary>
        public static string UserEndPoint {
            get {
                return ResourceManager.GetString("UserEndPoint", resourceCulture);
            }
        }
    }
}
