//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommentErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommentErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.CommentErrors", typeof(CommentErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset with provided Uid does not exist..
        /// </summary>
        public static string AssetUidNotFound {
            get {
                return ResourceManager.GetString("AssetUidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for the Body property..
        /// </summary>
        public static string BodyNotEmpty {
            get {
                return ResourceManager.GetString("BodyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to add a comment to this asset..
        /// </summary>
        public static string CommentAddPermission {
            get {
                return ResourceManager.GetString("CommentAddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment was not successfully removed..
        /// </summary>
        public static string CommentNotRemoved {
            get {
                return ResourceManager.GetString("CommentNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment was not successfully updated..
        /// </summary>
        public static string CommentNotUpdated {
            get {
                return ResourceManager.GetString("CommentNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not provide more than 50 tags on this comment..
        /// </summary>
        public static string CommentTagMaxLimit {
            get {
                return ResourceManager.GetString("CommentTagMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the creator of this comment and may not update it..
        /// </summary>
        public static string CommentUpdatePermission {
            get {
                return ResourceManager.GetString("CommentUpdatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the creator of this comment or administrator and may not update it..
        /// </summary>
        public static string CommentUpdatePermissionAdmin {
            get {
                return ResourceManager.GetString("CommentUpdatePermissionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a valid Uid for the AssetUid property..
        /// </summary>
        public static string InvalidAssetUid {
            get {
                return ResourceManager.GetString("InvalidAssetUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content provided to create a comment with..
        /// </summary>
        public static string NoContentProvided {
            get {
                return ResourceManager.GetString("NoContentProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent comment not found.
        /// </summary>
        public static string ParentCommentNotFound {
            get {
                return ResourceManager.GetString("ParentCommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments may not be created on asset with provided Uid..
        /// </summary>
        public static string RestrictedAssetUid {
            get {
                return ResourceManager.GetString("RestrictedAssetUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to read the specified asset type..
        /// </summary>
        public static string RestrictReadAssettype {
            get {
                return ResourceManager.GetString("RestrictReadAssettype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment was not successfully created..
        /// </summary>
        public static string UnableCreateComment {
            get {
                return ResourceManager.GetString("UnableCreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with provided Uid does not exist..
        /// </summary>
        public static string UserUidNotFound {
            get {
                return ResourceManager.GetString("UserUidNotFound", resourceCulture);
            }
        }
    }
}
