//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyContextErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyContextErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.CompanyContextErrors", typeof(CompanyContextErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to add a relationship type with this predicate..
        /// </summary>
        public static string AddRelationshipValidation_Predicate {
            get {
                return ResourceManager.GetString("AddRelationshipValidation_Predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset not found based on uid &apos;{0}&apos;.
        /// </summary>
        public static string AssetUidNotFound {
            get {
                return ResourceManager.GetString("AssetUidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect Type.
        /// </summary>
        public static string IntersectType {
            get {
                return ResourceManager.GetString("IntersectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Relationship field encountered no relationship type to lookup found in definition..
        /// </summary>
        public static string InvalidRelationShipField {
            get {
                return ResourceManager.GetString("InvalidRelationShipField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TypeIdentifierInfoModel..
        /// </summary>
        public static string InvalidTypeIdentifierInfoModel {
            get {
                return ResourceManager.GetString("InvalidTypeIdentifierInfoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more relationships reference this relationship..
        /// </summary>
        public static string MultiRelationshipsReferRelationship {
            get {
                return ResourceManager.GetString("MultiRelationshipsReferRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields reference this relationship..
        /// </summary>
        public static string MutliReferenceRelationNotAllowed {
            get {
                return ResourceManager.GetString("MutliReferenceRelationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string ObjectAlreadyExists {
            get {
                return ResourceManager.GetString("ObjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not part of assets table.
        /// </summary>
        public static string ObjectNotPartAssetTable {
            get {
                return ResourceManager.GetString("ObjectNotPartAssetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type Cannot Be Created.
        /// </summary>
        public static string RelationShipTypeNotCreated {
            get {
                return ResourceManager.GetString("RelationShipTypeNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type Cannot Be Updated.
        /// </summary>
        public static string RelationShipTypeNotUpdated {
            get {
                return ResourceManager.GetString("RelationShipTypeNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject asset type does not exist..
        /// </summary>
        public static string SubjectAssetTypeNotExists {
            get {
                return ResourceManager.GetString("SubjectAssetTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject and object may not be the same when using this Predicate..
        /// </summary>
        public static string SubjectObjectNotSameThisPredicate {
            get {
                return ResourceManager.GetString("SubjectObjectNotSameThisPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject and object must be the same when using this Predicate..
        /// </summary>
        public static string SubjectObjectSameThisPredicate {
            get {
                return ResourceManager.GetString("SubjectObjectSameThisPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using this predicate either your subject or object must support being used as a transformation, but not both..
        /// </summary>
        public static string ThisPrediateUseTransormationNotBoth {
            get {
                return ResourceManager.GetString("ThisPrediateUseTransormationNotBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using this predicate either your subject or object must support being used as a transformation..
        /// </summary>
        public static string ThisPrediateUseTransormationSubjOrObj {
            get {
                return ResourceManager.GetString("ThisPrediateUseTransormationSubjOrObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Could not be Removed.
        /// </summary>
        public static string TitleRelationNotRemoved {
            get {
                return ResourceManager.GetString("TitleRelationNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected object type {0}.
        /// </summary>
        public static string UnexpectedObjectType {
            get {
                return ResourceManager.GetString("UnexpectedObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using this predicate your object must be one of the following classes : {0}..
        /// </summary>
        public static string WhenPredicateObjectOfClass {
            get {
                return ResourceManager.GetString("WhenPredicateObjectOfClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using this predicate your subject must be one of the following classes : {0}..
        /// </summary>
        public static string WhenPredicateSubjectOfClass {
            get {
                return ResourceManager.GetString("WhenPredicateSubjectOfClass", resourceCulture);
            }
        }
    }
}
