//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Graph.
        /// </summary>
        public static string CompanyRebuildJobToken_AssetGraph {
            get {
                return ResourceManager.GetString("CompanyRebuildJobToken_AssetGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Visualization diagrams for assets. This request may take a significant amount of time to complete, depending on the number of assets contained within your environment. Additionally, this action has a performance impact on your environment..
        /// </summary>
        public static string CompanyRebuildJobToken_AssetGraph_Desc {
            get {
                return ResourceManager.GetString("CompanyRebuildJobToken_AssetGraph_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Values.
        /// </summary>
        public static string CompanyRebuildJobToken_DisplayValues {
            get {
                return ResourceManager.GetString("CompanyRebuildJobToken_DisplayValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild display values for all assets within your environment..
        /// </summary>
        public static string CompanyRebuildJobToken_DisplayValues_Desc {
            get {
                return ResourceManager.GetString("CompanyRebuildJobToken_DisplayValues_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Index.
        /// </summary>
        public static string CompanyRebuildJobToken_SearchIndex {
            get {
                return ResourceManager.GetString("CompanyRebuildJobToken_SearchIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilds the full-text index for all assets within your environment, and can take up to sixty minutes to fully rebuild..
        /// </summary>
        public static string CompanyRebuildJobToken_SearchIndex_Desc {
            get {
                return ResourceManager.GetString("CompanyRebuildJobToken_SearchIndex_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is after.
        /// </summary>
        public static string OperatorAfter {
            get {
                return ResourceManager.GetString("OperatorAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is before.
        /// </summary>
        public static string OperatorBefore {
            get {
                return ResourceManager.GetString("OperatorBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is between.
        /// </summary>
        public static string OperatorBetween {
            get {
                return ResourceManager.GetString("OperatorBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        public static string OperatorContains {
            get {
                return ResourceManager.GetString("OperatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        public static string OperatorEndsWith {
            get {
                return ResourceManager.GetString("OperatorEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string OperatorEquals {
            get {
                return ResourceManager.GetString("OperatorEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than.
        /// </summary>
        public static string OperatorGreaterThan {
            get {
                return ResourceManager.GetString("OperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than or equal to.
        /// </summary>
        public static string OperatorGreaterThanOrEquals {
            get {
                return ResourceManager.GetString("OperatorGreaterThanOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string OperatorIn {
            get {
                return ResourceManager.GetString("OperatorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is false.
        /// </summary>
        public static string OperatorIsFalse {
            get {
                return ResourceManager.GetString("OperatorIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is in band.
        /// </summary>
        public static string OperatorIsInBand {
            get {
                return ResourceManager.GetString("OperatorIsInBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is true.
        /// </summary>
        public static string OperatorIsTrue {
            get {
                return ResourceManager.GetString("OperatorIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        public static string OperatorLessThan {
            get {
                return ResourceManager.GetString("OperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than or equal to.
        /// </summary>
        public static string OperatorLessThanOrEquals {
            get {
                return ResourceManager.GetString("OperatorLessThanOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not contain.
        /// </summary>
        public static string OperatorNotContains {
            get {
                return ResourceManager.GetString("OperatorNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string OperatorNotEquals {
            get {
                return ResourceManager.GetString("OperatorNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not in.
        /// </summary>
        public static string OperatorNotIn {
            get {
                return ResourceManager.GetString("OperatorNotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not populated.
        /// </summary>
        public static string OperatorNotPopulated {
            get {
                return ResourceManager.GetString("OperatorNotPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on or after.
        /// </summary>
        public static string OperatorOnOrAfter {
            get {
                return ResourceManager.GetString("OperatorOnOrAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on or before.
        /// </summary>
        public static string OperatorOnOrBefore {
            get {
                return ResourceManager.GetString("OperatorOnOrBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is populated.
        /// </summary>
        public static string OperatorPopulated {
            get {
                return ResourceManager.GetString("OperatorPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        public static string OperatorStartsWith {
            get {
                return ResourceManager.GetString("OperatorStartsWith", resourceCulture);
            }
        }
    }
}
