//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.errors", typeof(errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this artifact as it participates in {0} intersecting relationship(s)..
        /// </summary>
        public static string ARTIFACT_DELETE_RELATIONS {
            get {
                return ResourceManager.GetString("ARTIFACT_DELETE_RELATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this artifact module.  {0} business rule{1} currently assigned..
        /// </summary>
        public static string ARTIFACTMODULE_DELETE_BUSINESSRULES {
            get {
                return ResourceManager.GetString("ARTIFACTMODULE_DELETE_BUSINESSRULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Module cannot be added or updated because there is another module with the same name..
        /// </summary>
        public static string ARTIFACTMODULE_DUPLICATE {
            get {
                return ResourceManager.GetString("ARTIFACTMODULE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Sub-type cannot be added or updated because there is another sub-type with the same name..
        /// </summary>
        public static string ARTIFACTSUBTYPE_DUPLICATE {
            get {
                return ResourceManager.GetString("ARTIFACTSUBTYPE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Type cannot be added or updated because there is another type with the same name..
        /// </summary>
        public static string ARTIFACTTYPE_DUPLICATE {
            get {
                return ResourceManager.GetString("ARTIFACTTYPE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact cannot be deleted because there are one or more artifact types associated with it..
        /// </summary>
        public static string FACT_DELETE_ARTIFACTTYPEASSIGNMENTS {
            get {
                return ResourceManager.GetString("FACT_DELETE_ARTIFACTTYPEASSIGNMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact cannot be added or updated because there is a sibling fact with the same name..
        /// </summary>
        public static string FACT_DUPLICATE {
            get {
                return ResourceManager.GetString("FACT_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this group.  {0} {1} currently associated..
        /// </summary>
        public static string GROUP_DELETE_ASSIGNMENTS {
            get {
                return ResourceManager.GetString("GROUP_DELETE_ASSIGNMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group cannot be added or updated because there is another group with the same name..
        /// </summary>
        public static string GROUP_DUPLICATE {
            get {
                return ResourceManager.GetString("GROUP_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this grouping as it relates to {0} artifact(s)..
        /// </summary>
        public static string GROUPING_DELETE_RELATIONS {
            get {
                return ResourceManager.GetString("GROUPING_DELETE_RELATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other relationships are dependent on the relationship you are trying to remove.  You must first remove the dependent relationships..
        /// </summary>
        public static string INTERSECT_DELETE_CONSTRAINING {
            get {
                return ResourceManager.GetString("INTERSECT_DELETE_CONSTRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect Type cannot be added or updated because there is another type with the same name..
        /// </summary>
        public static string INTERSECTTYPE_DUPLICATE {
            get {
                return ResourceManager.GetString("INTERSECTTYPE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario cannot be added or updated because there is another scenario with the same configuration..
        /// </summary>
        public static string LINEAGE_DUPLICATE {
            get {
                return ResourceManager.GetString("LINEAGE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario cannot be added or updated because no valid path between start type and end type was found..
        /// </summary>
        public static string LINEAGE_NOVALIDPATHEXISTS {
            get {
                return ResourceManager.GetString("LINEAGE_NOVALIDPATHEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup cannot be deleted because there are artifact types with fields assigned to this lookup..
        /// </summary>
        public static string LOOKUP_DELETE_ASSIGNEDARTIFACTTYPES {
            get {
                return ResourceManager.GetString("LOOKUP_DELETE_ASSIGNEDARTIFACTTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup cannot be deleted because there are facts with fields assigned to this lookup..
        /// </summary>
        public static string LOOKUP_DELETE_ASSIGNEDFACTS {
            get {
                return ResourceManager.GetString("LOOKUP_DELETE_ASSIGNEDFACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup cannot be deleted because there are lookups with fields assigned to this lookup..
        /// </summary>
        public static string LOOKUP_DELETE_ASSIGNEDLOOKUPS {
            get {
                return ResourceManager.GetString("LOOKUP_DELETE_ASSIGNEDLOOKUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup cannot be deleted because there are perspective types with fields assigned to this lookup..
        /// </summary>
        public static string LOOKUP_DELETE_ASSIGNEDPERSPECTIVETYPES {
            get {
                return ResourceManager.GetString("LOOKUP_DELETE_ASSIGNEDPERSPECTIVETYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup cannot be deleted because it is a system lookup..
        /// </summary>
        public static string LOOKUP_DELETE_SYSTEM {
            get {
                return ResourceManager.GetString("LOOKUP_DELETE_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup cannot be added or updated because there is another lookup with the same name..
        /// </summary>
        public static string LOOKUP_DUPLICATE {
            get {
                return ResourceManager.GetString("LOOKUP_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not delete this item because it participates in {0} exception definition(s)..
        /// </summary>
        public static string LOOKUPVALUE_DELETE_TASKRULEBUSINESSRULE {
            get {
                return ResourceManager.GetString("LOOKUPVALUE_DELETE_TASKRULEBUSINESSRULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup value cannot be added or updated because there is a duplicate value..
        /// </summary>
        public static string LOOKUPVALUE_DUPLICATE {
            get {
                return ResourceManager.GetString("LOOKUPVALUE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this quality rule.  {0} group{1} currently set to be auto-assigned to exceptions..
        /// </summary>
        public static string QUALITYRULE_DELETE_AUTOASSIGNMENTS {
            get {
                return ResourceManager.GetString("QUALITYRULE_DELETE_AUTOASSIGNMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this quality rule.  One or more exceptions currently assigned..
        /// </summary>
        public static string QUALITYRULE_DELETE_EXCEPTIONS {
            get {
                return ResourceManager.GetString("QUALITYRULE_DELETE_EXCEPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this quality rule.  {0} resolution{1} currently assigned..
        /// </summary>
        public static string QUALITYRULE_DELETE_RESOLUTIONS {
            get {
                return ResourceManager.GetString("QUALITYRULE_DELETE_RESOLUTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Rule cannot be added or updated because there is another rule assigned to the same module with the same name..
        /// </summary>
        public static string QUALITYRULE_DUPLICATE {
            get {
                return ResourceManager.GetString("QUALITYRULE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource cannot be updated because there is another resource with the same username..
        /// </summary>
        public static string RESOURCE_DUPLICATE {
            get {
                return ResourceManager.GetString("RESOURCE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this role.  {0} {1} currently assigned..
        /// </summary>
        public static string ROLE_DELETE_LOCALASSIGNMENTS {
            get {
                return ResourceManager.GetString("ROLE_DELETE_LOCALASSIGNMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not remove this role.  {0} resource{1} currently assigned..
        /// </summary>
        public static string ROLE_DELETE_RESOURCES {
            get {
                return ResourceManager.GetString("ROLE_DELETE_RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be updated because there is another role with the same name..
        /// </summary>
        public static string ROLE_DUPLICATE {
            get {
                return ResourceManager.GetString("ROLE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status cannot be updated because there is another Status with the same name..
        /// </summary>
        public static string STATUS_DUPLICATE {
            get {
                return ResourceManager.GetString("STATUS_DUPLICATE", resourceCulture);
            }
        }
    }
}
