//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Information {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Information() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.Information", typeof(Information).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} Raised..
        /// </summary>
        public static string ActionAssetCommentBody {
            get {
                return ResourceManager.GetString("ActionAssetCommentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Created.
        /// </summary>
        public static string ActionCreatedMsg {
            get {
                return ResourceManager.GetString("ActionCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type was deleted.
        /// </summary>
        public static string ActionTypeDeleted {
            get {
                return ResourceManager.GetString("ActionTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type Not Found.
        /// </summary>
        public static string ActionTypeNotFound {
            get {
                return ResourceManager.GetString("ActionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type was updated..
        /// </summary>
        public static string ActionTypeUpdated {
            get {
                return ResourceManager.GetString("ActionTypeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocations added successfully.
        /// </summary>
        public static string AddAllocationsSuccessful {
            get {
                return ResourceManager.GetString("AddAllocationsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation added successfully.
        /// </summary>
        public static string AddSingleAllocationSuccessful {
            get {
                return ResourceManager.GetString("AddSingleAllocationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api endpoint uri successfully removed..
        /// </summary>
        public static string ApiEndPointUriRemoved {
            get {
                return ResourceManager.GetString("ApiEndPointUriRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api endpoint version successfully removed..
        /// </summary>
        public static string ApiEndPointVersionRemoved {
            get {
                return ResourceManager.GetString("ApiEndPointVersionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api field successfully removed..
        /// </summary>
        public static string ApiFieldRemoved {
            get {
                return ResourceManager.GetString("ApiFieldRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Field successfully updated..
        /// </summary>
        public static string ApiFieldUpdated {
            get {
                return ResourceManager.GetString("ApiFieldUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api service successfully removed..
        /// </summary>
        public static string ApiServiceRemoved {
            get {
                return ResourceManager.GetString("ApiServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type is created.
        /// </summary>
        public static string AssetTypeCreatedMessage {
            get {
                return ResourceManager.GetString("AssetTypeCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector labels consolidated successfully.
        /// </summary>
        public static string ConsolidateSucessfully {
            get {
                return ResourceManager.GetString("ConsolidateSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct endpoint for {0}s is {1}://{2}{3}.
        /// </summary>
        public static string CorrectEndpoint {
            get {
                return ResourceManager.GetString("CorrectEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dashboard was not found based on the provided unique identifier..
        /// </summary>
        public static string DashboardNotFound {
            get {
                return ResourceManager.GetString("DashboardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard removed.
        /// </summary>
        public static string DashboardRemoved {
            get {
                return ResourceManager.GetString("DashboardRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Deleted Successfully..
        /// </summary>
        public static string DeleteAllocationSuccessful {
            get {
                return ResourceManager.GetString("DeleteAllocationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point successfully removed..
        /// </summary>
        public static string EndPointRemoved {
            get {
                return ResourceManager.GetString("EndPointRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding dashboard.
        /// </summary>
        public static string ErrorOnCreate {
            get {
                return ResourceManager.GetString("ErrorOnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting dashboard.
        /// </summary>
        public static string ErrorOnDelete {
            get {
                return ResourceManager.GetString("ErrorOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving dashboard.
        /// </summary>
        public static string ErrorOnGet {
            get {
                return ResourceManager.GetString("ErrorOnGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating dashboard.
        /// </summary>
        public static string ErrorOnUpdate {
            get {
                return ResourceManager.GetString("ErrorOnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite moved successfully..
        /// </summary>
        public static string FavoriteMoved {
            get {
                return ResourceManager.GetString("FavoriteMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites List Cleared..
        /// </summary>
        public static string FavoritesListCleared {
            get {
                return ResourceManager.GetString("FavoritesListCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted specified favorites.
        /// </summary>
        public static string FavoritesSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("FavoritesSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field successfully created..
        /// </summary>
        public static string FieldCreated {
            get {
                return ResourceManager.GetString("FieldCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field moved successfully..
        /// </summary>
        public static string FieldMovedSuccessfully {
            get {
                return ResourceManager.GetString("FieldMovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded and queued for processing..
        /// </summary>
        public static string FileUploadedAndQueueProcessing {
            get {
                return ResourceManager.GetString("FileUploadedAndQueueProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter removed..
        /// </summary>
        public static string FilterRemove {
            get {
                return ResourceManager.GetString("FilterRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder added successfully.
        /// </summary>
        public static string FolderAdded {
            get {
                return ResourceManager.GetString("FolderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder item removed successfully..
        /// </summary>
        public static string FolderItemRemoved {
            get {
                return ResourceManager.GetString("FolderItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} moved successfully..
        /// </summary>
        public static string FolderMoved {
            get {
                return ResourceManager.GetString("FolderMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} moved down successfully..
        /// </summary>
        public static string FolderMovedDown {
            get {
                return ResourceManager.GetString("FolderMovedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} moved to bottom successfully..
        /// </summary>
        public static string FolderMovedToBottom {
            get {
                return ResourceManager.GetString("FolderMovedToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} moved to top successfully..
        /// </summary>
        public static string FolderMovedToTop {
            get {
                return ResourceManager.GetString("FolderMovedToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} moved up successfully..
        /// </summary>
        public static string FolderMovedUp {
            get {
                return ResourceManager.GetString("FolderMovedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder removed successfully..
        /// </summary>
        public static string FolderRemoved {
            get {
                return ResourceManager.GetString("FolderRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder updated successfully..
        /// </summary>
        public static string FolderUpdated {
            get {
                return ResourceManager.GetString("FolderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar allocation successfully modified..
        /// </summary>
        public static string GrammarAllocationModified {
            get {
                return ResourceManager.GetString("GrammarAllocationModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help menu items have been successfully created..
        /// </summary>
        public static string HelpItemsAdded {
            get {
                return ResourceManager.GetString("HelpItemsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help menu items have been successfully removed..
        /// </summary>
        public static string HelpItemsDeleted {
            get {
                return ResourceManager.GetString("HelpItemsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Menu Items Created..
        /// </summary>
        public static string HelpMenuItemsCreated {
            get {
                return ResourceManager.GetString("HelpMenuItemsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Menu Items Deleted..
        /// </summary>
        public static string HelpMenuItemsDeleted {
            get {
                return ResourceManager.GetString("HelpMenuItemsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Menu Items Updated..
        /// </summary>
        public static string HelpMenuItemsUpdated {
            get {
                return ResourceManager.GetString("HelpMenuItemsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Menu items have been successfully updated..
        /// </summary>
        public static string HelpMenuSuccess {
            get {
                return ResourceManager.GetString("HelpMenuSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid [AssetTypeUid] provided..
        /// </summary>
        public static string InvalidDashboardDashboardAssetTypeUid {
            get {
                return ResourceManager.GetString("InvalidDashboardDashboardAssetTypeUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid [AssetUid] provided..
        /// </summary>
        public static string InvalidDashboardDashboardAssetUid {
            get {
                return ResourceManager.GetString("InvalidDashboardDashboardAssetUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Location] must be one of the following values: List, Detail or Homepage.
        /// </summary>
        public static string InvalidDashboardLocation {
            get {
                return ResourceManager.GetString("InvalidDashboardLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ReportType] must be one of the following values: DqPlus or PowerBi.
        /// </summary>
        public static string InvalidDashboardType {
            get {
                return ResourceManager.GetString("InvalidDashboardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Uid provided..
        /// </summary>
        public static string InvalidDashboardUid {
            get {
                return ResourceManager.GetString("InvalidDashboardUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid [URL] value in [Definition].
        /// </summary>
        public static string InvalidDashboardURL {
            get {
                return ResourceManager.GetString("InvalidDashboardURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON value for [Definition].
        /// </summary>
        public static string InvalidDefinitionValue {
            get {
                return ResourceManager.GetString("InvalidDefinitionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully created and processed..
        /// </summary>
        public static string ItemCreatedProcessed {
            get {
                return ResourceManager.GetString("ItemCreatedProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully removed..
        /// </summary>
        public static string ItemRemoved {
            get {
                return ResourceManager.GetString("ItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully updated and processed..
        /// </summary>
        public static string ItemUpdatedProcessed {
            get {
                return ResourceManager.GetString("ItemUpdatedProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector label removed..
        /// </summary>
        public static string LabelRemoved {
            get {
                return ResourceManager.GetString("LabelRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector label successfully removed..
        /// </summary>
        public static string LabelRemoveSucess {
            get {
                return ResourceManager.GetString("LabelRemoveSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Added.
        /// </summary>
        public static string MetricAdded {
            get {
                return ResourceManager.GetString("MetricAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified metric was successfully added.
        /// </summary>
        public static string MetricAddedSuccessfully {
            get {
                return ResourceManager.GetString("MetricAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric removed..
        /// </summary>
        public static string MetricRemoved {
            get {
                return ResourceManager.GetString("MetricRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric successfully removed..
        /// </summary>
        public static string MetricRemoveMessage {
            get {
                return ResourceManager.GetString("MetricRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Updated.
        /// </summary>
        public static string MetricUpdated {
            get {
                return ResourceManager.GetString("MetricUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified metric was successfully updated.
        /// </summary>
        public static string MetricUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MetricUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard with same name already exists.
        /// </summary>
        public static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace successfully created..
        /// </summary>
        public static string NamespaceCreated {
            get {
                return ResourceManager.GetString("NamespaceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api namespace successfully removed..
        /// </summary>
        public static string NamespaceRemoved {
            get {
                return ResourceManager.GetString("NamespaceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace successfully updated..
        /// </summary>
        public static string NamespaceUpdated {
            get {
                return ResourceManager.GetString("NamespaceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild request received and accepted..
        /// </summary>
        public static string RebuildRequest {
            get {
                return ResourceManager.GetString("RebuildRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request successfully created.
        /// </summary>
        public static string RequestCreatedMsg {
            get {
                return ResourceManager.GetString("RequestCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted.
        /// </summary>
        public static string RequestSubmitted {
            get {
                return ResourceManager.GetString("RequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users password has been successfully updated!.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibility successfully added.
        /// </summary>
        public static string ResponsibilitySuccessAddMessage {
            get {
                return ResourceManager.GetString("ResponsibilitySuccessAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibility successfully deleted.
        /// </summary>
        public static string ResponsibilitySuccessDeleteMessage {
            get {
                return ResourceManager.GetString("ResponsibilitySuccessDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service successfully created..
        /// </summary>
        public static string ServiceCreated {
            get {
                return ResourceManager.GetString("ServiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service endpoint successfully created..
        /// </summary>
        public static string ServiceEndpointCreated {
            get {
                return ResourceManager.GetString("ServiceEndpointCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut added successfully.
        /// </summary>
        public static string ShortcutAdded {
            get {
                return ResourceManager.GetString("ShortcutAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut deleted successfully..
        /// </summary>
        public static string ShortcutDeleted {
            get {
                return ResourceManager.GetString("ShortcutDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut modified successfully.
        /// </summary>
        public static string ShortcutModified {
            get {
                return ResourceManager.GetString("ShortcutModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut {0} moved {1} successfully..
        /// </summary>
        public static string ShortcutMoved {
            get {
                return ResourceManager.GetString("ShortcutMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syles successfully updated..
        /// </summary>
        public static string StyleUpdated {
            get {
                return ResourceManager.GetString("StyleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully added..
        /// </summary>
        public static string SuccessfullyAdded {
            get {
                return ResourceManager.GetString("SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully created..
        /// </summary>
        public static string SucessfullyCreated {
            get {
                return ResourceManager.GetString("SucessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully deleted..
        /// </summary>
        public static string SucessfullyDeleted {
            get {
                return ResourceManager.GetString("SucessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully edited..
        /// </summary>
        public static string SucessfullyEdited {
            get {
                return ResourceManager.GetString("SucessfullyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully removed..
        /// </summary>
        public static string SucessfullyRemoved {
            get {
                return ResourceManager.GetString("SucessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully updated..
        /// </summary>
        public static string SucessfullyUpdated {
            get {
                return ResourceManager.GetString("SucessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym {0} successfully created..
        /// </summary>
        public static string SynonymCreated {
            get {
                return ResourceManager.GetString("SynonymCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym successfully removed.
        /// </summary>
        public static string SynRemoved {
            get {
                return ResourceManager.GetString("SynRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tagged you in a comment on &lt;a href=&apos;{1}&apos; class=&apos;link&apos;&gt;{2}&lt;/a&gt; at {3}.
        /// </summary>
        public static string TaggedCommentMailBody {
            get {
                return ResourceManager.GetString("TaggedCommentMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Comment.
        /// </summary>
        public static string TaggedCommentMailCommentLink {
            get {
                return ResourceManager.GetString("TaggedCommentMailCommentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tagged you in a comment.
        /// </summary>
        public static string TaggedCommentMailHeader {
            get {
                return ResourceManager.GetString("TaggedCommentMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D360 Govern.
        /// </summary>
        public static string TaggedCommentMailSender {
            get {
                return ResourceManager.GetString("TaggedCommentMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tagged you in a comment on {1}.
        /// </summary>
        public static string TaggedCommentMailSubject {
            get {
                return ResourceManager.GetString("TaggedCommentMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag removed..
        /// </summary>
        public static string TagRemoved {
            get {
                return ResourceManager.GetString("TagRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully removed..
        /// </summary>
        public static string TagRemoveMessage {
            get {
                return ResourceManager.GetString("TagRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags removed..
        /// </summary>
        public static string TagRemoveTitle {
            get {
                return ResourceManager.GetString("TagRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Type removed..
        /// </summary>
        public static string TagTypeRemoved {
            get {
                return ResourceManager.GetString("TagTypeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Type successfully removed..
        /// </summary>
        public static string TagTypeRemoveMessage {
            get {
                return ResourceManager.GetString("TagTypeRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Deleted..
        /// </summary>
        public static string TemplateDeleted {
            get {
                return ResourceManager.GetString("TemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Deleted Successfully..
        /// </summary>
        public static string TemplateDeletedMessage {
            get {
                return ResourceManager.GetString("TemplateDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri successfully created..
        /// </summary>
        public static string UriCreated {
            get {
                return ResourceManager.GetString("UriCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version successfully created..
        /// </summary>
        public static string VersionCreated {
            get {
                return ResourceManager.GetString("VersionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version successfully updated..
        /// </summary>
        public static string VersionUpdated {
            get {
                return ResourceManager.GetString("VersionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer watching {0}..
        /// </summary>
        public static string YouAreNoLongerWatching {
            get {
                return ResourceManager.GetString("YouAreNoLongerWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now watching {0}..
        /// </summary>
        public static string YouAreNowWatching {
            get {
                return ResourceManager.GetString("YouAreNowWatching", resourceCulture);
            }
        }
    }
}
