//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are child artifacts assigned to this artifact.  You must first remove the child artifacts..
        /// </summary>
        public static string Error_Artifact_ExistingChildren {
            get {
                return ResourceManager.GetString("Error_Artifact_ExistingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are existing artifacts based on this type..
        /// </summary>
        public static string Error_ArtifactsAssignedToType {
            get {
                return ResourceManager.GetString("Error_ArtifactsAssignedToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute type is allocated to one ore more system objects..
        /// </summary>
        public static string Error_AttributeType_Allocations {
            get {
                return ResourceManager.GetString("Error_AttributeType_Allocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are child types assigned to this type..
        /// </summary>
        public static string Error_ChildTypesAssignedToType {
            get {
                return ResourceManager.GetString("Error_ChildTypesAssignedToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This claim is already assigned to the specified object. You may not add it again..
        /// </summary>
        public static string Error_Claim_AlreadyAssignedToItem {
            get {
                return ResourceManager.GetString("Error_Claim_AlreadyAssignedToItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Relationship Uid identifiers : {0}. Identifiers must be unique within a batch..
        /// </summary>
        public static string Error_Duplicate_Relationship_Uid {
            get {
                return ResourceManager.GetString("Error_Duplicate_Relationship_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field type is allocated to one ore more system objects..
        /// </summary>
        public static string Error_FieldType_Allocations {
            get {
                return ResourceManager.GetString("Error_FieldType_Allocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more JSON Attribute fields reference the field you are attempting to remove..
        /// </summary>
        public static string Error_Item_FieldJsonAttributeReferences {
            get {
                return ResourceManager.GetString("Error_Item_FieldJsonAttributeReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields reference this item..
        /// </summary>
        public static string Error_Item_FieldReferences {
            get {
                return ResourceManager.GetString("Error_Item_FieldReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more relationships reference this item..
        /// </summary>
        public static string Error_Item_RelationshipsReferences {
            get {
                return ResourceManager.GetString("Error_Item_RelationshipsReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields reference this list..
        /// </summary>
        public static string Error_List_FieldReferences {
            get {
                return ResourceManager.GetString("Error_List_FieldReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required..
        /// </summary>
        public static string Error_Name_Required {
            get {
                return ResourceManager.GetString("Error_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is taken. Please try another name..
        /// </summary>
        public static string Error_NameTaken {
            get {
                return ResourceManager.GetString("Error_NameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be removed..
        /// </summary>
        public static string Error_NotRemoved_Tokenized {
            get {
                return ResourceManager.GetString("Error_NotRemoved_Tokenized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has invalid GUID value.
        /// </summary>
        public static string Error_Parameter_InvalidUidValue {
            get {
                return ResourceManager.GetString("Error_Parameter_InvalidUidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more responsibilities are assigned to the group your are trying to remove. You must first remove these responsibilities before continuing..
        /// </summary>
        public static string Error_ResponsibilitiesAssignedToGroup {
            get {
                return ResourceManager.GetString("Error_ResponsibilitiesAssignedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must use When conditions when ApplyToType value is set to false..
        /// </summary>
        public static string Error_Responsibility_ApplyToType_False {
            get {
                return ResourceManager.GetString("Error_Responsibility_ApplyToType_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are existing assignments based on this responsibility type. Please remove those assignments first before continuing..
        /// </summary>
        public static string Error_ResponsibilityType_ExistingResponsibilities {
            get {
                return ResourceManager.GetString("Error_ResponsibilityType_ExistingResponsibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more child models exist. You must first remove the child models before continuing..
        /// </summary>
        public static string Error_Taxonomy_ChildModelsExist {
            get {
                return ResourceManager.GetString("Error_Taxonomy_ChildModelsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields reference this model..
        /// </summary>
        public static string Error_Taxonomy_FieldReference {
            get {
                return ResourceManager.GetString("Error_Taxonomy_FieldReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more people responsibilities exist. You must first remove these responsibilities before continuing..
        /// </summary>
        public static string Error_Taxonomy_PeopleResponsibilitiesExist {
            get {
                return ResourceManager.GetString("Error_Taxonomy_PeopleResponsibilitiesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more relationships reference this model..
        /// </summary>
        public static string Error_Taxonomy_RelationshipReference {
            get {
                return ResourceManager.GetString("Error_Taxonomy_RelationshipReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information model could not be removed.
        /// </summary>
        public static string Error_Taxonomy_RemoveTitle {
            get {
                return ResourceManager.GetString("Error_Taxonomy_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more sourcing responsibilities exist. You must first remove these responsibilities before continuing..
        /// </summary>
        public static string Error_Taxonomy_SourcingResponsibilitiesExist {
            get {
                return ResourceManager.GetString("Error_Taxonomy_SourcingResponsibilitiesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model type is assigned as a subject area to one or more artifacts and may not be removed..
        /// </summary>
        public static string TaxonomyType_Assigned {
            get {
                return ResourceManager.GetString("TaxonomyType_Assigned", resourceCulture);
            }
        }
    }
}
