//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetricsErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetricsErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.MetricsErrors", typeof(MetricsErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ScoreType not recognised.  Value {0}.
        /// </summary>
        public static string AllocationScoreTypeNotRecognised {
            get {
                return ResourceManager.GetString("AllocationScoreTypeNotRecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a valid AllocationUid..
        /// </summary>
        public static string AllocationUidInvalid {
            get {
                return ResourceManager.GetString("AllocationUidInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition group in position {0} must contain a Threshold value between 0 and 1.
        /// </summary>
        public static string ConditionGroupThresholdValue {
            get {
                return ResourceManager.GetString("ConditionGroupThresholdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A condition uses an operator ({0}) that is not valid for fields with a data type of {1}. .
        /// </summary>
        public static string ConditionOperatorNotValid {
            get {
                return ResourceManager.GetString("ConditionOperatorNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Value.
        /// </summary>
        public static string ConditionValue {
            get {
                return ResourceManager.GetString("ConditionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DataQuality filter uses an invalid operator..
        /// </summary>
        public static string DataQualityInvalidOperator {
            get {
                return ResourceManager.GetString("DataQualityInvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DataQuality filter uses an operator ({0}) that is not valid for fields with a data type of {1}..
        /// </summary>
        public static string DataQualityInvalidOperatorForDataType {
            get {
                return ResourceManager.GetString("DataQualityInvalidOperatorForDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A measure belonging to an externally calculated score may not have a DataQuality definition..
        /// </summary>
        public static string DataQualityMustNotExternalCalc {
            get {
                return ResourceManager.GetString("DataQualityMustNotExternalCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Quality Result Filter.
        /// </summary>
        public static string DataQualityResultFilter {
            get {
                return ResourceManager.GetString("DataQualityResultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition must not exceed 4000 characters..
        /// </summary>
        public static string DefinitionNotExceed4000 {
            get {
                return ResourceManager.GetString("DefinitionNotExceed4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition object property must not be empty..
        /// </summary>
        public static string DefinitionObjectPropertyNotEmpty {
            get {
                return ResourceManager.GetString("DefinitionObjectPropertyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not add a metric with the same name under the same grouping..
        /// </summary>
        public static string DuplicateMetricSameGroup {
            get {
                return ResourceManager.GetString("DuplicateMetricSameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding metric.
        /// </summary>
        public static string Erroraddingmetric {
            get {
                return ResourceManager.GetString("Erroraddingmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not alter the conditions of this metric without also altering its effective date..
        /// </summary>
        public static string ErrorConditionAlter {
            get {
                return ResourceManager.GetString("ErrorConditionAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not alter the condition type of this metric without also altering its effective date..
        /// </summary>
        public static string ErrorConditionTypeAlter {
            get {
                return ResourceManager.GetString("ErrorConditionTypeAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not convert this grouping to a metric as there are child metrics already associated with it..
        /// </summary>
        public static string ErrorConvertGroupToMetricChildExists {
            get {
                return ResourceManager.GetString("ErrorConvertGroupToMetricChildExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not convert this metric to a grouping as there are results already associated with it..
        /// </summary>
        public static string ErrorConvertMetricToGroup {
            get {
                return ResourceManager.GetString("ErrorConvertMetricToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating measure.
        /// </summary>
        public static string ErrorCreatingMeasure {
            get {
                return ResourceManager.GetString("ErrorCreatingMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not alter the definition of this metric without also altering its effective date..
        /// </summary>
        public static string ErrorDefinitionAlter {
            get {
                return ResourceManager.GetString("ErrorDefinitionAlter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating measure.
        /// </summary>
        public static string ErrorUpdatingMeasure {
            get {
                return ResourceManager.GetString("ErrorUpdatingMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating metric.
        /// </summary>
        public static string Errorupdatingmetric {
            get {
                return ResourceManager.GetString("Errorupdatingmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not alter the weight of this metric without also altering its effective date..
        /// </summary>
        public static string ErrorWeightalter {
            get {
                return ResourceManager.GetString("ErrorWeightalter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldType does not exist!.
        /// </summary>
        public static string FieldTypeNotFound {
            get {
                return ResourceManager.GetString("FieldTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governance Field Check.
        /// </summary>
        public static string GovernanceFieldCheck {
            get {
                return ResourceManager.GetString("GovernanceFieldCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A measure belonging to an externally calculated score may not have a Governance definition..
        /// </summary>
        public static string GovernanceMustNotExternalCalc {
            get {
                return ResourceManager.GetString("GovernanceMustNotExternalCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Governance {0} does not support the selected operator..
        /// </summary>
        public static string GovernanceNotSupportOperator {
            get {
                return ResourceManager.GetString("GovernanceNotSupportOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governance Relation Check.
        /// </summary>
        public static string GovernanceRelationCheck {
            get {
                return ResourceManager.GetString("GovernanceRelationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions for External check cannot be longer than 500 characters..
        /// </summary>
        public static string InstrunctionExternalCheckMax500Char {
            get {
                return ResourceManager.GetString("InstrunctionExternalCheckMax500Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid FieldType for this asset!.
        /// </summary>
        public static string InvalidFieldTypeAsset {
            get {
                return ResourceManager.GetString("InvalidFieldTypeAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field type name ({0}) used on your Governance Field Check does not exist on this asset type..
        /// </summary>
        public static string InvalidFieldTypeGovernanceFieldCheck {
            get {
                return ResourceManager.GetString("InvalidFieldTypeGovernanceFieldCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field type name ({0}) used on your Governance Field Check does not support the selected operator..
        /// </summary>
        public static string InvalidOperatorGovernanceFieldCheck {
            get {
                return ResourceManager.GetString("InvalidOperatorGovernanceFieldCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure does not belong to a valid Allocation, indicating an invalid measure..
        /// </summary>
        public static string MeasureInvalidAllocation {
            get {
                return ResourceManager.GetString("MeasureInvalidAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure with name &apos;{0}&apos; already exists..
        /// </summary>
        public static string MeasureNameAlreadyExists {
            get {
                return ResourceManager.GetString("MeasureNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure does not belong to allocation with Uid of {0}..
        /// </summary>
        public static string MeasureNotAllocationUid {
            get {
                return ResourceManager.GetString("MeasureNotAllocationUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure is currently being recalculated. Please wait until we have completed this action then try again..
        /// </summary>
        public static string MeasureRecalculated {
            get {
                return ResourceManager.GetString("MeasureRecalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure with Uid of {0} could not be found..
        /// </summary>
        public static string MeasureUidNotFound {
            get {
                return ResourceManager.GetString("MeasureUidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure does not contain any versions, indicating an invalid measure..
        /// </summary>
        public static string MeasureWithNoVersion {
            get {
                return ResourceManager.GetString("MeasureWithNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not backdate the effective date for this metric. You must provide date more recent than {0}.
        /// </summary>
        public static string MetricBackDateEntryNotAllowed {
            get {
                return ResourceManager.GetString("MetricBackDateEntryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are have provided a null metric..
        /// </summary>
        public static string MetricNotNull {
            get {
                return ResourceManager.GetString("MetricNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric with UID {0} does not exist..
        /// </summary>
        public static string MetricUidNotExists {
            get {
                return ResourceManager.GetString("MetricUidNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be longer than 250 characters..
        /// </summary>
        public static string NameMax250Char {
            get {
                return ResourceManager.GetString("NameMax250Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not provide a DataQuality object property under Definition..
        /// </summary>
        public static string NotProvideDataQualityUnderDefinition {
            get {
                return ResourceManager.GetString("NotProvideDataQualityUnderDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not provide a Governance object property under Definition..
        /// </summary>
        public static string NotProvideGovernanceUnderDefinition {
            get {
                return ResourceManager.GetString("NotProvideGovernanceUnderDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more values used on your DataQuality filters are not supported by the data type ({0}) of the referenced field..
        /// </summary>
        public static string OneMoreValueDataQualityNotSupportDataType {
            get {
                return ResourceManager.GetString("OneMoreValueDataQualityNotSupportDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more values used on your Governance Field Check are not supported by the data type ({0}) of the referenced field..
        /// </summary>
        public static string OneMoreValueGovernanceNotSupportDataType {
            get {
                return ResourceManager.GetString("OneMoreValueGovernanceNotSupportDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more values used on your Governance Relation Check are not supported. All values must correspond to existing asset Uids..
        /// </summary>
        public static string OneMoreValueGovernanceRelationNotSupport {
            get {
                return ResourceManager.GetString("OneMoreValueGovernanceRelationNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator used on your {0} does not support {1} values. You must provide exactly {2} value(s) for this operator..
        /// </summary>
        public static string OperatorAcceptExactValue {
            get {
                return ResourceManager.GetString("OperatorAcceptExactValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator used on your {0} does not support {1} values. You must provide between {2} and {3} values for this operator..
        /// </summary>
        public static string OperatorAcceptRangeValue {
            get {
                return ResourceManager.GetString("OperatorAcceptRangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator used on your {0} does not support {1} values. You must not provide any values for this operator..
        /// </summary>
        public static string OperatorNotAcceptAnyValue {
            get {
                return ResourceManager.GetString("OperatorNotAcceptAnyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent metric not found..
        /// </summary>
        public static string ParentMetricNotFound {
            get {
                return ResourceManager.GetString("ParentMetricNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide the DataQuality object property under Definition..
        /// </summary>
        public static string ProvideDataQualityUnderDefinition {
            get {
                return ResourceManager.GetString("ProvideDataQualityUnderDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide the Governance object property under Definition..
        /// </summary>
        public static string ProvideGovernanceUnderDefinition {
            get {
                return ResourceManager.GetString("ProvideGovernanceUnderDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must not provide a value for the Threshold property since the measure you are adding does not belong to a threshold-based score definition..
        /// </summary>
        public static string ProvideValueForNotThresholdBasedScoring {
            get {
                return ResourceManager.GetString("ProvideValueForNotThresholdBasedScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have referenced an invalid field as part of your DataQuality filters, either because it was not found or is using an improper operator..
        /// </summary>
        public static string ReferInvalidFieldDataQualityFilters {
            get {
                return ResourceManager.GetString("ReferInvalidFieldDataQualityFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultPathUid may not be an empty identifier..
        /// </summary>
        public static string ResultPathUidNotEmpty {
            get {
                return ResourceManager.GetString("ResultPathUidNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultPathUid with the specified identifier {0} does not exist or does not correspond to the asset type you are scoring..
        /// </summary>
        public static string ResultPathUidNotValid {
            get {
                return ResourceManager.GetString("ResultPathUidNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition group in position {0} must not provide a value for the Threshold property since the measure you are adding does not belong to a threshold-based measure..
        /// </summary>
        public static string ScoreDefinitionNotThresholdBased {
            get {
                return ResourceManager.GetString("ScoreDefinitionNotThresholdBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold must be a value between 0 and 1.
        /// </summary>
        public static string ThresholdRangeCheck {
            get {
                return ResourceManager.GetString("ThresholdRangeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uid Governance Owner Check does not correspond to a known responsibility type..
        /// </summary>
        public static string UidGovernanceOwnerCheck {
            get {
                return ResourceManager.GetString("UidGovernanceOwnerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uid Governance Predicate Check does not correspond to a known predicate..
        /// </summary>
        public static string UidGovernancePredicateCheck {
            get {
                return ResourceManager.GetString("UidGovernancePredicateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uid Governance Relation Check does not correspond to a known relationship type..
        /// </summary>
        public static string UidGovernanceRelationCheck {
            get {
                return ResourceManager.GetString("UidGovernanceRelationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide valid (non-empty) field names (API Name of the field definition) when using Rule Result Filters..
        /// </summary>
        public static string ValidApiFieldNameWhenRuleResultFilterUse {
            get {
                return ResourceManager.GetString("ValidApiFieldNameWhenRuleResultFilterUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide valid (non-empty) asset type identifiers when using Rule Result Filters..
        /// </summary>
        public static string ValidAssetTypeUidWhenRuleResultFilterUse {
            get {
                return ResourceManager.GetString("ValidAssetTypeUidWhenRuleResultFilterUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more values used on your condition is not supported by the data type ({0}) of the referenced field..
        /// </summary>
        public static string ValueNotSupportByDataType {
            get {
                return ResourceManager.GetString("ValueNotSupportByDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight can have a maximum of 2 decimal places..
        /// </summary>
        public static string WeightDecimalCheck {
            get {
                return ResourceManager.GetString("WeightDecimalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be a value between 0 and 1.
        /// </summary>
        public static string WeightRangeCheck {
            get {
                return ResourceManager.GetString("WeightRangeCheck", resourceCulture);
            }
        }
    }
}
