//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OthersError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OthersError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.OthersError", typeof(OthersError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to index individual errors: .
        /// </summary>
        public static string AddIndexIndividualErrors {
            get {
                return ResourceManager.GetString("AddIndexIndividualErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use a search strategy of none.
        /// </summary>
        public static string CannotUseSearch {
            get {
                return ResourceManager.GetString("CannotUseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request contains duplicate combinations of assetUid, metricAssetUid, and effectiveDate. You must send in unique combinations for those three fields..
        /// </summary>
        public static string DuplicateCombination {
            get {
                return ResourceManager.GetString("DuplicateCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for assetTypeUid parameter.
        /// </summary>
        public static string InvalidAssetTypeUid {
            get {
                return ResourceManager.GetString("InvalidAssetTypeUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Measure Found.
        /// </summary>
        public static string InvalidMeasureFound {
            get {
                return ResourceManager.GetString("InvalidMeasureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for order parameter. Use Name|ValidForDays|CreatedOn|UpdatedOn|NumberOfResponses.
        /// </summary>
        public static string InvalidOrderSurvey {
            get {
                return ResourceManager.GetString("InvalidOrderSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for page num parameter.
        /// </summary>
        public static string InvalidPageNum {
            get {
                return ResourceManager.GetString("InvalidPageNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for page size parameter.
        /// </summary>
        public static string InvalidPageSize {
            get {
                return ResourceManager.GetString("InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response no data.
        /// </summary>
        public static string InvalidResponseData {
            get {
                return ResourceManager.GetString("InvalidResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for surveyTypeUid parameter.
        /// </summary>
        public static string InvalidSurveyTypeUid {
            get {
                return ResourceManager.GetString("InvalidSurveyTypeUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job is currently in an Active state and cannot be scheduled again until complete..
        /// </summary>
        public static string JobinActiveState {
            get {
                return ResourceManager.GetString("JobinActiveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job is not currently running and cannot be marked as complete..
        /// </summary>
        public static string JobIsNotRunning {
            get {
                return ResourceManager.GetString("JobIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job is currently running.
        /// </summary>
        public static string JobIsRunning {
            get {
                return ResourceManager.GetString("JobIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job is not currently running.
        /// </summary>
        public static string JobNotRunning {
            get {
                return ResourceManager.GetString("JobNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEV ERROR - NO SEARCH BASE URL SPECIFIED..
        /// </summary>
        public static string NoSearchUrlError {
            get {
                return ResourceManager.GetString("NoSearchUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine server version.
        /// </summary>
        public static string NotDetermineServerVersion {
            get {
                return ResourceManager.GetString("NotDetermineServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile record does not exist for provided Uid..
        /// </summary>
        public static string ProfileRecordNotExists {
            get {
                return ResourceManager.GetString("ProfileRecordNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Type is invalid..
        /// </summary>
        public static string SignatureTypeInvalid {
            get {
                return ResourceManager.GetString("SignatureTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Type is required..
        /// </summary>
        public static string SignatureTypeRequired {
            get {
                return ResourceManager.GetString("SignatureTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown search strategy: .
        /// </summary>
        public static string UnknownSearchStrategy {
            get {
                return ResourceManager.GetString("UnknownSearchStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update index individual errors:.
        /// </summary>
        public static string UpdateIndexIndividualErrors {
            get {
                return ResourceManager.GetString("UpdateIndexIndividualErrors", resourceCulture);
            }
        }
    }
}
