//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d360.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SurveyTypeErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SurveyTypeErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d360.core.resources.SurveyTypeErrors", typeof(SurveyTypeErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description should not exceed {maxDescriptionLength} characters.
        /// </summary>
        public static string DescriptionTooBig {
            get {
                return ResourceManager.GetString("DescriptionTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey with the same name already exists for this asset type..
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another survey with the same name already exists for this asset type..
        /// </summary>
        public static string DuplicateNameWhenUpdating {
            get {
                return ResourceManager.GetString("DuplicateNameWhenUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question with the same name already exists for this survey type..
        /// </summary>
        public static string DuplicateQuestionNameWhenUpdating {
            get {
                return ResourceManager.GetString("DuplicateQuestionNameWhenUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter unique option value for option #{index}.
        /// </summary>
        public static string DuplicateQuestionOptionName {
            get {
                return ResourceManager.GetString("DuplicateQuestionOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter unique option identifier for option #{index}.
        /// </summary>
        public static string DuplicateQuestionOptionValue {
            get {
                return ResourceManager.GetString("DuplicateQuestionOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for direction parameter. Use asc|desc..
        /// </summary>
        public static string InvalidDirection {
            get {
                return ResourceManager.GetString("InvalidDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Display Style.
        /// </summary>
        public static string InvalidDisplayStyle {
            get {
                return ResourceManager.GetString("InvalidDisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing a Name in option #{index}.
        /// </summary>
        public static string MissingQuestionOptionName {
            get {
                return ResourceManager.GetString("MissingQuestionOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing one or more options..
        /// </summary>
        public static string MissingQuestionOptions {
            get {
                return ResourceManager.GetString("MissingQuestionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should not exceed {maxNameLength} characters..
        /// </summary>
        public static string NameIsTooBig {
            get {
                return ResourceManager.GetString("NameIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be not empty..
        /// </summary>
        public static string NameShouldBeNotEmpty {
            get {
                return ResourceManager.GetString("NameShouldBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey question with the specified Uid was does not exist..
        /// </summary>
        public static string QuestionTypeNotFound {
            get {
                return ResourceManager.GetString("QuestionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question response already submitted by user and may no longer be updated. Only Description may be updated..
        /// </summary>
        public static string SubmittedQuestionCanChangeOnlyDescription {
            get {
                return ResourceManager.GetString("SubmittedQuestionCanChangeOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey with the specified Uid does not exist..
        /// </summary>
        public static string SurveyTypeNotFound {
            get {
                return ResourceManager.GetString("SurveyTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidForDays must be {maxValidForDays} days or less..
        /// </summary>
        public static string ValidForDaysIsTooBig {
            get {
                return ResourceManager.GetString("ValidForDaysIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidForDays must be {minValidForDays} days or greater..
        /// </summary>
        public static string ValidForDaysIsTooSmall {
            get {
                return ResourceManager.GetString("ValidForDaysIsTooSmall", resourceCulture);
            }
        }
    }
}
