import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/forms';
import '@angular/http';
import '@angular/router';
import 'rxjs/Rx';

import 'primeng/primeng';
import 'lodash';
import 'angular2-highcharts';
import 'highcharts/highcharts';
import 'highcharts/highcharts-more';
import 'highcharts/modules/solid-gauge';
import 'brace';
import 'brace/mode/sql';
import 'brace/theme/eclipse';
import 'gojs';