<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.4" />
    <PackageReference Include="EnterpriseLibrary.TransientFaultHandling.Data" Version="6.0.1304.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="2.0.0" />
    <PackageReference Include="WindowsAzure.ServiceBus" Version="3.4.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\igx.jobs\igx.jobs.csproj" />
  </ItemGroup>
</Project>
