import { AdminGovernanceComponent } from './admin-governance.component';
import { AdminSettingsComponent } from './admin-settings.component';
import { AdminDomainComponent } from './admin-domain.component';
import { AdminGroupsComponent } from './admin-groups.component';
import { AdminWorkflowComponent } from './admin-workflow.component';
import { AdminArtifactsComponent } from './admin-artifacts.component';
import { AdminTemplatesComponent } from './admin-templates.component';
import { AdminTaxonomiesComponent } from './admin-taxonomies.component';
import { AdminLookupsComponent } from './admin-lookups.component';
import { AdminRulesComponent } from './admin-rules.component';
import { AdminPoliciesComponent } from './admin-policies.component';
import { AdminAttributesComponent } from './admin-attributes.component';
import { AdminRelationshipsComponent } from './admin-relationships.component';
import { AdminResourcesComponent } from './admin-resources.component';
import { AdminStatisticsComponent } from './admin-statistics.component';
import { AdminDashboardsComponent } from './admin-dashboards.component';
import { AdminLoadComponent } from './admin-load.component';
import { AdminFusionComponent } from './admin-fusion.component';
import { AdminSurveysComponent } from './admin-surveys.component';
import { AdminComponent } from './admin.component';
import { AdminAttributeTypeEditor } from './admin-attribute-type-editor.component';
import { AdminDashboardsEditor } from './admin-dashboards-editor.component';
import { AdminLookupTypeEditorComponent } from './admin-lookup-type-editor.component';
import { AdminRelationshipsEditor } from './admin-relationships-editor.component';
import { AdminReportItemsComponent } from './admin-report-items.component';
import { AdminStatisticEditor } from './admin-statistics-editor.component';
import { AdminSurveyQuestionEditorEditor } from './admin-survey-question-editor.component';
import { AdminTaxonomyEditorComponent } from './admin-taxonomy-editor.component';
import { AdminTaxonomyDetailComponent } from './admin-taxonomy-detail.component';
import { AdminTaxonomyLevelEditorComponent } from './admin-taxonomy-level-editor.component';
import { AdminTemplateEditorComponent } from './admin-template-editor';
import { AdminStatisticCheckTypeInput } from './admin-statistic-checktype-input';
import { AdminReportLayoutComponent } from './admin-report-layout.component';
import { AdminSurveyQuestionsComponent } from './admin-survey-questions.component';
import { AdminRuleDimensionsComponent } from './admin-rule-dimensions.component';
import { AdminRelationshipsListComponent } from './admin-relationships-list.component';
import { AdminModelLevelComponent } from './admin-model-level.component';
import { AdminModelClassificationComponent } from './admin-model-classification.component';
import { AdminRelationshipRolesComponent } from './admin-relationship-roles.component';

export * from './admin-governance.component';
export * from './admin-settings.component';
export * from './admin-domain.component';
export * from './admin-groups.component';
export * from './admin-workflow.component';
export * from './admin-artifacts.component';
export * from './admin-templates.component';
export * from './admin-taxonomies.component';
export * from './admin.component';
export * from './admin-lookups.component';
export * from './admin-rules.component';
export * from './admin-policies.component';
export * from './admin-attributes.component';
export * from './admin-relationships.component';
export * from './admin-resources.component';
export * from './admin-relationships.component';
export * from './admin-statistics.component';
export * from './admin-dashboards.component';
export * from './admin-fusion.component';
export * from './admin-load.component';
export * from './admin-surveys.component';
export * from './admin-attribute-type-editor.component';
export * from './admin-dashboards-editor.component';
export * from './admin-lookup-type-editor.component';
export * from './admin-relationships-editor.component';
export * from './admin-statistics-editor.component';
export * from './admin-survey-question-editor.component';
export * from './admin-taxonomy-editor.component';
export * from './admin-taxonomy-detail.component';
export * from './admin-taxonomy-level-editor.component';
export * from './admin-template-editor';
export * from './admin-statistic-checktype-input';
export * from './admin-report-items.component';
export * from './admin-report-layout.component';
export * from './admin-survey-questions.component';
export * from './admin-rule-dimensions.component';
export * from './admin-relationships-list.component';
export * from './admin-model-level.component';
export * from './admin-model-classification.component';
export * from './admin-relationship-roles.component';