import { AdminGovernanceComponent } from './admin-governance.component';
import { AdminSettingsComponent } from './admin-settings.component';
import { AdminDomainComponent } from './admin-domain.component';
import { AdminGroupsComponent } from './admin-groups.component';
import { AdminWorkflowComponent } from './admin-workflow.component';
import { AdminArtifactsComponent } from './admin-artifacts.component';
import { AdminTemplatesComponent } from './admin-templates.component';
import { AdminTaxonomiesComponent } from './admin-taxonomies.component';
import { AdminLookupsComponent } from './admin-lookups.component';
import { AdminRulesComponent } from './admin-rules.component';
import { AdminPoliciesComponent } from './admin-policies.component';
import { AdminAttributesComponent } from './admin-attributes.component';
import { AdminRelationshipsComponent } from './admin-relationships.component';
import { AdminComponent } from './admin.component';


export * from './admin-governance.component';
export * from './admin-settings.component';
export * from './admin-domain.component';
export * from './admin-groups.component';
export * from './admin-workflow.component';
export * from './admin-artifacts.component';
export * from './admin-templates.component';
export * from './admin-taxonomies.component';
export * from './admin.component';
export * from './admin-lookups.component';
export * from './admin-rules.component';
export * from './admin-policies.component';
export * from './admin-attributes.component';
export * from './admin-relationships.component';