CREATE TABLE [dbo].[MapTypeTemplate](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MapTypeID] [int] NOT NULL,
	[Name] [varchar](150) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO


