<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net48</TargetFrameworks>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\constants\constants.csproj" />
	  <ProjectReference Include="..\d360.core\d360.core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="models\" />
	</ItemGroup>

</Project>
