<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <ItemGroup>    
    <PackageReference Include="Dapper" Version="1.50.2" />    
    <PackageReference Include="EnterpriseLibrary.TransientFaultHandling" Version="6.0.1304" />    
    <PackageReference Include="EnterpriseLibrary.TransientFaultHandling.Data" Version="6.0.1304.1" />    
    <PackageReference Include="Mandrill.net" Version="4.1.0" />    
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\d360.core\d360.core.csproj" />
    <ProjectReference Include="..\d360.extensions\d360.extensions.csproj" />
    <ProjectReference Include="..\d360.utils.company\d360.utils.company.csproj" />
    <ProjectReference Include="..\d360.utils\d360.utils.csproj" />
    <ProjectReference Include="..\igx.function\igx.function.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
