<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net48</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
    <Compile Update="Information.de-DE.Designer.cs">
      <DependentUpon>Information.de-DE.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Information.es-ES.Designer.cs">
      <DependentUpon>Information.es-ES.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Information.fr-FR.Designer.cs">
      <DependentUpon>Information.fr-FR.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Information.it-IT.Designer.cs">
      <DependentUpon>Information.it-IT.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Information.nl-NL.Designer.cs">
      <DependentUpon>Information.nl-NL.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Error.fr-FR.Designer.cs">
      <DependentUpon>Error.fr-FR.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Error.it-IT.Designer.cs">
      <DependentUpon>Error.it-IT.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Error.nl-NL.Designer.cs">
      <DependentUpon>Error.nl-NL.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Error.es-ES.Designer.cs">
      <DependentUpon>Error.es-ES.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Error.de-DE.Designer.cs">
      <DependentUpon>Error.de-DE.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Error.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Error.resx</DependentUpon>
    </Compile>
    <Compile Update="Information.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Information.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Information.de-DE.resx">
      <LastGenOutput>Information.de-DE.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Information.es-ES.resx">
      <LastGenOutput>Information.es-ES.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Information.fr-FR.resx">
      <LastGenOutput>Information.fr-FR.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Information.it-IT.resx">
      <LastGenOutput>Information.it-IT.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Information.nl-NL.resx">
      <LastGenOutput>Information.nl-NL.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Error.fr-FR.resx">
      <LastGenOutput>Error.fr-FR.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Error.it-IT.resx">
      <LastGenOutput>Error.it-IT.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Error.nl-NL.resx">
      <LastGenOutput>Error.nl-NL.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Error.es-ES.resx">
      <LastGenOutput>Error.es-ES.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Error.de-DE.resx">
      <LastGenOutput>Error.de-DE.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Error.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Error.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Information.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Information.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
