trigger:
  branches:
    include:
      - '*sprint*'
  paths:
    include:
      - '/'
    exclude:
    - '/igx.functions'
    - '/igx.jobs'
    - '/igx.jobs.*'
    - '/igx.CertificateManager'
    - '/igx.UpdateDatabases'
    - '/DBUpdateScripts'
  batch: true
pr:
  autoCancel: false
  drafts: true
  branches:
    include:
    - '*sprint*'
  paths:
    include:
      - '/'
    exclude:
    - '/igx.functions'
    - '/igx.jobs'
    - '/igx.jobs.*'
    - '/igx.CertificateManager'
    - '/igx.UpdateDatabases'
    - '/DBUpdateScripts'
name: $(SourceBranchName)-$(Date:MM-dd-yyyy)$(Rev:.r)
resources:
  repositories:
  - repository: self
    type: git
  - repository: templates
    type: github
    name: Infogix/govern-pipeline-templates
    ref: refs/heads/main
    endpoint: 'govern-build - Service Endpoint'
  - repository: global-templates
    type: github
    name: Infogix/ado-pipeline-templates
    ref: refs/heads/main
    endpoint: 'govern-build - Service Endpoint'
  - repository: devops
    type: github
    name: Infogix/devops
    ref: refs/heads/master
    endpoint: 'govern-build - Service Endpoint'
stages:
- stage: BUILD_NAME
  displayName: 'Set build name'
  dependsOn: []
  jobs:
  - template: build/jobs/job-build-name.yml@templates
- stage: UNIT_TESTS
  displayName: 'Run unit tests'
  dependsOn: []
  jobs:
  - template: build/jobs/job-govern-UI-dotnet-unit-tests.yml@templates
- stage: BUNDLE_SCRIPTS
  displayName: 'Bundle scripts'
  dependsOn: []
  jobs:
  - job: BundleScripts
    displayName: "Bundle scripts"
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 5
    variables:
      npm_config_cache: $(Pipeline.Workspace)/.npm
    pool:
      vmImage: ubuntu-20.04
    steps:
    - checkout: self
    - script: mkdir $(Build.Repository.LocalPath)/d360.web/Scripts/dist
    - script: yarn
      workingDirectory: 'd360.web'
    - script: yarn run build-dev-ops-prod-linux
      workingDirectory: 'd360.web'
    - publish: $(Build.Repository.LocalPath)/d360.web/Scripts/dist
      displayName: 'Publish bundled scripts for later use'
      artifact: dist
- stage: BUILD
  displayName: 'Build solution'
  dependsOn:
  - UNIT_TESTS
  - BUNDLE_SCRIPTS
  jobs:
  - job: UiBuild
    displayName: 'UI Build and deploy'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 5
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
    - download: current
      artifact: dist
    - task: CopyFiles@2
      displayName: 'Copy bundled scripts'
      inputs:
        sourceFolder: $(Pipeline.Workspace)
        contents: 'dist/**'
        targetFolder: $(Build.Repository.LocalPath)/d360.web/Scripts/
    - template: build/steps/step-t4-transform.yml@templates
    - template: build/steps/step-dotnet-build.yml@templates
      parameters:
        solutionToRestore: D360.sln
        solutionToBuild: d360.web/d360.web.csproj
        nuGetCommand: 'restore -Project2ProjectTimeOut 20'
        buildArguments: '/p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package  /p:PackageAsSingleFile=true  /p:PackageLocation="$(Build.Repository.LocalPath)\d360.web\bin\Release\web.zip" /p:PrecompileBeforePublish=true '
    - template: build/steps/step-azure-key-vault.yml@templates
      parameters:
        secretsFilter: blackduckApi
    - template: build/steps/step-blackduck-nuget.yml@templates
      parameters:
        blackduckApiToken: $(blackduckApi)
        projectName: 'InfogixData360-Govern-UI'
        blackDuckScanDirectory: $PWD
    - template: build/steps/step-blackduck-npm.yml@templates
      parameters:
        blackduckApiToken: $(blackduckApi)
        projectName: 'InfogixData360-Govern-UI'
        blackDuckScanDirectory: $PWD/d360.web
    - checkout: devops
    - template: blackduck-third-party-license/steps/blackduck-thirdpartylicense.yml@global-templates
      parameters:
        blackDuckProjectVersion: "e2471ee7-ddf2-4905-9f1d-fcf02efdea3b"
        blackDuckApiToken: $(blackduckApi)
        blackDuckScriptLocation: "$(Pipeline.Workspace)/scripts/common/blackduck/thirdpartylicense.py"
    - template: blackduck-third-party-license/steps/blackduck-extractzip.yml@global-templates
    - task: Bash@3
      displayName: 'Move BlackDuck Third Party License File'
      inputs:
        targetType: inline
        failOnStderr: true
        workingDirectory: $(Build.SourcesDirectory)
        script: |
          mv thirdpartylicense.json $(Build.Repository.LocalPath)\WEB\Content\D_C\a\1\s\d360.web\obj\Release\Package\PackageTmp\Content\version-license.json
    - task: ArchiveFiles@2
      displayName: 'Add License Attribution File to Distro'
      inputs:
        rootFolderOrFile: $(Build.Repository.LocalPath)\WEB\
        includeRootFolder: false
        sevenZipCompression: 5
        archiveFile: $(Build.Repository.LocalPath)\d360.web\bin\Release\web.zip
        replaceExistingArchive: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Web Distro to Build'
      inputs:
        PathtoPublish: $(Build.Repository.LocalPath)\d360.web\bin\Release\web.zip
        ArtifactName: Govern-UI
- stage: UPDATE_VG_DB_DEPLOYMENTS
  displayName: 'Update Variable Groups for DB deployments'
  dependsOn: []
  jobs:
  - template: build/jobs/job-update-vg-db-deployments.yml@templates
