

export class FontAwesomeHelper {

    static GetHtmlCode(code: string): string {
        if (!code)
            return '';
        var icon = this.icons.filter(x => x.class == code)[0];
        return icon ? icon.html.replace(";", "") : '';
    }

    static icons = [{
        "class": "fa-500px",
        "html": "\uf26e;"
    }, {
        "class": "fa-address-book",
        "html": "\uf2b9;"
    }, {
        "class": "fa-address-book-o",
        "html": "\uf2ba;"
    }, {
        "class": "fa-address-card",
        "html": "\uf2bb;"
    }, {
        "class": "fa-address-card-o",
        "html": "\uf2bc;"
    }, {
        "class": "fa-adjust",
        "html": "\uf042;"
    }, {
        "class": "fa-adn",
        "html": "\uf170;"
    }, {
        "class": "fa-align-center",
        "html": "\uf037;"
    }, {
        "class": "fa-align-justify",
        "html": "\uf039;"
    }, {
        "class": "fa-align-left",
        "html": "\uf036;"
    }, {
        "class": "fa-align-right",
        "html": "\uf038;"
    }, {
        "class": "fa-amazon",
        "html": "\uf270;"
    }, {
        "class": "fa-ambulance",
        "html": "\uf0f9;"
    }, {
        "class": "fa-american-sign-language-interpreting",
        "html": "\uf2a3;"
    }, {
        "class": "fa-anchor",
        "html": "\uf13d;"
    }, {
        "class": "fa-android",
        "html": "\uf17b;"
    }, {
        "class": "fa-angellist",
        "html": "\uf209;"
    }, {
        "class": "fa-angle-double-down",
        "html": "\uf103;"
    }, {
        "class": "fa-angle-double-left",
        "html": "\uf100;"
    }, {
        "class": "fa-angle-double-right",
        "html": "\uf101;"
    }, {
        "class": "fa-angle-double-up",
        "html": "\uf102;"
    }, {
        "class": "fa-angle-down",
        "html": "\uf107;"
    }, {
        "class": "fa-angle-left",
        "html": "\uf104;"
    }, {
        "class": "fa-angle-right",
        "html": "\uf105;"
    }, {
        "class": "fa-angle-up",
        "html": "\uf106;"
    }, {
        "class": "fa-apple",
        "html": "\uf179;"
    }, {
        "class": "fa-archive",
        "html": "\uf187;"
    }, {
        "class": "fa-area-chart",
        "html": "\uf1fe;"
    }, {
        "class": "fa-arrow-circle-down",
        "html": "\uf0ab;"
    }, {
        "class": "fa-arrow-circle-left",
        "html": "\uf0a8;"
    }, {
        "class": "fa-arrow-circle-o-down",
        "html": "\uf01a;"
    }, {
        "class": "fa-arrow-circle-o-left",
        "html": "\uf190;"
    }, {
        "class": "fa-arrow-circle-o-right",
        "html": "\uf18e;"
    }, {
        "class": "fa-arrow-circle-o-up",
        "html": "\uf01b;"
    }, {
        "class": "fa-arrow-circle-right",
        "html": "\uf0a9;"
    }, {
        "class": "fa-arrow-circle-up",
        "html": "\uf0aa;"
    }, {
        "class": "fa-arrow-down",
        "html": "\uf063;"
    }, {
        "class": "fa-arrow-left",
        "html": "\uf060;"
    }, {
        "class": "fa-arrow-right",
        "html": "\uf061;"
    }, {
        "class": "fa-arrow-up",
        "html": "\uf062;"
    }, {
        "class": "fa-arrows",
        "html": "\uf047;"
    }, {
        "class": "fa-arrows-alt",
        "html": "\uf0b2;"
    }, {
        "class": "fa-arrows-h",
        "html": "\uf07e;"
    }, {
        "class": "fa-arrows-v",
        "html": "\uf07d;"
    }, {
        "class": "fa-asl-interpreting",
        "html": "\uf2a3;"
    }, {
        "class": "fa-assistive-listening-systems",
        "html": "\uf2a2;"
    }, {
        "class": "fa-asterisk",
        "html": "\uf069;"
    }, {
        "class": "fa-at",
        "html": "\uf1fa;"
    }, {
        "class": "fa-audio-description",
        "html": "\uf29e;"
    }, {
        "class": "fa-automobile",
        "html": "\uf1b9;"
    }, {
        "class": "fa-backward",
        "html": "\uf04a;"
    }, {
        "class": "fa-balance-scale",
        "html": "\uf24e;"
    }, {
        "class": "fa-ban",
        "html": "\uf05e;"
    }, {
        "class": "fa-bandcamp",
        "html": "\uf2d5;"
    }, {
        "class": "fa-bank",
        "html": "\uf19c;"
    }, {
        "class": "fa-bar-chart",
        "html": "\uf080;"
    }, {
        "class": "fa-bar-chart-o",
        "html": "\uf080;"
    }, {
        "class": "fa-barcode",
        "html": "\uf02a;"
    }, {
        "class": "fa-bars",
        "html": "\uf0c9;"
    }, {
        "class": "fa-bath",
        "html": "\uf2cd;"
    }, {
        "class": "fa-bathtub",
        "html": "\uf2cd;"
    }, {
        "class": "fa-battery-0",
        "html": "\uf244;"
    }, {
        "class": "fa-battery-1",
        "html": "\uf243;"
    }, {
        "class": "fa-battery-2",
        "html": "\uf242;"
    }, {
        "class": "fa-battery-3",
        "html": "\uf241;"
    }, {
        "class": "fa-battery-4",
        "html": "\uf240;"
    }, {
        "class": "fa-battery-empty",
        "html": "\uf244;"
    }, {
        "class": "fa-battery-full",
        "html": "\uf240;"
    }, {
        "class": "fa-battery-half",
        "html": "\uf242;"
    }, {
        "class": "fa-battery-quarter",
        "html": "\uf243;"
    }, {
        "class": "fa-battery-three-quarters",
        "html": "\uf241;"
    }, {
        "class": "fa-bed",
        "html": "\uf236;"
    }, {
        "class": "fa-beer",
        "html": "\uf0fc;"
    }, {
        "class": "fa-behance",
        "html": "\uf1b4;"
    }, {
        "class": "fa-behance-square",
        "html": "\uf1b5;"
    }, {
        "class": "fa-bell",
        "html": "\uf0f3;"
    }, {
        "class": "fa-bell-o",
        "html": "\uf0a2;"
    }, {
        "class": "fa-bell-slash",
        "html": "\uf1f6;"
    }, {
        "class": "fa-bell-slash-o",
        "html": "\uf1f7;"
    }, {
        "class": "fa-bicycle",
        "html": "\uf206;"
    }, {
        "class": "fa-binoculars",
        "html": "\uf1e5;"
    }, {
        "class": "fa-birthday-cake",
        "html": "\uf1fd;"
    }, {
        "class": "fa-bitbucket",
        "html": "\uf171;"
    }, {
        "class": "fa-bitbucket-square",
        "html": "\uf172;"
    }, {
        "class": "fa-bitcoin",
        "html": "\uf15a;"
    }, {
        "class": "fa-black-tie",
        "html": "\uf27e;"
    }, {
        "class": "fa-blind",
        "html": "\uf29d;"
    }, {
        "class": "fa-bluetooth",
        "html": "\uf293;"
    }, {
        "class": "fa-bluetooth-b",
        "html": "\uf294;"
    }, {
        "class": "fa-bold",
        "html": "\uf032;"
    }, {
        "class": "fa-bolt",
        "html": "\uf0e7;"
    }, {
        "class": "fa-bomb",
        "html": "\uf1e2;"
    }, {
        "class": "fa-book",
        "html": "\uf02d;"
    }, {
        "class": "fa-bookmark",
        "html": "\uf02e;"
    }, {
        "class": "fa-bookmark-o",
        "html": "\uf097;"
    }, {
        "class": "fa-braille",
        "html": "\uf2a1;"
    }, {
        "class": "fa-briefcase",
        "html": "\uf0b1;"
    }, {
        "class": "fa-btc",
        "html": "\uf15a;"
    }, {
        "class": "fa-bug",
        "html": "\uf188;"
    }, {
        "class": "fa-building",
        "html": "\uf1ad;"
    }, {
        "class": "fa-building-o",
        "html": "\uf0f7;"
    }, {
        "class": "fa-bullhorn",
        "html": "\uf0a1;"
    }, {
        "class": "fa-bullseye",
        "html": "\uf140;"
    }, {
        "class": "fa-bus",
        "html": "\uf207;"
    }, {
        "class": "fa-buysellads",
        "html": "\uf20d;"
    }, {
        "class": "fa-cab",
        "html": "\uf1ba;"
    }, {
        "class": "fa-calculator",
        "html": "\uf1ec;"
    }, {
        "class": "fa-calendar",
        "html": "\uf073;"
    }, {
        "class": "fa-calendar-check-o",
        "html": "\uf274;"
    }, {
        "class": "fa-calendar-minus-o",
        "html": "\uf272;"
    }, {
        "class": "fa-calendar-o",
        "html": "\uf133;"
    }, {
        "class": "fa-calendar-plus-o",
        "html": "\uf271;"
    }, {
        "class": "fa-calendar-times-o",
        "html": "\uf273;"
    }, {
        "class": "fa-camera",
        "html": "\uf030;"
    }, {
        "class": "fa-camera-retro",
        "html": "\uf083;"
    }, {
        "class": "fa-car",
        "html": "\uf1b9;"
    }, {
        "class": "fa-caret-down",
        "html": "\uf0d7;"
    }, {
        "class": "fa-caret-left",
        "html": "\uf0d9;"
    }, {
        "class": "fa-caret-right",
        "html": "\uf0da;"
    }, {
        "class": "fa-caret-square-o-down",
        "html": "\uf150;"
    }, {
        "class": "fa-caret-square-o-left",
        "html": "\uf191;"
    }, {
        "class": "fa-caret-square-o-right",
        "html": "\uf152;"
    }, {
        "class": "fa-caret-square-o-up",
        "html": "\uf151;"
    }, {
        "class": "fa-caret-up",
        "html": "\uf0d8;"
    }, {
        "class": "fa-cart-arrow-down",
        "html": "\uf218;"
    }, {
        "class": "fa-cart-plus",
        "html": "\uf217;"
    }, {
        "class": "fa-cc",
        "html": "\uf20a;"
    }, {
        "class": "fa-cc-amex",
        "html": "\uf1f3;"
    }, {
        "class": "fa-cc-diners-club",
        "html": "\uf24c;"
    }, {
        "class": "fa-cc-discover",
        "html": "\uf1f2;"
    }, {
        "class": "fa-cc-jcb",
        "html": "\uf24b;"
    }, {
        "class": "fa-cc-mastercard",
        "html": "\uf1f1;"
    }, {
        "class": "fa-cc-paypal",
        "html": "\uf1f4;"
    }, {
        "class": "fa-cc-stripe",
        "html": "\uf1f5;"
    }, {
        "class": "fa-cc-visa",
        "html": "\uf1f0;"
    }, {
        "class": "fa-certificate",
        "html": "\uf0a3;"
    }, {
        "class": "fa-chain",
        "html": "\uf0c1;"
    }, {
        "class": "fa-chain-broken",
        "html": "\uf127;"
    }, {
        "class": "fa-check",
        "html": "\uf00c;"
    }, {
        "class": "fa-check-circle",
        "html": "\uf058;"
    }, {
        "class": "fa-check-circle-o",
        "html": "\uf05d;"
    }, {
        "class": "fa-check-square",
        "html": "\uf14a;"
    }, {
        "class": "fa-check-square-o",
        "html": "\uf046;"
    }, {
        "class": "fa-chevron-circle-down",
        "html": "\uf13a;"
    }, {
        "class": "fa-chevron-circle-left",
        "html": "\uf137;"
    }, {
        "class": "fa-chevron-circle-right",
        "html": "\uf138;"
    }, {
        "class": "fa-chevron-circle-up",
        "html": "\uf139;"
    }, {
        "class": "fa-chevron-down",
        "html": "\uf078;"
    }, {
        "class": "fa-chevron-left",
        "html": "\uf053;"
    }, {
        "class": "fa-chevron-right",
        "html": "\uf054;"
    }, {
        "class": "fa-chevron-up",
        "html": "\uf077;"
    }, {
        "class": "fa-child",
        "html": "\uf1ae;"
    }, {
        "class": "fa-chrome",
        "html": "\uf268;"
    }, {
        "class": "fa-circle",
        "html": "\uf111;"
    }, {
        "class": "fa-circle-o",
        "html": "\uf10c;"
    }, {
        "class": "fa-circle-o-notch",
        "html": "\uf1ce;"
    }, {
        "class": "fa-circle-thin",
        "html": "\uf1db;"
    }, {
        "class": "fa-clipboard",
        "html": "\uf0ea;"
    }, {
        "class": "fa-clock-o",
        "html": "\uf017;"
    }, {
        "class": "fa-clone",
        "html": "\uf24d;"
    }, {
        "class": "fa-close",
        "html": "\uf00d;"
    }, {
        "class": "fa-cloud",
        "html": "\uf0c2;"
    }, {
        "class": "fa-cloud-download",
        "html": "\uf0ed;"
    }, {
        "class": "fa-cloud-upload",
        "html": "\uf0ee;"
    }, {
        "class": "fa-cny",
        "html": "\uf157;"
    }, {
        "class": "fa-code",
        "html": "\uf121;"
    }, {
        "class": "fa-code-fork",
        "html": "\uf126;"
    }, {
        "class": "fa-codepen",
        "html": "\uf1cb;"
    }, {
        "class": "fa-codiepie",
        "html": "\uf284;"
    }, {
        "class": "fa-coffee",
        "html": "\uf0f4;"
    }, {
        "class": "fa-cog",
        "html": "\uf013;"
    }, {
        "class": "fa-cogs",
        "html": "\uf085;"
    }, {
        "class": "fa-columns",
        "html": "\uf0db;"
    }, {
        "class": "fa-comment",
        "html": "\uf075;"
    }, {
        "class": "fa-comment-o",
        "html": "\uf0e5;"
    }, {
        "class": "fa-comments",
        "html": "\uf086;"
    }, {
        "class": "fa-comments-o",
        "html": "\uf0e6;"
    }, {
        "class": "fa-commenting",
        "html": "\uf27a;"
    }, {
        "class": "fa-commenting-o",
        "html": "\uf27b;"
    }, {
        "class": "fa-compass",
        "html": "\uf14e;"
    }, {
        "class": "fa-compress",
        "html": "\uf066;"
    }, {
        "class": "fa-connectdevelop",
        "html": "\uf20e;"
    }, {
        "class": "fa-contao",
        "html": "\uf26d;"
    }, {
        "class": "fa-copy",
        "html": "\uf0c5;"
    }, {
        "class": "fa-copyright",
        "html": "\uf1f9;"
    }, {
        "class": "fa-creative-commons",
        "html": "\uf25e;"
    }, {
        "class": "fa-credit-card",
        "html": "\uf09d;"
    }, {
        "class": "fa-credit-card-alt",
        "html": "\uf283;"
    }, {
        "class": "fa-crop",
        "html": "\uf125;"
    }, {
        "class": "fa-crosshairs",
        "html": "\uf05b;"
    }, {
        "class": "fa-css3",
        "html": "\uf13c;"
    }, {
        "class": "fa-cube",
        "html": "\uf1b2;"
    }, {
        "class": "fa-cubes",
        "html": "\uf1b3;"
    }, {
        "class": "fa-cut",
        "html": "\uf0c4;"
    }, {
        "class": "fa-cutlery",
        "html": "\uf0f5;"
    }, {
        "class": "fa-dashboard",
        "html": "\uf0e4;"
    }, {
        "class": "fa-dashcube",
        "html": "\uf210;"
    }, {
        "class": "fa-database",
        "html": "\uf1c0;"
    }, {
        "class": "fa-deaf",
        "html": "\uf2a4;"
    }, {
        "class": "fa-deafness",
        "html": "\uf2a4;"
    }, {
        "class": "fa-dedent",
        "html": "\uf03b;"
    }, {
        "class": "fa-delicious",
        "html": "\uf1a5;"
    }, {
        "class": "fa-desktop",
        "html": "\uf108;"
    }, {
        "class": "fa-deviantart",
        "html": "\uf1bd;"
    }, {
        "class": "fa-diamond",
        "html": "\uf219;"
    }, {
        "class": "fa-digg",
        "html": "\uf1a6;"
    }, {
        "class": "fa-dollar",
        "html": "\uf155;"
    }, {
        "class": "fa-dot-circle-o",
        "html": "\uf192;"
    }, {
        "class": "fa-download",
        "html": "\uf019;"
    }, {
        "class": "fa-dribbble",
        "html": "\uf17d;"
    }, {
        "class": "fa-drivers-license",
        "html": "\uf2c2;"
    }, {
        "class": "fa-drivers-license-o",
        "html": "\uf2c3;"
    }, {
        "class": "fa-dropbox",
        "html": "\uf16b;"
    }, {
        "class": "fa-drupal",
        "html": "\uf1a9;"
    }, {
        "class": "fa-edge",
        "html": "\uf282;"
    }, {
        "class": "fa-edit",
        "html": "\uf044;"
    }, {
        "class": "fa-eercast",
        "html": "\uf2da;"
    }, {
        "class": "fa-eject",
        "html": "\uf052;"
    }, {
        "class": "fa-ellipsis-h",
        "html": "\uf141;"
    }, {
        "class": "fa-ellipsis-v",
        "html": "\uf142;"
    }, {
        "class": "fa-empire",
        "html": "\uf1d1;"
    }, {
        "class": "fa-envelope",
        "html": "\uf0e0;"
    }, {
        "class": "fa-envelope-o",
        "html": "\uf003;"
    }, {
        "class": "fa-envelope-open",
        "html": "\uf2b6;"
    }, {
        "class": "fa-envelope-open-o",
        "html": "\uf2b7;"
    }, {
        "class": "fa-envelope-square",
        "html": "\uf199;"
    }, {
        "class": "fa-envira",
        "html": "\uf299;"
    }, {
        "class": "fa-eraser",
        "html": "\uf12d;"
    }, {
        "class": "fa-etsy",
        "html": "\uf2d7;"
    }, {
        "class": "fa-eur",
        "html": "\uf153;"
    }, {
        "class": "fa-euro",
        "html": "\uf153;"
    }, {
        "class": "fa-exchange",
        "html": "\uf0ec;"
    }, {
        "class": "fa-exclamation",
        "html": "\uf12a;"
    }, {
        "class": "fa-exclamation-circle",
        "html": "\uf06a;"
    }, {
        "class": "fa-exclamation-triangle",
        "html": "\uf071;"
    }, {
        "class": "fa-expand",
        "html": "\uf065;"
    }, {
        "class": "fa-expeditedssl",
        "html": "\uf23e;"
    }, {
        "class": "fa-external-link",
        "html": "\uf08e;"
    }, {
        "class": "fa-external-link-square",
        "html": "\uf14c;"
    }, {
        "class": "fa-eye",
        "html": "\uf06e;"
    }, {
        "class": "fa-eye-slash",
        "html": "\uf070;"
    }, {
        "class": "fa-eyedropper",
        "html": "\uf1fb;"
    }, {
        "class": "fa-font-awesome",
        "html": "\uf2b4;"
    }, {
        "class": "fa-facebook",
        "html": "\uf09a;"
    }, {
        "class": "fa-facebook-f",
        "html": "\uf09a;"
    }, {
        "class": "fa-facebook-official",
        "html": "\uf230;"
    }, {
        "class": "fa-facebook-square",
        "html": "\uf082;"
    }, {
        "class": "fa-fast-backward",
        "html": "\uf049;"
    }, {
        "class": "fa-fast-forward",
        "html": "\uf050;"
    }, {
        "class": "fa-fax",
        "html": "\uf1ac;"
    }, {
        "class": "fa-feed",
        "html": "\uf09e;"
    }, {
        "class": "fa-female",
        "html": "\uf182;"
    }, {
        "class": "fa-fighter-jet",
        "html": "\uf0fb;"
    }, {
        "class": "fa-file",
        "html": "\uf15b;"
    }, {
        "class": "fa-file-archive-o",
        "html": "\uf1c6;"
    }, {
        "class": "fa-file-audio-o",
        "html": "\uf1c7;"
    }, {
        "class": "fa-file-code-o",
        "html": "\uf1c9;"
    }, {
        "class": "fa-file-excel-o",
        "html": "\uf1c3;"
    }, {
        "class": "fa-file-image-o",
        "html": "\uf1c5;"
    }, {
        "class": "fa-file-movie-o",
        "html": "\uf1c8;"
    }, {
        "class": "fa-file-o",
        "html": "\uf016;"
    }, {
        "class": "fa-file-pdf-o",
        "html": "\uf1c1;"
    }, {
        "class": "fa-file-photo-o",
        "html": "\uf1c5;"
    }, {
        "class": "fa-file-picture-o",
        "html": "\uf1c5;"
    }, {
        "class": "fa-file-powerpoint-o",
        "html": "\uf1c4;"
    }, {
        "class": "fa-file-sound-o",
        "html": "\uf1c7;"
    }, {
        "class": "fa-file-text",
        "html": "\uf15c;"
    }, {
        "class": "fa-file-text-o",
        "html": "\uf0f6;"
    }, {
        "class": "fa-file-video-o",
        "html": "\uf1c8;"
    }, {
        "class": "fa-file-word-o",
        "html": "\uf1c2;"
    }, {
        "class": "fa-file-zip-o",
        "html": "\uf1c6;"
    }, {
        "class": "fa-files-o",
        "html": "\uf0c5;"
    }, {
        "class": "fa-film",
        "html": "\uf008;"
    }, {
        "class": "fa-filter",
        "html": "\uf0b0;"
    }, {
        "class": "fa-fire",
        "html": "\uf06d;"
    }, {
        "class": "fa-fire-extinguisher",
        "html": "\uf134;"
    }, {
        "class": "fa-firefox",
        "html": "\uf269;"
    }, {
        "class": "fa-first-order",
        "html": "\uf2b0;"
    }, {
        "class": "fa-flag",
        "html": "\uf024;"
    }, {
        "class": "fa-flag-checkered",
        "html": "\uf11e;"
    }, {
        "class": "fa-flag-o",
        "html": "\uf11d;"
    }, {
        "class": "fa-flash",
        "html": "\uf0e7;"
    }, {
        "class": "fa-flask",
        "html": "\uf0c3;"
    }, {
        "class": "fa-flickr",
        "html": "\uf16e;"
    }, {
        "class": "fa-floppy-o",
        "html": "\uf0c7;"
    }, {
        "class": "fa-folder",
        "html": "\uf07b;"
    }, {
        "class": "fa-folder-o",
        "html": "\uf114;"
    }, {
        "class": "fa-folder-open",
        "html": "\uf07c;"
    }, {
        "class": "fa-folder-open-o",
        "html": "\uf115;"
    }, {
        "class": "fa-font",
        "html": "\uf031;"
    }, {
        "class": "fa-font-awesome",
        "html": "\uf2b4;"
    }, {
        "class": "fa-fonticons",
        "html": "\uf280;"
    }, {
        "class": "fa-fort-awesome",
        "html": "\uf286;"
    }, {
        "class": "fa-forumbee",
        "html": "\uf211;"
    }, {
        "class": "fa-forward",
        "html": "\uf04e;"
    }, {
        "class": "fa-foursquare",
        "html": "\uf180;"
    }, {
        "class": "fa-free-code-camp",
        "html": "\uf2c5;"
    }, {
        "class": "fa-frown-o",
        "html": "\uf119;"
    }, {
        "class": "fa-futbol-o",
        "html": "\uf1e3;"
    }, {
        "class": "fa-gamepad",
        "html": "\uf11b;"
    }, {
        "class": "fa-gavel",
        "html": "\uf0e3;"
    }, {
        "class": "fa-gbp",
        "html": "\uf154;"
    }, {
        "class": "fa-ge",
        "html": "\uf1d1;"
    }, {
        "class": "fa-gear",
        "html": "\uf013;"
    }, {
        "class": "fa-gears",
        "html": "\uf085;"
    }, {
        "class": "fa-genderless",
        "html": "\uf22d;"
    }, {
        "class": "fa-get-pocket",
        "html": "\uf265;"
    }, {
        "class": "fa-gg",
        "html": "\uf260;"
    }, {
        "class": "fa-gg-circle",
        "html": "\uf261;"
    }, {
        "class": "fa-gift",
        "html": "\uf06b;"
    }, {
        "class": "fa-git",
        "html": "\uf1d3;"
    }, {
        "class": "fa-git-square",
        "html": "\uf1d2;"
    }, {
        "class": "fa-github",
        "html": "\uf09b;"
    }, {
        "class": "fa-github-alt",
        "html": "\uf113;"
    }, {
        "class": "fa-github-square",
        "html": "\uf092;"
    }, {
        "class": "fa-gitlab",
        "html": "\uf296;"
    }, {
        "class": "fa-gittip",
        "html": "\uf184;"
    }, {
        "class": "fa-glass",
        "html": "\uf000;"
    }, {
        "class": "fa-glide",
        "html": "\uf2a5;"
    }, {
        "class": "fa-glide-g",
        "html": "\uf2a6;"
    }, {
        "class": "fa-globe",
        "html": "\uf0ac;"
    }, {
        "class": "fa-google",
        "html": "\uf1a0;"
    }, {
        "class": "fa-google-plus",
        "html": "\uf0d5;"
    }, {
        "class": "fa-google-plus-circle",
        "html": "\uf2b3;"
    }, {
        "class": "fa-google-plus-official",
        "html": "\uf2b3;"
    }, {
        "class": "fa-google-plus-square",
        "html": "\uf0d4;"
    }, {
        "class": "fa-google-wallet",
        "html": "\uf1ee;"
    }, {
        "class": "fa-graduation-cap",
        "html": "\uf19d;"
    }, {
        "class": "fa-gratipay",
        "html": "\uf184;"
    }, {
        "class": "fa-grav",
        "html": "\uf2d6;"
    }, {
        "class": "fa-group",
        "html": "\uf0c0;"
    }, {
        "class": "fa-h-square",
        "html": "\uf0fd;"
    }, {
        "class": "fa-hacker-news",
        "html": "\uf1d4;"
    }, {
        "class": "fa-hand-grab-o",
        "html": "\uf255;"
    }, {
        "class": "fa-hand-lizard-o",
        "html": "\uf258;"
    }, {
        "class": "fa-hand-o-down",
        "html": "\uf0a7;"
    }, {
        "class": "fa-hand-o-left",
        "html": "\uf0a5;"
    }, {
        "class": "fa-hand-o-right",
        "html": "\uf0a4;"
    }, {
        "class": "fa-hand-o-up",
        "html": "\uf0a6;"
    }, {
        "class": "fa-hand-paper-o",
        "html": "\uf256;"
    }, {
        "class": "fa-hand-peace-o",
        "html": "\uf25b;"
    }, {
        "class": "fa-hand-pointer-o",
        "html": "\uf25a;"
    }, {
        "class": "fa-hand-rock-o",
        "html": "\uf255;"
    }, {
        "class": "fa-hand-scissors-o",
        "html": "\uf257;"
    }, {
        "class": "fa-hand-spock-o",
        "html": "\uf259;"
    }, {
        "class": "fa-hand-stop-o",
        "html": "\uf256;"
    }, {
        "class": "fa-handshake-o",
        "html": "\uf2b5;"
    }, {
        "class": "fa-hard-of-hearing",
        "html": "\uf2a4;"
    }, {
        "class": "fa-hashtag",
        "html": "\uf292;"
    }, {
        "class": "fa-hdd-o",
        "html": "\uf0a0;"
    }, {
        "class": "fa-header",
        "html": "\uf1dc;"
    }, {
        "class": "fa-headphones",
        "html": "\uf025;"
    }, {
        "class": "fa-heart",
        "html": "\uf004;"
    }, {
        "class": "fa-heart-o",
        "html": "\uf08a;"
    }, {
        "class": "fa-heartbeat",
        "html": "\uf21e;"
    }, {
        "class": "fa-history",
        "html": "\uf1da;"
    }, {
        "class": "fa-home",
        "html": "\uf015;"
    }, {
        "class": "fa-hospital-o",
        "html": "\uf0f8;"
    }, {
        "class": "fa-hotel",
        "html": "\uf236;"
    }, {
        "class": "fa-hourglass",
        "html": "\uf254;"
    }, {
        "class": "fa-hourglass-1",
        "html": "\uf251;"
    }, {
        "class": "fa-hourglass-2",
        "html": "\uf252;"
    }, {
        "class": "fa-hourglass-3",
        "html": "\uf253;"
    }, {
        "class": "fa-hourglass-end",
        "html": "\uf253;"
    }, {
        "class": "fa-hourglass-half",
        "html": "\uf252;"
    }, {
        "class": "fa-hourglass-o",
        "html": "\uf250;"
    }, {
        "class": "fa-hourglass-start",
        "html": "\uf251;"
    }, {
        "class": "fa-houzz",
        "html": "\uf27c;"
    }, {
        "class": "fa-html5",
        "html": "\uf13b;"
    }, {
        "class": "fa-i-cursor",
        "html": "\uf246;"
    }, {
        "class": "fa-id-badge",
        "html": "\uf2c1;"
    }, {
        "class": "fa-id-card",
        "html": "\uf2c2;"
    }, {
        "class": "fa-id-card-o",
        "html": "\uf2c3;"
    }, {
        "class": "fa-ils",
        "html": "\uf20b;"
    }, {
        "class": "fa-image",
        "html": "\uf03e;"
    }, {
        "class": "fa-imdb",
        "html": "\uf2d8;"
    }, {
        "class": "fa-inbox",
        "html": "\uf01c;"
    }, {
        "class": "fa-indent",
        "html": "\uf03c;"
    }, {
        "class": "fa-industry",
        "html": "\uf275;"
    }, {
        "class": "fa-info",
        "html": "\uf129;"
    }, {
        "class": "fa-info-circle",
        "html": "\uf05a;"
    }, {
        "class": "fa-inr",
        "html": "\uf156;"
    }, {
        "class": "fa-instagram",
        "html": "\uf16d;"
    }, {
        "class": "fa-institution",
        "html": "\uf19c;"
    }, {
        "class": "fa-internet-explorer",
        "html": "\uf26b;"
    }, {
        "class": "fa-intersex",
        "html": "\uf224;"
    }, {
        "class": "fa-ioxhost",
        "html": "\uf208;"
    }, {
        "class": "fa-italic",
        "html": "\uf033;"
    }, {
        "class": "fa-joomla",
        "html": "\uf1aa;"
    }, {
        "class": "fa-jpy",
        "html": "\uf157;"
    }, {
        "class": "fa-jsfiddle",
        "html": "\uf1cc;"
    }, {
        "class": "fa-key",
        "html": "\uf084;"
    }, {
        "class": "fa-keyboard-o",
        "html": "\uf11c;"
    }, {
        "class": "fa-krw",
        "html": "\uf159;"
    }, {
        "class": "fa-language",
        "html": "\uf1ab;"
    }, {
        "class": "fa-laptop",
        "html": "\uf109;"
    }, {
        "class": "fa-lastfm",
        "html": "\uf202;"
    }, {
        "class": "fa-lastfm-square",
        "html": "\uf203;"
    }, {
        "class": "fa-leaf",
        "html": "\uf06c;"
    }, {
        "class": "fa-leanpub",
        "html": "\uf212;"
    }, {
        "class": "fa-legal",
        "html": "\uf0e3;"
    }, {
        "class": "fa-lemon-o",
        "html": "\uf094;"
    }, {
        "class": "fa-level-down",
        "html": "\uf149;"
    }, {
        "class": "fa-level-up",
        "html": "\uf148;"
    }, {
        "class": "fa-life-bouy",
        "html": "\uf1cd;"
    }, {
        "class": "fa-life-buoy",
        "html": "\uf1cd;"
    }, {
        "class": "fa-life-ring",
        "html": "\uf1cd;"
    }, {
        "class": "fa-life-saver",
        "html": "\uf1cd;"
    }, {
        "class": "fa-lightbulb-o",
        "html": "\uf0eb;"
    }, {
        "class": "fa-line-chart",
        "html": "\uf201;"
    }, {
        "class": "fa-link",
        "html": "\uf0c1;"
    }, {
        "class": "fa-linkedin",
        "html": "\uf0e1;"
    }, {
        "class": "fa-linkedin-square",
        "html": "\uf08c;"
    }, {
        "class": "fa-linode",
        "html": "\uf2b8"
    }, {
        "class": "fa-linux",
        "html": "\uf17c"
    }, {
        "class": "fa-list",
        "html": "\uf03a;"
    }, {
        "class": "fa-list-alt",
        "html": "\uf022;"
    }, {
        "class": "fa-list-ol",
        "html": "\uf0cb;"
    }, {
        "class": "fa-list-ul",
        "html": "\uf0ca;"
    }, {
        "class": "fa-location-arrow",
        "html": "\uf124;"
    }, {
        "class": "fa-lock",
        "html": "\uf023;"
    }, {
        "class": "fa-long-arrow-down",
        "html": "\uf175;"
    }, {
        "class": "fa-long-arrow-left",
        "html": "\uf177;"
    }, {
        "class": "fa-long-arrow-right",
        "html": "\uf178;"
    }, {
        "class": "fa-long-arrow-up",
        "html": "\uf176;"
    }, {
        "class": "fa-low-vision",
        "html": "\uf2a8;"
    }, {
        "class": "fa-magic",
        "html": "\uf0d0;"
    }, {
        "class": "fa-magnet",
        "html": "\uf076;"
    }, {
        "class": "fa-mail-forward",
        "html": "\uf064;"
    }, {
        "class": "fa-mail-reply",
        "html": "\uf112;"
    }, {
        "class": "fa-mail-reply-all",
        "html": "\uf122;"
    }, {
        "class": "fa-male",
        "html": "\uf183;"
    }, {
        "class": "fa-map",
        "html": "\uf279;"
    }, {
        "class": "fa-map-marker",
        "html": "\uf041;"
    }, {
        "class": "fa-map-o",
        "html": "\uf278;"
    }, {
        "class": "fa-map-pin",
        "html": "\uf276;"
    }, {
        "class": "fa-map-signs",
        "html": "\uf277;"
    }, {
        "class": "fa-mars",
        "html": "\uf222;"
    }, {
        "class": "fa-mars-double",
        "html": "\uf227;"
    }, {
        "class": "fa-mars-stroke",
        "html": "\uf229;"
    }, {
        "class": "fa-mars-stroke-h",
        "html": "\uf22b;"
    }, {
        "class": "fa-mars-stroke-v",
        "html": "\uf22a;"
    }, {
        "class": "fa-maxcdn",
        "html": "\uf136;"
    }, {
        "class": "fa-meanpath",
        "html": "\uf20c;"
    }, {
        "class": "fa-medium",
        "html": "\uf23a;"
    }, {
        "class": "fa-medkit",
        "html": "\uf0fa;"
    }, {
        "class": "fa-meetup",
        "html": "\uf2e0;"
    }, {
        "class": "fa-meh-o",
        "html": "\uf11a;"
    }, {
        "class": "fa-mercury",
        "html": "\uf223;"
    }, {
        "class": "fa-microchip",
        "html": "\uf2db;"
    }, {
        "class": "fa-microphone",
        "html": "\uf130;"
    }, {
        "class": "fa-microphone-slash",
        "html": "\uf131;"
    }, {
        "class": "fa-minus",
        "html": "\uf068;"
    }, {
        "class": "fa-minus-circle",
        "html": "\uf056;"
    }, {
        "class": "fa-minus-square",
        "html": "\uf146;"
    }, {
        "class": "fa-minus-square-o",
        "html": "\uf147;"
    }, {
        "class": "fa-mixcloud",
        "html": "\uf289;"
    }, {
        "class": "fa-mobile",
        "html": "\uf10b;"
    }, {
        "class": "fa-mobile-phone",
        "html": "\uf10b;"
    }, {
        "class": "fa-modx",
        "html": "\uf285;"
    }, {
        "class": "fa-money",
        "html": "\uf0d6;"
    }, {
        "class": "fa-moon-o",
        "html": "\uf186;"
    }, {
        "class": "fa-mortar-board",
        "html": "\uf19d;"
    }, {
        "class": "fa-motorcycle",
        "html": "\uf21c;"
    }, {
        "class": "fa-mouse-pointer",
        "html": "\uf245;"
    }, {
        "class": "fa-music",
        "html": "\uf001;"
    }, {
        "class": "fa-navicon",
        "html": "\uf0c9;"
    }, {
        "class": "fa-neuter",
        "html": "\uf22c;"
    }, {
        "class": "fa-newspaper-o",
        "html": "\uf1ea;"
    }, {
        "class": "fa-object-group",
        "html": "\uf247;"
    }, {
        "class": "fa-object-ungroup",
        "html": "\uf248;"
    }, {
        "class": "fa-odnoklassniki",
        "html": "\uf263;"
    }, {
        "class": "fa-odnoklassniki-square",
        "html": "\uf264;"
    }, {
        "class": "fa-opencart",
        "html": "\uf23d;"
    }, {
        "class": "fa-openid",
        "html": "\uf19b;"
    }, {
        "class": "fa-opera",
        "html": "\uf26a;"
    }, {
        "class": "fa-optin-monster",
        "html": "\uf23c;"
    }, {
        "class": "fa-outdent",
        "html": "\uf03b;"
    }, {
        "class": "fa-paint-brush",
        "html": "\uf1fc;"
    }, {
        "class": "fa-pagelines",
        "html": "\uf18c;"
    }, {
        "class": "fa-paper-plane",
        "html": "\uf1d8;"
    }, {
        "class": "fa-paper-plane-o",
        "html": "\uf1d9;"
    }, {
        "class": "fa-paperclip",
        "html": "\uf0c6;"
    }, {
        "class": "fa-paragraph",
        "html": "\uf1dd;"
    }, {
        "class": "fa-paste",
        "html": "\uf0ea;"
    }, {
        "class": "fa-pause",
        "html": "\uf04c;"
    }, {
        "class": "fa-pause-circle",
        "html": "\uf28b;"
    }, {
        "class": "fa-pause-circle-o",
        "html": "\uf28c;"
    }, {
        "class": "fa-paw",
        "html": "\uf1b0;"
    }, {
        "class": "fa-paypal",
        "html": "\uf1ed;"
    }, {
        "class": "fa-pencil",
        "html": "\uf040;"
    }, {
        "class": "fa-pencil-square",
        "html": "\uf14b;"
    }, {
        "class": "fa-pencil-square-o",
        "html": "\uf044;"
    }, {
        "class": "fa-percent",
        "html": "\uf295;"
    }, {
        "class": "fa-phone",
        "html": "\uf095;"
    }, {
        "class": "fa-phone-square",
        "html": "\uf098;"
    }, {
        "class": "fa-photo",
        "html": "\uf03e;"
    }, {
        "class": "fa-picture-o",
        "html": "\uf03e;"
    }, {
        "class": "fa-pie-chart",
        "html": "\uf200;"
    }, {
        "class": "fa-pied-piper",
        "html": "\uf2ae;"
    }, {
        "class": "fa-pied-piper-alt",
        "html": "\uf1a8;"
    }, {
        "class": "fa-pied-piper-pp",
        "html": "\uf1a7;"
    }, {
        "class": "fa-pinterest",
        "html": "\uf0d2;"
    }, {
        "class": "fa-pinterest-p",
        "html": "\uf231;"
    }, {
        "class": "fa-pinterest-square",
        "html": "\uf0d3;"
    }, {
        "class": "fa-plane",
        "html": "\uf072;"
    }, {
        "class": "fa-play",
        "html": "\uf04b;"
    }, {
        "class": "fa-play-circle",
        "html": "\uf144;"
    }, {
        "class": "fa-play-circle-o",
        "html": "\uf01d;"
    }, {
        "class": "fa-plug",
        "html": "\uf1e6;"
    }, {
        "class": "fa-plus",
        "html": "\uf067;"
    }, {
        "class": "fa-plus-circle",
        "html": "\uf055;"
    }, {
        "class": "fa-plus-square",
        "html": "\uf0fe;"
    }, {
        "class": "fa-plus-square-o",
        "html": "\uf196;"
    }, {
        "class": "fa-podcast",
        "html": "\uf2ce;"
    }, {
        "class": "fa-power-off",
        "html": "\uf011;"
    }, {
        "class": "fa-print",
        "html": "\uf02f;"
    }, {
        "class": "fa-product-hunt",
        "html": "\uf288;"
    }, {
        "class": "fa-puzzle-piece",
        "html": "\uf12e;"
    }, {
        "class": "fa-qq",
        "html": "\uf1d6;"
    }, {
        "class": "fa-qrcode",
        "html": "\uf029;"
    }, {
        "class": "fa-question",
        "html": "\uf128;"
    }, {
        "class": "fa-question-circle",
        "html": "\uf059;"
    }, {
        "class": "fa-question-circle-o",
        "html": "\uf29c;"
    }, {
        "class": "fa-quora",
        "html": "\uf2c4;"
    }, {
        "class": "fa-quote-left",
        "html": "\uf10d;"
    }, {
        "class": "fa-quote-right",
        "html": "\uf10e;"
    }, {
        "class": "fa-ra",
        "html": "\uf1d0;"
    }, {
        "class": "fa-random",
        "html": "\uf074;"
    }, {
        "class": "fa-ravelry",
        "html": "\uf2d9;"
    }, {
        "class": "fa-rebel",
        "html": "\uf1d0;"
    }, {
        "class": "fa-recycle",
        "html": "\uf1b8;"
    }, {
        "class": "fa-reddit",
        "html": "\uf1a1;"
    }, {
        "class": "fa-reddit-alien",
        "html": "\uf281;"
    }, {
        "class": "fa-reddit-square",
        "html": "\uf1a2;"
    }, {
        "class": "fa-refresh",
        "html": "\uf021;"
    }, {
        "class": "fa-registered",
        "html": "\uf25d;"
    }, {
        "class": "fa-remove",
        "html": "\uf00d;"
    }, {
        "class": "fa-renren",
        "html": "\uf18b;"
    }, {
        "class": "fa-reorder",
        "html": "\uf0c9;"
    }, {
        "class": "fa-repeat",
        "html": "\uf01e;"
    }, {
        "class": "fa-reply",
        "html": "\uf112;"
    }, {
        "class": "fa-reply-all",
        "html": "\uf122;"
    }, {
        "class": "fa-resistance",
        "html": "\uf1d0;"
    }, {
        "class": "fa-retweet",
        "html": "\uf079;"
    }, {
        "class": "fa-rmb",
        "html": "\uf157;"
    }, {
        "class": "fa-road",
        "html": "\uf018;"
    }, {
        "class": "fa-rocket",
        "html": "\uf135;"
    }, {
        "class": "fa-rotate-left",
        "html": "\uf0e2;"
    }, {
        "class": "fa-rotate-right",
        "html": "\uf01e;"
    }, {
        "class": "fa-rouble",
        "html": "\uf158;"
    }, {
        "class": "fa-rss",
        "html": "\uf09e;"
    }, {
        "class": "fa-rss-square",
        "html": "\uf143;"
    }, {
        "class": "fa-rub",
        "html": "\uf158;"
    }, {
        "class": "fa-ruble",
        "html": "\uf158;"
    }, {
        "class": "fa-rupee",
        "html": "\uf156;"
    }, {
        "class": "fa-s15",
        "html": "\uf2cd;"
    }, {
        "class": "fa-safari",
        "html": "\uf267;"
    }, {
        "class": "fa-save",
        "html": "\uf0c7;"
    }, {
        "class": "fa-scissors",
        "html": "\uf0c4;"
    }, {
        "class": "fa-scribd",
        "html": "\uf28a;"
    }, {
        "class": "fa-search",
        "html": "\uf002;"
    }, {
        "class": "fa-search-minus",
        "html": "\uf010;"
    }, {
        "class": "fa-search-plus",
        "html": "\uf00e;"
    }, {
        "class": "fa-sellsy",
        "html": "\uf213;"
    }, {
        "class": "fa-send",
        "html": "\uf1d8;"
    }, {
        "class": "fa-send-o",
        "html": "\uf1d9;"
    }, {
        "class": "fa-server",
        "html": "\uf233;"
    }, {
        "class": "fa-share",
        "html": "\uf064;"
    }, {
        "class": "fa-share-alt",
        "html": "\uf1e0;"
    }, {
        "class": "fa-share-alt-square",
        "html": "\uf1e1;"
    }, {
        "class": "fa-share-square",
        "html": "\uf14d;"
    }, {
        "class": "fa-share-square-o",
        "html": "\uf045;"
    }, {
        "class": "fa-shekel",
        "html": "\uf20b;"
    }, {
        "class": "fa-sheqel",
        "html": "\uf20b;"
    }, {
        "class": "fa-shield",
        "html": "\uf132;"
    }, {
        "class": "fa-ship",
        "html": "\uf21a;"
    }, {
        "class": "fa-shirtsinbulk",
        "html": "\uf214;"
    }, {
        "class": "fa-shopping-bag",
        "html": "\uf290;"
    }, {
        "class": "fa-shopping-basket",
        "html": "\uf291;"
    }, {
        "class": "fa-shopping-cart",
        "html": "\uf07a;"
    }, {
        "class": "fa-shower",
        "html": "\uf2cc;"
    }, {
        "class": "fa-sign-in",
        "html": "\uf090;"
    }, {
        "class": "fa-sign-language",
        "html": "\uf2a7;"
    }, {
        "class": "fa-sign-out",
        "html": "\uf08b;"
    }, {
        "class": "fa-signal",
        "html": "\uf012;"
    }, {
        "class": "fa-signing",
        "html": "\uf2a7;"
    }, {
        "class": "fa-simplybuilt",
        "html": "\uf215;"
    }, {
        "class": "fa-sitemap",
        "html": "\uf0e8;"
    }, {
        "class": "fa-skyatlas",
        "html": "\uf216;"
    }, {
        "class": "fa-skype",
        "html": "\uf17e;"
    }, {
        "class": "fa-slack",
        "html": "\uf198;"
    }, {
        "class": "fa-sliders",
        "html": "\uf1de;"
    }, {
        "class": "fa-slideshare",
        "html": "\uf1e7;"
    }, {
        "class": "fa-smile-o",
        "html": "\uf118;"
    }, {
        "class": "fa-snapchat",
        "html": "\uf2ab;"
    }, {
        "class": "fa-snapchat-ghost",
        "html": "\uf2ac;"
    }, {
        "class": "fa-snapchat-square",
        "html": "\uf2ad;"
    }, {
        "class": "fa-snowflake-o",
        "html": "\uf2dc;"
    }, {
        "class": "fa-soccer-ball-o",
        "html": "\uf1e3;"
    }, {
        "class": "fa-sort",
        "html": "\uf0dc;"
    }, {
        "class": "fa-sort-alpha-asc",
        "html": "\uf15d;"
    }, {
        "class": "fa-sort-alpha-desc",
        "html": "\uf15e;"
    }, {
        "class": "fa-sort-amount-asc",
        "html": "\uf160;"
    }, {
        "class": "fa-sort-amount-desc",
        "html": "\uf161;"
    }, {
        "class": "fa-sort-asc",
        "html": "\uf0de;"
    }, {
        "class": "fa-sort-desc",
        "html": "\uf0dd;"
    }, {
        "class": "fa-sort-down",
        "html": "\uf0dd;"
    }, {
        "class": "fa-sort-numeric-asc",
        "html": "\uf162;"
    }, {
        "class": "fa-sort-numeric-desc",
        "html": "\uf163;"
    }, {
        "class": "fa-sort-up",
        "html": "\uf0de;"
    }, {
        "class": "fa-soundcloud",
        "html": "\uf1be;"
    }, {
        "class": "fa-space-shuttle",
        "html": "\uf197;"
    }, {
        "class": "fa-spinner",
        "html": "\uf110;"
    }, {
        "class": "fa-spoon",
        "html": "\uf1b1;"
    }, {
        "class": "fa-spotify",
        "html": "\uf1bc;"
    }, {
        "class": "fa-square",
        "html": "\uf0c8;"
    }, {
        "class": "fa-square-o",
        "html": "\uf096;"
    }, {
        "class": "fa-stack-exchange",
        "html": "\uf18d;"
    }, {
        "class": "fa-stack-overflow",
        "html": "\uf16c;"
    }, {
        "class": "fa-star",
        "html": "\uf005;"
    }, {
        "class": "fa-star-half",
        "html": "\uf089;"
    }, {
        "class": "fa-star-half-empty",
        "html": "\uf123;"
    }, {
        "class": "fa-star-half-full",
        "html": "\uf123;"
    }, {
        "class": "fa-star-half-o",
        "html": "\uf123;"
    }, {
        "class": "fa-star-o",
        "html": "\uf006;"
    }, {
        "class": "fa-steam",
        "html": "\uf1b6;"
    }, {
        "class": "fa-steam-square",
        "html": "\uf1b7;"
    }, {
        "class": "fa-step-backward",
        "html": "\uf048;"
    }, {
        "class": "fa-step-forward",
        "html": "\uf051;"
    }, {
        "class": "fa-stethoscope",
        "html": "\uf0f1;"
    }, {
        "class": "fa-sticky-note",
        "html": "\uf249;"
    }, {
        "class": "fa-sticky-note-o",
        "html": "\uf24a;"
    }, {
        "class": "fa-stop",
        "html": "\uf04d;"
    }, {
        "class": "fa-stop-circle",
        "html": "\uf28d;"
    }, {
        "class": "fa-stop-circle-o",
        "html": "\uf28e;"
    }, {
        "class": "fa-street-view",
        "html": "\uf21d;"
    }, {
        "class": "fa-strikethrough",
        "html": "\uf0cc;"
    }, {
        "class": "fa-stumbleupon",
        "html": "\uf1a4;"
    }, {
        "class": "fa-stumbleupon-circle",
        "html": "\uf1a3;"
    }, {
        "class": "fa-subscript",
        "html": "\uf12c;"
    }, {
        "class": "fa-subway",
        "html": "\uf239;"
    }, {
        "class": "fa-suitcase",
        "html": "\uf0f2;"
    }, {
        "class": "fa-sun-o",
        "html": "\uf185;"
    }, {
        "class": "fa-superpowers",
        "html": "\uf2dd;"
    }, {
        "class": "fa-superscript",
        "html": "\uf12b;"
    }, {
        "class": "fa-support",
        "html": "\uf1cd;"
    }, {
        "class": "fa-table",
        "html": "\uf0ce;"
    }, {
        "class": "fa-tablet",
        "html": "\uf10a;"
    }, {
        "class": "fa-tachometer",
        "html": "\uf0e4;"
    }, {
        "class": "fa-tag",
        "html": "\uf02b;"
    }, {
        "class": "fa-tags",
        "html": "\uf02c;"
    }, {
        "class": "fa-tasks",
        "html": "\uf0ae;"
    }, {
        "class": "fa-taxi",
        "html": "\uf1ba;"
    }, {
        "class": "fa-telegram",
        "html": "\uf2c6;"
    }, {
        "class": "fa-television",
        "html": "\uf26c;"
    }, {
        "class": "fa-tencent-weibo",
        "html": "\uf1d5;"
    }, {
        "class": "fa-terminal",
        "html": "\uf120;"
    }, {
        "class": "fa-text-height",
        "html": "\uf034;"
    }, {
        "class": "fa-text-width",
        "html": "\uf035;"
    }, {
        "class": "fa-th",
        "html": "\uf00a;"
    }, {
        "class": "fa-th-large",
        "html": "\uf009;"
    }, {
        "class": "fa-th-list",
        "html": "\uf00b;"
    }, {
        "class": "fa-themeisle",
        "html": "\uf2b2;"
    }, {
        "class": "fa-thermometer",
        "html": "\uf2c7;"
    }, {
        "class": "fa-thermometer-0",
        "html": "\uf2cb;"
    }, {
        "class": "fa-thermometer-1",
        "html": "\uf2ca;"
    }, {
        "class": "fa-thermometer-2",
        "html": "\uf2c9;"
    }, {
        "class": "fa-thermometer-3",
        "html": "\uf2c8;"
    }, {
        "class": "fa-thermometer-4",
        "html": "\uf2c7;"
    }, {
        "class": "fa-thermometer-empty",
        "html": "\uf2cb;"
    }, {
        "class": "fa-thermometer-full",
        "html": "\uf2c7;"
    }, {
        "class": "fa-thermometer-half",
        "html": "\uf2c9;"
    }, {
        "class": "fa-thermometer-quarter",
        "html": "\uf2ca;"
    }, {
        "class": "fa-thermometer-three-quarters",
        "html": "\uf2c8;"
    }, {
        "class": "fa-thumb-tack",
        "html": "\uf08d;"
    }, {
        "class": "fa-thumbs-down",
        "html": "\uf165;"
    }, {
        "class": "fa-thumbs-o-down",
        "html": "\uf088;"
    }, {
        "class": "fa-thumbs-o-up",
        "html": "\uf087;"
    }, {
        "class": "fa-thumbs-up",
        "html": "\uf164;"
    }, {
        "class": "fa-ticket",
        "html": "\uf145;"
    }, {
        "class": "fa-times",
        "html": "\uf00d;"
    }, {
        "class": "fa-times-circle",
        "html": "\uf057;"
    }, {
        "class": "fa-times-circle-o",
        "html": "\uf05c;"
    }, {
        "class": "fa-times-rectangle",
        "html": "\uf2d3;"
    }, {
        "class": "fa-times-rectangle-o",
        "html": "\uf2d4;"
    }, {
        "class": "fa-tint",
        "html": "\uf043;"
    }, {
        "class": "fa-toggle-down",
        "html": "\uf150;"
    }, {
        "class": "fa-toggle-left",
        "html": "\uf191;"
    }, {
        "class": "fa-toggle-off",
        "html": "\uf204;"
    }, {
        "class": "fa-toggle-on",
        "html": "\uf205;"
    }, {
        "class": "fa-toggle-right",
        "html": "\uf152;"
    }, {
        "class": "fa-toggle-up",
        "html": "\uf151;"
    }, {
        "class": "fa-trademark",
        "html": "\uf25c;"
    }, {
        "class": "fa-train",
        "html": "\uf238;"
    }, {
        "class": "fa-transgender",
        "html": "\uf224;"
    }, {
        "class": "fa-transgender-alt",
        "html": "\uf225;"
    }, {
        "class": "fa-trash",
        "html": "\uf1f8;"
    }, {
        "class": "fa-trash-o",
        "html": "\uf014;"
    }, {
        "class": "fa-tree",
        "html": "\uf1bb;"
    }, {
        "class": "fa-trello",
        "html": "\uf181;"
    }, {
        "class": "fa-tripadvisor",
        "html": "\uf262;"
    }, {
        "class": "fa-trophy",
        "html": "\uf091;"
    }, {
        "class": "fa-truck",
        "html": "\uf0d1;"
    }, {
        "class": "fa-try",
        "html": "\uf195;"
    }, {
        "class": "fa-tty",
        "html": "\uf1e4;"
    }, {
        "class": "fa-tumblr",
        "html": "\uf173;"
    }, {
        "class": "fa-tumblr-square",
        "html": "\uf174;"
    }, {
        "class": "fa-turkish-lira",
        "html": "\uf195;"
    }, {
        "class": "fa-tv",
        "html": "\uf26c;"
    }, {
        "class": "fa-twitch",
        "html": "\uf1e8;"
    }, {
        "class": "fa-twitter",
        "html": "\uf099;"
    }, {
        "class": "fa-twitter-square",
        "html": "\uf081;"
    }, {
        "class": "fa-umbrella",
        "html": "\uf0e9;"
    }, {
        "class": "fa-underline",
        "html": "\uf0cd;"
    }, {
        "class": "fa-undo",
        "html": "\uf0e2;"
    }, {
        "class": "fa-universal-access",
        "html": "\uf29a;"
    }, {
        "class": "fa-university",
        "html": "\uf19c;"
    }, {
        "class": "fa-unlink",
        "html": "\uf127;"
    }, {
        "class": "fa-unlock",
        "html": "\uf09c;"
    }, {
        "class": "fa-unlock-alt",
        "html": "\uf13e;"
    }, {
        "class": "fa-unsorted",
        "html": "\uf0dc;"
    }, {
        "class": "fa-upload",
        "html": "\uf093;"
    }, {
        "class": "fa-usb",
        "html": "\uf287;"
    }, {
        "class": "fa-usd",
        "html": "\uf155;"
    }, {
        "class": "fa-user",
        "html": "\uf007;"
    }, {
        "class": "fa-user-circle",
        "html": "\uf2bd;"
    }, {
        "class": "fa-user-circle-o",
        "html": "\uf2be;"
    }, {
        "class": "fa-user-md",
        "html": "\uf0f0;"
    }, {
        "class": "fa-user-o",
        "html": "\uf2c0;"
    }, {
        "class": "fa-user-plus",
        "html": "\uf234;"
    }, {
        "class": "fa-user-secret",
        "html": "\uf21b;"
    }, {
        "class": "fa-user-times",
        "html": "\uf235;"
    }, {
        "class": "fa-users",
        "html": "\uf0c0;"
    }, {
        "class": "fa-vcard",
        "html": "\uf2bb;"
    }, {
        "class": "fa-vcard-o",
        "html": "\uf2bc;"
    }, {
        "class": "fa-venus",
        "html": "\uf221;"
    }, {
        "class": "fa-venus-double",
        "html": "\uf226;"
    }, {
        "class": "fa-venus-mars",
        "html": "\uf228;"
    }, {
        "class": "fa-viacoin",
        "html": "\uf237;"
    }, {
        "class": "fa-viadeo",
        "html": "\uf2a9;"
    }, {
        "class": "fa-viadeo-square",
        "html": "\uf2aa;"
    }, {
        "class": "fa-video-camera",
        "html": "\uf03d;"
    }, {
        "class": "fa-vimeo",
        "html": "\uf27d;"
    }, {
        "class": "fa-vimeo-square",
        "html": "\uf194;"
    }, {
        "class": "fa-vine",
        "html": "\uf1ca;"
    }, {
        "class": "fa-vk",
        "html": "\uf189;"
    }, {
        "class": "fa-volume-control-phone",
        "html": "\uf2a0;"
    }, {
        "class": "fa-volume-down",
        "html": "\uf027;"
    }, {
        "class": "fa-volume-off",
        "html": "\uf026;"
    }, {
        "class": "fa-volume-up",
        "html": "\uf028;"
    }, {
        "class": "fa-warning",
        "html": "\uf071;"
    }, {
        "class": "fa-wechat",
        "html": "\uf1d7;"
    }, {
        "class": "fa-weibo",
        "html": "\uf18a;"
    }, {
        "class": "fa-weixin",
        "html": "\uf1d7;"
    }, {
        "class": "fa-whatsapp",
        "html": "\uf232;"
    }, {
        "class": "fa-wheelchair",
        "html": "\uf193;"
    }, {
        "class": "fa-wheelchair-alt",
        "html": "\uf29b;"
    }, {
        "class": "fa-wifi",
        "html": "\uf1eb;"
    }, {
        "class": "fa-wikipedia-w",
        "html": "\uf266;"
    }, {
        "class": "fa-window-close",
        "html": "\uf2d3;"
    }, {
        "class": "fa-window-close-o",
        "html": "\uf2d4;"
    }, {
        "class": "fa-window-maximize",
        "html": "\uf2d0;"
    }, {
        "class": "fa-window-minimize",
        "html": "\uf2d1;"
    }, {
        "class": "fa-window-restore",
        "html": "\uf2d2;"
    }, {
        "class": "fa-windows",
        "html": "\uf17a;"
    }, {
        "class": "fa-won",
        "html": "\uf159;"
    }, {
        "class": "fa-wordpress",
        "html": "\uf19a;"
    }, {
        "class": "fa-wpbeginner",
        "html": "\uf297;"
    }, {
        "class": "fa-wpexplorer",
        "html": "\uf2de;"
    }, {
        "class": "fa-wpforms",
        "html": "\uf298;"
    }, {
        "class": "fa-wrench",
        "html": "\uf0ad;"
    }, {
        "class": "fa-xing",
        "html": "\uf168;"
    }, {
        "class": "fa-xing-square",
        "html": "\uf169;"
    }, {
        "class": "fa-y-combinator",
        "html": "\uf23b;"
    }, {
        "class": "fa-y-combinator-square",
        "html": "\uf1d4;"
    }, {
        "class": "fa-yahoo",
        "html": "\uf19e;"
    }, {
        "class": "fa-yc",
        "html": "\uf23b;"
    }, {
        "class": "fa-yc-square",
        "html": "\uf1d4;"
    }, {
        "class": "fa-yelp",
        "html": "\uf1e9;"
    }, {
        "class": "fa-yen",
        "html": "\uf157;"
    }, {
        "class": "fa-yoast",
        "html": "\uf2b1;"
    }, {
        "class": "fa-youtube",
        "html": "\uf167;"
    }, {
        "class": "fa-youtube-play",
        "html": "\uf16a;"
    }, {
        "class": "fa-youtube-square",
        "html": "\uf166;"
    }];
}