trigger:
  branches:
    include:
    - '*sprint*'
  paths:
    include:
    - /igx.jobs
    - /d360.core
    - /d360.model
    - /d360.extensions
    - /d360.utils.company
    - /igx.jobs.apiexecutionprocessor
pr:
  autoCancel: false
  drafts: false
  branches:
    include:
    - '*sprint*'
  paths:
    include:
    - /igx.jobs
    - /d360.core
    - /d360.model
    - /d360.extensions
    - /d360.utils.company
    - /igx.jobs.apiexecutionprocessor
name: WebJob-APIExecutionProcessor-$(SourceBranchName)-$(Date:MM-dd-yyyy)$(Rev:.r)
resources:
  repositories:
  - repository: self
    type: git
  - repository: templates
    type: github
    name: Infogix/govern-pipeline-templates
    ref: refs/heads/main
    endpoint: 'govern-build - Service Endpoint'
stages:
- stage: BUILD_NAME
  displayName: 'Set build name'
  dependsOn: []
  jobs:
  - template: build/jobs/job-build-name.yml@templates
- stage: BUILD_SOLUTION
  displayName: 'Build ApiExecutionProcessor'
  dependsOn: []
  jobs:
  - job: BUILD
    displayName: 'Build ApiExecutionProcessor'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
    - template: build/seteps/step-azure-key-vault.yml@templates
      parameters:
        secretsFilter: 'whitesourceApiKey,blackduckApi'
    - template: build/steps/step-t4-transform.yml@templates
    - task: Cache@2
      displayName: 'Cache NuGet packages'
      inputs:
        key: 'nuget-temp | "$(Agent.OS)" | $(Build.SourcesDirectory)/**/packages.config, !$(Build.SourcesDirectory)/igx.jobs.genericcommandprocessor/packages.config'
        restoreKeys: |
          nuget-temp | "$(Agent.OS)"
          nuget-temp
        path: $(UserProfile)/.nuget/packages/
    - template: build/steps/step-dotnet-build.yml
      parameters:
        solutionToRestore: .
        solutionToBuild: igx.jobs.apiexecutionprocessor/igx.jobs.apiexecutionprocessor.csproj
        nuGetCommand: 'restore -Project2ProjectTimeOut 20'
        buildArguments: '/p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.Repository.LocalPath)/apiexecutionprocessor/"'
    - template: build/jobs/job-whitesource-blackduck-scan.yml@templates
      parameters:
        whitesourceApiKey: $(whitesourceApiKey)
        blackduckApi: $(blackduckApi)
        artifactName: ApiExecutionProcessor
        projectName: 'API Execution Processor' 
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: API Execution Processor'
      inputs:
        PathtoPublish: $(Build.Repository.LocalPath)\apiexecutionprocessor\
        ArtifactName: APIExecutionProcessor