trigger:
  branches:
    include:
    - '*sprint*'
  paths:
    include:
    - /igx.jobs
    - /d360.core
    - /d360.model
    - /d360.extensions
    - /d360.utils.company
    - /igx.jobs.workflowdigestprocessor
pr:
  autoCancel: false
  drafts: true
  branches:
    include:
    - '*sprint*'
  paths:
    include:
    - /igx.jobs
    - /d360.core
    - /d360.model
    - /d360.extensions
    - /d360.utils.company
    - /igx.jobs.workflowdigestprocessor
name: WebJob-WorkflowDigestProcessor-$(SourceBranchName)-$(Date:MM-dd-yyyy)$(Rev:.r)
resources:
  repositories:
  - repository: self
    type: git
  - repository: templates
    type: github
    name: Infogix/govern-pipeline-templates
    ref: refs/heads/main
    endpoint: 'govern-build - Service Endpoint'
stages:
- stage: BUILD_NAME
  displayName: 'Set build name'
  dependsOn: []
  jobs:
  - template: build/jobs/job-build-name.yml@templates
- stage: BUILD_SOLUTION
  displayName: 'Build WorkflowDigestProcessor'
  dependsOn: []
  jobs:
  - job: BUILD
    displayName: 'Build WorkflowDigestProcessor'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
    - template: build/steps/step-azure-key-vault.yml@templates
      parameters:
        secretsFilter: 'whitesourceApiKey,blackduckApi'
    - template: build/steps/step-t4-transform.yml@templates
    - template: build/steps/step-dotnet-build.yml@templates
      parameters:
        solutionToRestore: D360.sln
        solutionToBuild: d360.core/d360.core.csproj
        nuGetCommand: 'restore -Project2ProjectTimeOut 20'
        buildArguments: '/p:Configuration=Release /t:Rebuild'
    - task: MSBuild@1
      displayName: Build solution d360.utils.company/d360.utils.company.csproj
      inputs:
        solution: d360.utils.company/d360.utils.company.csproj
        msbuildArguments: /p:Configuration=Release /t:Rebuild
        clean: true
        maximumCpuCount: true
    - task: MSBuild@1
      displayName: Build solution d360.model/d360.model.csproj
      inputs:
        solution: d360.model/d360.model.csproj
        msbuildArguments: /p:Configuration=Release /t:Rebuild
    - task: MSBuild@1
      displayName: Build solution d360.extensions/d360.extensions.csproj
      inputs:
        solution: d360.extensions/d360.extensions.csproj
        msbuildArguments: /p:Configuration=Release /t:Rebuild
    - task: MSBuild@1
      displayName: Build solution igx.jobs/igx.jobs.csproj
      inputs:
        solution: igx.jobs/igx.jobs.csproj
        msbuildArguments: /p:Configuration=Release /t:Rebuild
    - task: MSBuild@1
      displayName: Build WebJob Workflow Digest Processor
      inputs:
        solution: igx.jobs.workflowdigestprocessor/igx.jobs.workflowdigestprocessor.csproj
        msbuildArguments: /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.Repository.LocalPath)/workflowdigestprocessor/"
        clean: true
        maximumCpuCount: true
    - template: build/steps/step-whitesource-scan.yml@templates
      parameters:
        whitesourceApiKey: $(whitesourceApiKey)
        projectName: 'Workflow Digest Processor'
    - template: build/steps/step-blackduck-nuget.yml@templates
      parameters:
        blackduckApiToken: $(blackduckApi)
        projectName: 'InfogixData360-Govern-Webjob-WorkflowDigestProcessor'
        blackDuckScanDirectory: $PWD/igx.jobs.workflowdigestprocessor
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Workflow Digest Processor'
      inputs:
        PathtoPublish: $(Build.Repository.LocalPath)/workflowdigestprocessor/
        ArtifactName: WorkflowDigestProcessor