<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net48</TargetFrameworks>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="entities\Graph\**" />
    <Compile Remove="entities\reference\**" />
    <EmbeddedResource Remove="entities\Graph\**" />
    <EmbeddedResource Remove="entities\reference\**" />
    <None Remove="entities\Graph\**" />
    <None Remove="entities\reference\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="antisamy\antisamy-govern.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="antisamy\antisamy-govern.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="versioning.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>versioning.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OWASP.AntiSamy" Version="1.2.1" />
    <PackageReference Include="System.ComponentModel" Version="4.3.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\constants\constants.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="resources\Label.Designer.cs">
		<DependentUpon>Label.resx</DependentUpon>
		<DesignTime>True</DesignTime>
		<AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="resources\Error.Designer.cs">
		<DependentUpon>Error.resx</DependentUpon>
		<DesignTime>True</DesignTime>
		<AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="resources\Information.Designer.cs">
		<DependentUpon>Information.resx</DependentUpon>
		<DesignTime>True</DesignTime>
		<AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="resources\Enums.Designer.cs">
		<DependentUpon>Enums.resx</DependentUpon>
		<DesignTime>True</DesignTime>
		<AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="versioning.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>versioning.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="resources\Label.resx">
      <LastGenOutput>Label.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="resources\Error.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Error.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="resources\Information.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>Information.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="resources\Enums.resx">
      <LastGenOutput>Enums.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="resources\Enums.*.resx">
			<DependentUpon>resources\Enums.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="resources\Error.*.resx">
			<DependentUpon>resources\Error.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="resources\Information.*.resx">
			<DependentUpon>resources\Information.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="resources\Label.*.resx">
			<DependentUpon>resources\Label.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
    <None Update="versioning.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>versioning.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
